### ISSUE TITLE
Problem with footnote placement

### ISSUE THREAD

**Issue by nignasi** [T-F-S/tcolorbox#10]
I want to use `\footnotemark` inside `tcolorbox` and `\footnotetex` outside it. If there is no enough space for the next box, it jumps to next page but this jump shortens previous page and footnotes are placed just below last box and not at the end of the page.

As an example compare footnote placement between page 1 and 2 in next example.

If a manual `\newpage` command is inserted after second box, footnote placement is correct.
[306373.pdf](https://github.com/T-F-S/tcolorbox/files/239990/306373.pdf)

```
\documentclass{article}
\usepackage[most]{tcolorbox}

\usepackage{tikz}

\newtcolorbox{mybox}{empty, sidebyside, notitle, lower separated=false}

\begin{document}

\begin{mybox}
\begin{tikzpicture}
\draw (0,0) rectangle ++(5,6);
\end{tikzpicture}
\tcblower % right column
I'm a description.
\end{mybox}

\begin{mybox}
\begin{tikzpicture}
\draw (0,0) rectangle ++(5,6);
\end{tikzpicture}
\tcblower % right column
I'm a description.\footnotemark
\end{mybox}
\footnotetext{I'm a footnote.}

\begin{mybox}
\begin{tikzpicture}
\draw (0,0) rectangle ++(5,6);
\end{tikzpicture}
\tcblower % right column
I'm a description.
\end{mybox}

\begin{mybox}
\begin{tikzpicture}
\draw (0,0) rectangle ++(5,6);
\end{tikzpicture}
\tcblower % right column
I'm a description.\footnotemark
\end{mybox}
\footnotetext{I'm a footnote.}
\end{document}
```

**Comment by T-F-S** [comment]
I think that this problem is not related to `tcolorbox`. You get the same result, if `tcolorbox` is removed and the situation is build up using `tikzpicture` alone:

```latex
\documentclass{article}

\usepackage{tikz}

\begin{document}

\begin{tikzpicture}
\draw (0,0) rectangle ++(5,7);
\node[right] at (6,3) {I'm a description.};
\end{tikzpicture}

\begin{tikzpicture}
\draw (0,0) rectangle ++(5,7);
\node[right] at (6,3) {I'm a description.\footnotemark};
\end{tikzpicture}
\footnotetext{I'm a footnote.}

% \newpage

\begin{tikzpicture}
\draw (0,0) rectangle ++(5,7);
\node[right] at (6,3) {I'm a description.};
\end{tikzpicture}

\begin{tikzpicture}
\draw (0,0) rectangle ++(5,7);
\node[right] at (6,3) {I'm a description.\footnotemark};
\end{tikzpicture}
\footnotetext{I'm a footnote.}

\end{document}
```
Let me know, if I have misinterpreted something. Currently, I think this is outside the scope of `tcolorbox`.

**Comment by nignasi** [comment]
You are right, It seems to be a problem with `footnote` command with early page breaks, not related with tcolorbox or even TikZ. It's solved with `\usepackage[bottom]{footmisc}`.

Sorry for the noise.

**Comment by T-F-S** [comment]
No problem :-)
