### ISSUE TITLE
minor typos

### ISSUE THREAD

**Issue by FrankMittelbach** [T-F-S/tcolorbox#102]
16.8 contains three times the word "examles"

**Comment by T-F-S** [comment]
Thank your for reporting the typos. I will correct them for the next version.

**Comment by muzimuzhi** [comment]
Note: resolved in v4.31 by https://github.com/T-F-S/tcolorbox/commit/55d9deed444eef58c65a88b893500255f44ac7ba, more specifically by [these lines](https://github.com/T-F-S/tcolorbox/commit/55d9deed444eef58c65a88b893500255f44ac7ba#diff-c69ada293c8855833f5d664e7edd99c0L1185-L1187).
