### ISSUE TITLE
In preamble, tcbraster env cannot be directly saved in a box

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#104]
From this question: https://tex.stackexchange.com/questions/547802/exam-tcolorbx-calculate-the-header-height-then-pass-it-to-geometry

```tex
\documentclass{article}
\usepackage[raster]{tcolorbox}

\newsavebox\mybox
\savebox\mybox{%
  \begin{tcbraster}[raster columns=1]
    \begin{tcolorbox}
      content
    \end{tcolorbox}
  \end{tcbraster}%
}

\begin{document}
test
\end{document}
```

The above example raises `Missing \begin{document}` error. It seems the problem is caused by the `\noindent` at the end of `\begin{tcbraster}`.
https://github.com/T-F-S/tcolorbox/blob/3957996cabb0e840cd1a077c28dd59d3a60d4332/tex/latex/tcolorbox/tcbraster.code.tex#L206

If this is by design, then maybe some reminders (or workarounds) can be added to the package documentation.

**Comment by T-F-S** [comment]
The `\noindent` is needed by design. The linked question has some exotic usage for `tcbraster` outside the intended scope. You gave a good answer there and I added another one suggesting `tcboxedraster`.

To be honest: For the documentation I would not know what to write and describe to warn for a `\noindent`...

**Comment by muzimuzhi** [comment]
> To be honest: For the documentation I would not know what to write and describe to warn for a `\noindent`...

For example, add something like "If you want to store a raster in a box (especially in preamble or in vertical mode), use `tcboxedraster` other than `tcbraster` environment" under the documentation of `tcbraster` environment.

The point is, usages or warnings recorded in documentation can (possibly) help more users than those recorded in bug tracker or q&a website only.
