### ISSUE TITLE
Line spacing in customized tcolorbox

### ISSUE THREAD

**Issue by weimiao1993** [T-F-S/tcolorbox#107]
I'm trying to create tcolorbox for a specific environment. The following code works for me now:

`\renewtcolorbox[use counter=countdef]{df}[1][]{
  title={Definition \the\c@countdef\ : #1},
  before upper={\protected@edef\@currentlabel{\csname p@definition\endcsname\csname thedefinition\endcsname}},
  colframe=arsenic!75,             
    colback=arsenic!5,
    fonttitle=\fontsize{9}{12},
}`

I'm trying to add an option controlling the line spacing in the tcolorbox. I found a solution online saying that I could add `code = \singlespace' to the customized environment. However, I was told 'I don't recognize \tcb\code' when I wrote

`\renewtcolorbox[use counter=countdef, code = \singlespace]{df}[1][]{
  title={Definition \the\c@countdef\ : #1},
  before upper={\protected@edef\@currentlabel{\csname p@definition\endcsname\csname thedefinition\endcsname}},
  colframe=arsenic!75,             
    colback=arsenic!5,
    fonttitle=\fontsize{9}{12},
}`

How should I set the line spacing in the tcolorbox? Thanks!

**Comment by muzimuzhi** [comment]
Options `fontupper` and `fontlower` are sufficient:

```tex
\documentclass{article}
\usepackage{tcolorbox}
\usepackage{lipsum}

\newtcolorbox{mybox}[1][]{
  title={Title\ifblank{#1}{}{: #1}}, % improved the case when #1 is blank
  fonttitle=\fontsize{9}{12}\selectfont, % \selectfont is required here
  fontupper=\linespread{1.5}\selectfont,
  fontlower=\linespread{0.8}\selectfont
}

\def\dummy{%
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua.}

\begin{document}
\begin{mybox}
  \dummy
  \tcblower
  \dummy
\end{mybox}

\begin{mybox}[title]
  \dummy
  \tcblower
  \dummy
\end{mybox}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/88618709-5c612e80-d0cc-11ea-9f3b-3c118fcfa2c1.png)

Please always provide complete example (also called [mwe](https://tex.meta.stackexchange.com/q/228)) that starts with `\documentclass` and ends with `\end{document}`. This helps others to help you. In your code snippet, environment `df` is redefined before I see its definition, counters `countdef` and `definition` are not defined, and color `arsenic` is not defined.
