### ISSUE TITLE
Improve usability of options `highlight math` and `highlight math style`

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#109]
From this question: https://tex.stackexchange.com/q/556832

Firstly, is it worth to document the initial value of style `highlight math`, which is `notitle,nophantom,colframe=red,colback=yellow!25!white`?

Then, when user wants to append styles to `highlight math`, following option naming scheme of `tcolorbox`, something like
```tex
\tcbset{
  % does a pre variant useful as well?
  highlight math style app/.style={highlight math/.append style={#1}}
}
```
would be helpful.

------
PS: While there are more and more hooks options, do they need to be mentioned in the doc of corresponding base keys? This may help users to find and use hooks options. For (a crude) example,
```tex
\newcommand\mentionTcbHooksKey{%
  Hookable versions \refKey{/tcb/#1 pre} and \refKey{/tcb//tcb/#1 app} are available in \mylib{hooks} library.}

\begin{docTcbKey}{key1}{...}
   <contents> \mentionTcbHooksKey{key1}
\end{docTcbKey}
```

**Comment by T-F-S** [comment]
Documentation expanded by version `4.32 (2020-09-17)`.
