### ISSUE TITLE
Change in output with lualatex 0.95

### ISSUE THREAD

**Issue by grizzilus** [T-F-S/tcolorbox#11]
I am pretesting TeX Live 2016. The following example produces different output using lualatex in TeX Live 2015 and TeX Live 2016. I used version 3.91 of tcolorbox for both tests.

```latex
\documentclass{article}

\usepackage{tcolorbox}

\tcbuselibrary{breakable}

\tcbset{breakable}

\usepackage{lipsum}

\begin{document}

\vspace*{5.5in}

test

\begin{tcolorbox}
    \begin{minipage}[t]{\linewidth}
        \lipsum[1-2]
    \end{minipage}
\end{tcolorbox}

\end{document}
```

Here are the output files:
[2015.pdf](https://github.com/T-F-S/tcolorbox/files/267029/2015.pdf)
[2016.pdf](https://github.com/T-F-S/tcolorbox/files/267028/2016.pdf)

There were many changes in the luatex included in TeX Live 2016, but I don't see anything in the `breakable` library that causes the behavior change in the example above.

**Comment by T-F-S** [comment]
Currently, I have no machine with TeX Live to test your code, but with the current update to MiKTeX, `luatex` and `tikz/pgf` (including `tcolorbox`) seem to be not compatible any more.

Compiling your example with `luatex` (current MiKTeX) does not work at all.

There are some solution hints in the following links:

http://tex.stackexchange.com/questions/309140/after-miktex-update-when-using-lualatex-package-pgf-error-driver-file-pgfsys

https://sourceforge.net/p/pgf/bugs/384/

https://sourceforge.net/p/miktex/mailman/message/35020847/

For my system, no hint helped. But, maybe, for TeX Live 2016 one of the hints is useful.

I hope that the `lualatex` / `pgf` problem is solved soon. I guess this will also solve the issue you found which I think is not `tcolorbox`-specific.

**Comment by grizzilus** [comment]
I installed MikTeX with the current pre-release packages to get luatex 0.95. The TeX Live developers reached an agreement with the PGF author to include a driver in TeX Live 2016, but MikTeX does not have the updated files. However, the files simply rename the primitives that were changed in luatex, so it is easy to replicate in MikTeX by running the following example:

```latex
\RequirePackage{luatex85}
\def\pgfsysdriver{pgfsys-pdftex.def}
\documentclass{article}

\usepackage{tcolorbox}

\tcbuselibrary{breakable}

\tcbset{breakable}

\usepackage{lipsum}

\begin{document}

\vspace*{5.5in}

test

\begin{tcolorbox}
    \begin{minipage}[t]{\linewidth}
        \lipsum[1-2]
    \end{minipage}
\end{tcolorbox}

\end{document}
```

Adding the `luatex85` package defines the original names for the changed primitives, and the second line uses the driver that was always used in the past. The output with this example is the same as what I posted above.

To see if something in PGF was at fault on a lower level, I modified the example above to use the empty skin, and encountered the same page-breaking issue.

To see if some loaded code from PGF was causing other problems, I replaced the `RequirePackage{pgf}` in `tcolorbox.sty` with `\RequirePackage{pgfkeys}` and `\RequirePackage{xcolor}`, and the page-breaking issue was still there.

I'll continue to investigate. Maybe then TeX Live 2016 is released soon someone will have more information.

**Comment by T-F-S** [comment]
Thank you for the information on how to make `lualatex`  and `pgf` work together using MiKTeX.

With it, I was able to reproduce the problem. It is not related to `pgf` as I assumed first. With the current implementation of `lualatex` and `pdflatex`, there are different results when using `\vsplit` for an unsplittable object like in your example. 

With `pdflatex` and presumable the *old* `lualatex`, this `\vsplit` results in a box with wrong dimensions and a high `\badness`. 

With the current `lualatex`,  this `\vsplit` results in a box with correct (but too large) dimensions and a `\badness` of `0`. I don't know if this new behaviour is intended or not.

I can offer the following patch which works for the example. I cannot tell yet, if it does something bad in other places:

```latex
\RequirePackage{luatex85}
\def\pgfsysdriver{pgfsys-pdftex.def}
\documentclass{article}

\usepackage{tcolorbox}

\tcbuselibrary{breakable}

\makeatletter%   BEGIN PATCH
\def\tcb@split@upper@box@and@assemble{%
  \vfuzz=\maxdimen\vbadness=10000\savingvdiscards=1%
  \setbox\tcb@upperbox=\vsplit\tcb@totalupperbox to\tcb@split@dim%
  \edef\tcb@upper@box@badness{\the\badness}%
  %>> lualatex
  \ifdim\dimexpr\ht\tcb@upperbox+\dp\tcb@upperbox>\tcb@split@dim\relax%
    \edef\tcb@upper@box@badness{1000000}%
  \fi
  %<<
  \ifnum\tcb@upper@box@badness=1000000\relax%
    \setbox\tcb@totalupperbox=\vbox{%
      \unvbox\tcb@upperbox%
      \splitdiscards%
      \unvbox\tcb@totalupperbox}%
  \else%
    \tcb@setbox@upper{\tcb@split@dim}{\tcb@upperbox}%
  \fi%
  \vbadness=\tcb@thevbadness\vfuzz=\tcb@thevfuzz\savingvdiscards=0%
}
\makeatother%   END PATCH

\tcbset{breakable}

\usepackage{lipsum}

\begin{document}

\vspace*{5.5in}

test

\begin{tcolorbox}
    \begin{minipage}[t]{\linewidth}
        \lipsum[1-2]
    \end{minipage}
\end{tcolorbox}

\end{document}
```

Let me know, if this patch fixes the problem for your document(s). I have to investigate further, if the patch works and does no harm.

**Comment by grizzilus** [comment]
The patch works for the issues with non-breakable content, but it looks like there are some unintended effects. In the following example, the box is on page 1 using luatex 0.80 and one page 2 using luatex 0.95.

```latex
\documentclass{article}

\usepackage{tcolorbox}

\tcbuselibrary{breakable}

\makeatletter%   BEGIN PATCH
\def\tcb@split@upper@box@and@assemble{%
  \vfuzz=\maxdimen\vbadness=10000\savingvdiscards=1%
  \setbox\tcb@upperbox=\vsplit\tcb@totalupperbox to\tcb@split@dim%
  \edef\tcb@upper@box@badness{\the\badness}%
  %>> lualatex
  \ifdim\dimexpr\ht\tcb@upperbox+\dp\tcb@upperbox>\tcb@split@dim\relax%
    \edef\tcb@upper@box@badness{1000000}%
  \fi
  %<<
  \ifnum\tcb@upper@box@badness=1000000\relax%
    \setbox\tcb@totalupperbox=\vbox{%
      \unvbox\tcb@upperbox%
      \splitdiscards%
      \unvbox\tcb@totalupperbox}%
  \else%
    \tcb@setbox@upper{\tcb@split@dim}{\tcb@upperbox}%
  \fi%
  \vbadness=\tcb@thevbadness\vfuzz=\tcb@thevfuzz\savingvdiscards=0%
}
\makeatother%   END PATCH

\tcbset{breakable}

\begin{document}

\vspace*{6in}

\begin{tcolorbox}
	text

	text

	text

	\begin{enumerate}
		\item text
		\item text
		\item text
	\end{enumerate}
\end{tcolorbox}

\end{document}
```

I'll see if there are any other cases I can find where the behavior changes now that I know where the change in behavior is (with vsplit).

**Comment by grizzilus** [comment]
I am not sure if the change in vsplit is intended, so I reported the change to the luatex bug tracker to confirm: http://tracker.luatex.org/view.php?id=974

**Comment by grizzilus** [comment]
Looks like the change in `vsplit` is a bug. I built the current luatex from source and `vsplit` is back to its old behavior. This build showed the version as 0.96, so I am not sure when it will be released to the major distributions, so I'll keep an eye on what versions of luatex end up on TeX Live and MiKTeX in the coming weeks.

**Comment by T-F-S** [comment]
I can confirm your observations with your second example. With the current `vsplit` behavior change in luatex 0.95, I see no way to get the same output for luatex and pdftex.

Without the patch, overfull splitted boxes are not detected (for luatex 0.95). The result is quite terrible as in your example 1.

With the patch, compressable splitted boxes are considered overfull (for luatex 0.95). Your example 2 has an inner height of 92.15pt which can be compressed to 83.46pt. The result is bad (page break), but better than to have situation 1.

With the old (=normal) `vsplit` behavior, the patch should have no effects besides costing a tiny bit more compilation time.

**Comment by grizzilus** [comment]
I made a patch to work around the issue. This patch required loading the package `ifluatex`.

```latex
\makeatletter%   BEGIN PATCH
\def\tcb@split@upper@box@and@assemble{%
  \vfuzz=\maxdimen\vbadness=10000\savingvdiscards=1%
  \ifluatex
    \ifnum\luatexversion=95
      \directlua{%
        local vlist = tex.splitbox("tcb@totalupperbox", tex.sp("\tcb@split@dim"), "exactly")
        tex.setbox("tcb@upperbox", vlist)
      }%
      \edef\tcb@upper@box@badness{\the\badness}%
    \else
      \setbox\tcb@upperbox=\vsplit\tcb@totalupperbox to\tcb@split@dim%
      \edef\tcb@upper@box@badness{\the\badness}%
    \fi
  \else
    \setbox\tcb@upperbox=\vsplit\tcb@totalupperbox to\tcb@split@dim%
    \edef\tcb@upper@box@badness{\the\badness}%
  \fi
  \ifnum\tcb@upper@box@badness=1000000\relax%
    \setbox\tcb@totalupperbox=\vbox{%
      \unvbox\tcb@upperbox%
      \splitdiscards%
      \unvbox\tcb@totalupperbox}%
  \else%
    \tcb@setbox@upper{\tcb@split@dim}{\tcb@upperbox}%
  \fi%
  \vbadness=\tcb@thevbadness\vfuzz=\tcb@thevfuzz\savingvdiscards=0%
}
\makeatother%   END PATCH
```

This patch accessed the equivalent of `vsplit` from lua and passes the argument `"exactly"` to get the normal `vsplit` behavior (what this value means is explained in the manual for luatex 0.96).

I tested this patch with TeX Live 2015 and 2016 with both pdflatex and lualatex and both examples above and get consistent output. I think the patch could be improved to check for a range of luatex versions with this bug, but I don't think anything between 0.80 and 0.95 was released in a standard TeX distribution so this step is not really necessary. But I can find the affected versions and make a pull request with the changes if you would like (assuming this patch is usable).

**Comment by T-F-S** [comment]
Thank you for providing this patch with the lua code (I have not used luatex before).

I have taken this code to make a preview version (3.92pre1) of `tcolorbox` which is available via Github now. I hesitated to load `ifluatex` by default. Therefore, the logic is the following:

- if pdftex or luatex (not 0.95) is used without `ifluatex`, the not-patched code is used and everthing should work well.

-  if pdftex or luatex (not 0.95) is used with `ifluatex`, the not-patched code is used and everthing should work well.

- if luatex 0.95 is used without `ifluatex`, the not-patched code is used and you get all the trouble.

-  if luatex 0.95 is used with `ifluatex` (loaded *before* `tcolorbox` or its `breakable` library), the patched code is used and everthing should work well.

So, to counteract the luatex 0.95 problem, a user has to add `ifluatex` (otherwise it would have to be included to `breakable` without sense for most users and/or the future).

Please, let me know if `tcolorbox 3.92pre1` works like expected or if new problems arise.

**Comment by grizzilus** [comment]
I tested a few long documents and noticed one issue. For some reason the `savingvdiscards` value is not set correctly with the patch. Setting things from the lua end temporarily fixes the issue and I get the expected behavior from tcolorbox with luatex 0.80 and 0.95. Here is an updated patch from 3.92pre1:

```latex
% patch for luatex 0.95
% needs package 'ifluatex' to be loaded before 'breakable' is loaded
\ifcsdef{ifluatex}{\ifluatex\ifnum\luatexversion=95\relax%
  \def\tcb@vsplit@upper{%
    \directlua{%
      tex.savingvdiscards = 1
      local vlist = tex.splitbox("tcb@totalupperbox", tex.sp("\tcb@split@dim"), "exactly")
      tex.setbox("tcb@upperbox", vlist)
      tex.savingvdiscards = 0
    }%
    \edef\tcb@upper@box@badness{\the\badness}%
  }%
  \def\tcb@vsplit@lower{%
    \directlua{%
      tex.savingvdiscards = 1
      local vlist = tex.splitbox("tcb@totallowerbox", tex.sp("\tcb@split@dim"), "exactly")
      tex.setbox("tcb@lowerbox", vlist)
      tex.savingvdiscards = 0
    }%
    \edef\tcb@lower@box@badness{\the\badness}%
  }%
\fi\fi}{}
```

Also, the `pgf` package has defined `\pgfutil@luatex` since 2012. So you can replace `\ifluatex` with `\pgfutil@ifluatex` since `pgf` is loaded anyway. I can't imagine a situation where someone is using luatex 0.95 and pgf more than four years old. Here is the definition of `\pgfutil@ifluatex` for reference:

```latex
% luatex stuff
% We assume luatex version > 0.39:
%   - \directlua <general text> will work
%   - \directlua is the only luatex primitive that we can assume
%     accessible without being prefixed by the format via
%     tex.enableprimitives.
% Ideas taken from the ifluatex package (Heiko Oberdiek)
\let\pgfutil@ifluatex\iffalse
\begingroup\expandafter\expandafter\expandafter\endgroup
\expandafter\ifx\csname directlua\endcsname\relax
\else
  \expandafter\let\csname pgfutil@ifluatex\expandafter\endcsname
    \csname iftrue\endcsname
\fi
```

**Comment by T-F-S** [comment]
I've uploaded a new preview version (3.92pre2) of `tcolorbox` which incorporates the `savingvdiscards` changes you suggested.

Also, I changed the luatex detection in a way that a user has not to think about including `ifluatex` manually. Without luatex (detected according to the non-existing `\directlua`), there is no patching. With luatex, the `ifluatex` package is included automatically for accessing the version number.

The patch 3.92pre1 is the following:

```latex
% patch for luatex 0.95 (thanks to Jeremy Engel)
\expandafter\ifx\csname directlua\endcsname\relax\else
  \RequirePackage{ifluatex}
  \ifnum\luatexversion=95\relax
  \def\tcb@vsplit@upper{%
    \directlua{%
      tex.savingvdiscards = 1
      local vlist = tex.splitbox("tcb@totalupperbox", tex.sp("\tcb@split@dim"), "exactly")
      tex.setbox("tcb@upperbox", vlist)
      tex.savingvdiscards = 0
    }%
    \edef\tcb@upper@box@badness{\the\badness}%
  }
  \def\tcb@vsplit@lower{%
    \directlua{%
      tex.savingvdiscards = 1
      local vlist = tex.splitbox("tcb@totallowerbox", tex.sp("\tcb@split@dim"), "exactly")
      tex.setbox("tcb@lowerbox", vlist)
      tex.savingvdiscards = 0
    }%
    \edef\tcb@lower@box@badness{\the\badness}%
  }
\fi\fi
```

Alternatively, use 3.92pre2 from GitHub.

If nothing new comes up, I plan to make this version official in the near future before too many users get in trouble using luatex 0.95.

**Comment by grizzilus** [comment]
I gave this version a quick test and everything seems to be working. I'll keep using 3.92pre2 until you make a new release to see if anything else comes up.

**Comment by T-F-S** [comment]
`tcolorbox` version 3.92 is now officially launched via CTAN and should be available on its mirrors in the next days.
