### ISSUE TITLE
Provide IfValueT and IfValueF (and friends)

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#111]
It would be nice for the `xparse` library to provide the option keys `IfValueT` and  `IfValueF` in addition to `IfValueTF`. And similarly for `IfNoValueTF` and `IfBooleanTF`.

**Comment by T-F-S** [comment]
Yes, that makes sense :-)

**Comment by T-F-S** [comment]
Implemented by version `4.32 (2020-09-17)`.
