### ISSUE TITLE
Distance between text and following tcolorbox depends on descenders in in the line

### ISSUE THREAD

**Issue by FrankMittelbach** [T-F-S/tcolorbox#115]
In the following example

```
\documentclass{article}

\usepackage{tcolorbox}

\showoutput

\begin{document}

Some text before
\begin{tcolorbox}
  XX
\end{tcolorbox}
\ldots{} and some after.
\end{document}
```
the text before looks rather ill placed. Adding an letter with a descender or a \strut makes it look reasonably well balanced. I guess the logic should take a look a \prevdepth and adds some extra space if that is noticably smaller than the depth of a strut.

The above gives:

<img width="519" alt="Screenshot 2020-09-21 at 22 16 13" src="https://user-images.githubusercontent.com/1062981/93816699-2a95bf80-fc58-11ea-9816-1d3e81a7d389.png">

while with a strut we get

<img width="520" alt="Screenshot 2020-09-21 at 22 16 49" src="https://user-images.githubusercontent.com/1062981/93816744-38e3db80-fc58-11ea-9c0a-a416137f4c64.png">

**Comment by T-F-S** [comment]
I shy away from changing the distance algorithm, if not needed for critical things. Every change influences all existing documents in a possibly annoying way. I had to do in the past and was forced to rearrange page breaks for many, many pages in many documents (and I know that I am not the only one).

But I could add new options for such a balancing. The standard option is `autoparskip` and could be supplemented by a new option `autoparskip strut`:

```latex
\documentclass{article}

%\usepackage{parskip}

\makeatletter
\AtBeginDocument{%
\ifdim\parskip>\z@\relax%
  \tcbset{autoparskip strut/.style=parskip strut}%
\else%
  \tcbset{autoparskip strut/.style=noparskip strut}%
\fi%
}
\makeatother

\usepackage{tcolorbox}


\makeatletter
\tcbset{
  parskip strut/.style={before={\ifnum\lastnodetype=-1\relax\else\par%
      \ifvmode\edef\tcb@prevdepth{\the\glueexpr.3\baselineskip+\lineskip+\parskip}%
      \def\tcb@undo@before{\addvspace{-\glueexpr\tcb@prevdepth}}%
      \pagebreak[0]\addvspace{\glueexpr.3\baselineskip-\prevdepth}\fi\fi\noindent},
    after={\tcb@parfillskip@check\par}},
  noparskip strut/.style={before={\ifnum\lastnodetype=-1\relax\else\par%
      \ifvmode\edef\tcb@prevdepth{\the\glueexpr.3\baselineskip+\lineskip}%
      \def\tcb@undo@before{\addvspace{-\glueexpr\smallskipamount+\tcb@prevdepth}}%
      \pagebreak[0]\addvspace{\glueexpr.3\baselineskip-\prevdepth}\smallskip\fi\fi\noindent},
    after={\tcb@parfillskip@check\par\smallskip}},
  autoparskip strut/.code={\let\tcb@use@autoparskip=\tcb@use@auto@parskipstrut},
}

\def\tcb@use@auto@parskipstrut{%
  \tcbset{autoparskip strut}%
}

\makeatother

\showoutput

%\tcbset{autoparskip strut}

\begin{document}

Some text before
\par\pagebreak[0]\smallskip\parindent=0pt%
\rule{\linewidth}{1cm}\par\smallskip
\ldots{} and some after.

\bigskip

Some text before
\begin{tcolorbox}
  XX (normal)
\end{tcolorbox}
\ldots{} and some after.

\bigskip

Some text before\strut
\begin{tcolorbox}
  XX (with strut)
\end{tcolorbox}
\ldots{} and some after.

\bigskip

Some text before
\begin{tcolorbox}[autoparskip strut]
  XX (with automated strut)
\end{tcolorbox}
\ldots{} and some after.

\end{document}
```

This gives

![distance](https://user-images.githubusercontent.com/7982989/93859149-8b0b1800-fcbd-11ea-9a99-e61b2c8a1c00.jpg)

The rule is just for comparison with the first tcolorbox showing the standard distances. Actually, it behaves like a rule box.

The second tcolorbox has a manual strut in the text before.

The last tcolorbox uses the option `autoparskip strut` which complements the vertical space automatically.  `autoparskip strut` can be used on a per-box basis or as a global preamble option to change the default algorithm.

**Comment by FrankMittelbach** [comment]
> I shy away from changing the distance algorithm, if not needed for 
> critical things. Every change influences all existing documents in a 
> possibly annoying way. I had to do in the past and was forced to 
> rearrange page breaks for many, many pages in many documents (and I know 
> that I am not the only one).

I fully understand. It would be a change altering older documents and it 
is always a question how high one values backward compatibility.

> But I could add new options for such a balancing. The standard option is 
> |autoparskip| and could be supplemented by a new option |autoparskip strut|:

That would certainly be an option. An slight variation (though less 
backward compatible) would be to make that new option the default.

In favor would be  the fact that  (imho) is is actually a bug and fixing 
bugs through adding options that the user always has to set to get the 
correct behavior is, while often done in the TeX world, not that great.
But of course, the downside is then that to rerun an old document you 
have to explicitly set "autoparskip" to get the old behavior if you 
experience page break changes.

I personally think less "fix-for-xyz" options are preferable, but as I 
said, I understand the other view quite well having maintained LaTeX for 
about 30+ years. Anyway, such an option (whether default or not) would 
be very much appreciated as the current results sometimes look rather 
odd and to get a changed vertical formatting, if you change, say, "void 
value" to "empty value" is not nice.

**Comment by muzimuzhi** [comment]
A compatibility key, like the `compat=<version>` in `pgfplots`, though complicates the maintaining work, would be another option.

**Comment by T-F-S** [comment]
Version 4.40 (2020/09/25) has two new options `before skip balanced` and `after skip balanced` which provide the requested balanced view. These options are the **default** settings now, replacing `autoparskip` (etc.).

Note that the new default settings cause small vertical changes compared with the old ones. Old documents may need adapted manual page breaks where used.

If needed, the old settings can be restored using

```latex
\tcbsetforeverylayer{autoparskip}
```

in the document preamble.

For boxes inside a box (`tcolorbox` or `minipage`), vertical changes can be more obvious, especially, if the package `parskip` is used. There is no visible leading glue any more for a leading `tcolorbox` in a box. But in other cases, a box in a box inserts the same glue as an outer box (with `parskip`, this was different in the past).

**Comment by T-F-S** [comment]
Since https://github.com/T-F-S/tcolorbox/issues/122 has nothing to do with #115, I close #115 again.

**Comment by mlhetland** [comment]
I may be misunderstanding your meaning of **default**, here (and the initial values specified in the docs), but is
```latex
beforeafter skip balanced = 0.5\baselineskip plus 2pt
```
equivalent to what you would expect, with just a plain `tcolorbox`, setting no options explicitly?

This is not what I'm seeing (version 5.0.2, 2022/01/07), though setting this option explicitly works fine.

**Comment by muzimuzhi** [comment]
> [..] but is
> 
> ```
> beforeafter skip balanced = 0.5\baselineskip plus 2pt
> ```
> 
> equivalent to what you would expect, with just a plain `tcolorbox`, setting no options explicitly?

Yes but since [v4.40](https://github.com/T-F-S/tcolorbox/blob/master/doc/latex/tcolorbox/CHANGES.md#changed-7)

> `before skip` and `before skip` balanced do not insert glue now, if the tcolorbox is the first element in a minipage (or sourrounding tcolorbox)

**Comment by mlhetland** [comment]
Indeed – I'm aware of this (I've also looked at the source for `before skip balanced`). The problem is, I don't seem to be getting the proper behavior by default. I.e., the following code does not look the same with and without the commented-out line:

```latex
\documentclass{article}
\usepackage{tcolorbox}
% \tcbset{beforeafter skip balanced = 0.5\baselineskip plus 2pt}
\begin{document}
Before
\begin{tcolorbox}
Contents
\end{tcolorbox}
After
\end{document}
```

**Comment by FrankMittelbach** [comment]
Am 23.06.22 um 14:16 schrieb Magnus Lie Hetland:
> These options are the default settings now,

that statement sounds as if I was wrong and Thomas decided differently, 
so perhaps better he clarifies instead of we are guessing :-) The area 
is subtle so bugs aren't impossible (from my experience)

**Comment by T-F-S** [comment]
I looked into it and I found the reason for the problem. There is leftover `autoparskip` setting (currently in line 2569) which overrules the initialization a few lines before. 

Writing these words I see that @muzimuzhi also found this line. Alas, I think the solution is delicate - I continue on https://github.com/T-F-S/tcolorbox/issues/182

**Comment by T-F-S** [comment]
Just to sum it up for notifications. It is a regression bug introduced with v5.0.0 last Christmas and I will make a new release tomorrow, if no new things come up, see https://github.com/T-F-S/tcolorbox/issues/182
