### ISSUE TITLE
difference between skin=beamer and beamer as a key?

### ISSUE THREAD

**Issue by FrankMittelbach** [T-F-S/tcolorbox#116]
The manual states in 10.7 that `beamer` is an abbreviation for setting `skin=beamer`. However
```
\documentclass{article}

\setlength\textwidth{159.0pt}

\usepackage{tcolorbox}
\tcbuselibrary{skins}

\begin{document}
\begin{tcolorbox}[title=My title]
This is my content.
\end{tcolorbox}
\begin{tcolorbox}[skin=beamer,title=My title]
This is my content.
\end{tcolorbox}
\begin{tcolorbox}[beamer,title=My title]
This is my content.
\end{tcolorbox}
\end{document}
```
using `skin=beamer` only results in some slight shading below the title, but no change in the title or shading elsewhere, while `beamer`alters the appearence noticeably. So either I'm misinterpreting the documentation or there is some error.

<img width="559" alt="Screenshot 2020-09-22 at 18 34 41" src="https://user-images.githubusercontent.com/1062981/93911127-4c4b8100-fd02-11ea-9cdf-3f22156c5193.png">

Also notice that there doesn't seem to be any need (these days?) to add `\usetikzlibrary{shadings}` it clearly works without that setting.

There are some places where examples say `skin=beamer,beamer` but I couldn't see that this was making any difference to just using `beamer`.

**Comment by muzimuzhi** [comment]
> The manual states in 10.7 that `beamer` is an abbreviation for setting `skin=beamer`. However
> [...]
> using `skin=beamer` only results in some slight shading below the title, but no change in the title or shading elsewhere, while `beamer`alters the appearence noticeably. So either I'm misinterpreting the documentation or there is some error.

The manual also says

> It (key `/tcb/beamer`) also changes the geometry and some style options.

https://github.com/T-F-S/tcolorbox/blob/78a915c1b1971a82cd3cce09f6008ccc065ab625/doc/latex/tcolorbox/tcolorbox.doc.skins.tex#L4039-L4042

https://github.com/T-F-S/tcolorbox/blob/78a915c1b1971a82cd3cce09f6008ccc065ab625/tex/latex/tcolorbox/tcbskins.code.tex#L677

**Comment by FrankMittelbach** [comment]
If that would have been a single sentence such as

   beamer is an abbreviation for ... and in addition changes ...

I would not have been puzzled, but the way it is written I have interpreted that as an explanation of what `skin=beamer` does. So I would still maintain that it is ambiguous.

**Comment by muzimuzhi** [comment]
> If that would have been a single sentence such as
> 
> beamer is an abbreviation for ... and in addition changes ...

Perhaps key `beamer` could be documented as 
 - `/tcb/beamer`, style, initially `skin=beamer,boxrule=0mm,titlerule=1mm,toptitle=0.5mm,arc=2mm,fonttitle=\bfseries,drop fuzzy shadow`
 - This key applies `skin=beamer` and changes the geometry and some style options.

**Comment by T-F-S** [comment]
The general idea of `skin=XXX` and `XXX` is
- `skin=XXX` never changes the box geometry
- `XXX` uses `skin=XXX` and possibly also changes geomtry and other stuff

For some skins like `enhanced`, there is no difference, but for `beamer` there is. To inform users,
I thought **Zeigen mit dem Zaunpfahl** with a big yellow box would be a good idea:

![beamer](https://user-images.githubusercontent.com/7982989/93986410-9e35ea80-fd86-11ea-8ed5-6426002ee719.jpg)

Obviously, I failed in doing so. But, I can remove the yellow warning box and rewrite the sentence.

**Comment by T-F-S** [comment]
`skin=beamer,beamer` is not wrong, but makes no sense. I found one example and correczed it.

**Comment by FrankMittelbach** [comment]
> ![beamer](https://user-images.githubusercontent.com/7982989/93986410-9e35ea80-fd86-11ea-8ed5-6426002ee719.jpg)
> 
> Obviously, I failed in doing so. But, I can remove the yellow warning box and rewrite the sentence.

Take it as me being dense. For some reason I didn't equate "It also" with "In addition it".

**Comment by T-F-S** [comment]
I agree that the current text can be misinterpreted. Therefore, changing it makes sense.

**Comment by T-F-S** [comment]
Documentation adapted for version 4.40 (2020/09/25).
