### ISSUE TITLE
should "empty" set coltitle to black?

### ISSUE THREAD

**Issue by FrankMittelbach** [T-F-S/tcolorbox#118]
If one uses the `empty` key then titles are set white on white which is easily repaired but why not set the default for `coltitle` to black in that case?

**Comment by muzimuzhi** [comment]
This is caused by the hierarchy, from bottom to top, 
 - initially `coltitle=white`,
 - `frame engine=empty` removes title filling
 - `skin=empty` sets all engines empty
 - `empty/.style={skin=empty}` (a pure abbreviation)

A minimum change would be `empty/.style={skin=empty,coltitle=black}`.

**Comment by T-F-S** [comment]
Changing the style to `empty/.style={skin=empty,coltitle=black}` would influence all documents using `empty`. If it would not have been documented for years that `empty` does not change the color, I would consider this change.
But with it, documents with e.g. `coltitle=red,empty` would change their title color.

**Comment by FrankMittelbach** [comment]
In which case, I guess it would be best to just document that by default you get white on white in the title part so that one should either alter `coltitle` or `colbacktitle` to make it visible.

**Comment by T-F-S** [comment]
The documentation of the next version of `tcolorbox` will contain a warning to users that the title color may become invisible, if not adapted.

**Comment by T-F-S** [comment]
Documentation adapted with version 4.50 (2021/05/21)
