### ISSUE TITLE
vertical space above tcolorbox changed in 2020/09/25

### ISSUE THREAD

**Issue by aminophen** [T-F-S/tcolorbox#121]
Hi,

``` diff
-tcolorbox.sty    2020/09/17 version 4.32 text color boxes
+tcolorbox.sty    2020/09/25 version 4.40 text color boxes
```

the vertical space above `tcolorbox` has changed between two version.

### 2020/09/17 version 4.32

* [main0.pdf](https://github.com/T-F-S/tcolorbox/files/5322626/main0.pdf)

![image](https://user-images.githubusercontent.com/9957466/95006107-6f97f980-063b-11eb-943b-ba5775520b46.png)

### 2020/09/25 version 4.40: slightly wider

* [main1.pdf](https://github.com/T-F-S/tcolorbox/files/5322627/main1.pdf)

![image](https://user-images.githubusercontent.com/9957466/95006114-7a528e80-063b-11eb-9f94-6d4d83606e28.png)

Is this change intended?  My documentation has got additional pages due to wider space, so I'd like to ask this.  Thank you in advance -- hironobu

**Comment by aminophen** [comment]
Sorry, I forgot to paste the MWE for above: here it is

``` tex
\listfiles
\documentclass{article}
\usepackage{tcolorbox}
\begin{document}

Hello,%
\begin{tcolorbox}
  \LaTeX
\end{tcolorbox}%
world!

\end{document}
```

**Comment by muzimuzhi** [comment]
> Is this change intended? 

Yes, this is the result of resolving #115.

> My documentation has got additional pages due to wider space, so I'd like to ask this.

It seems you can use `\tcbset{autoparskip}` to restore the behavior.

**Comment by aminophen** [comment]
> Yes, this is the result of resolving #115.

Thanks for the answer, understood.

> It seems you can use `\tcbset{autoparskip}` to restore the behavior.

Works fine, thanks!

**Comment by T-F-S** [comment]
Just for clarification from the CHANGES document:

```
- (#115) New default vertical space options
        'before skip balanced', 'after skip balanced', 'beforeafter skip balanced'
  NOTE: These options replace the current default options
        'parskip', 'noparskip', 'autoparskip'
  WARNING: Old documents may need adapted manual page breaks where used.
           Otherwise: Use \tcbsetforeverylayer{autoparskip}
           to restore the old behavior!
```

If you do not have boxes in boxes, `\tcbset{autoparskip}` is enough, otherwise I would use `\tcbsetforeverylayer{autoparskip}`.

**Comment by dbitouze** [comment]
@T-F-S Suppose:
- I put `\tcbsetforeverylayer{autoparskip}` in a package of mine in order to not break compatibility,
- a user of this package of mine doesn't like the old default setting and wants the new one.

What should this user use as a counter-order to `\tcbsetforeverylayer{autoparskip}`?

**Comment by T-F-S** [comment]
The counter-order would be `\tcbsetforeverylayer{beforeafter skip balanced=0.5\baselineskip plus 2pt}`.
