### ISSUE TITLE
v4.32: Extra top space if tcolorbox env starts with a list

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#123]
Changes in [`tcolorbox.sty@v4.32`](https://github.com/T-F-S/tcolorbox/commit/78a915c1b1971a82cd3cce09f6008ccc065ab625), which add support for #110 (breakable boxes and \color), will insert extra vertical space between top of `tcolorbox` contents and box frame, when the contents start with a list environment.

```tex
\documentclass{article}
\usepackage{tcolorbox}
\usepackage{lipsum}

\begin{document}

\begin{tcolorbox}
  \begin{enumerate}
    \item abc
  \end{enumerate}
\end{tcolorbox}

\begin{tcolorbox}[parbox=false]
  \begin{enumerate}
    \item abc
  \end{enumerate}
\end{tcolorbox}

\end{document}
```

* v4.31
   ![image](https://user-images.githubusercontent.com/6376638/95055064-566b7780-0725-11eb-95cf-61c9538656e7.png)
* v4.32
   ![image](https://user-images.githubusercontent.com/6376638/95055097-62efd000-0725-11eb-8fc2-bdae455ba51c.png)

**Comment by T-F-S** [comment]
Unfortunately, I was right that changes in color management have a high risk of producing side effects.
Since https://github.com/T-F-S/tcolorbox/issues/110 with tcolorbox version `4.32`, color is inserted directly into the saved boxes to allow breaking with color stacks.
This also inserts a whatsit (I think) which produces the additional space in combination with lists.

```latex
\documentclass{article}
\usepackage[skins]{tcolorbox}
\usepackage{lipsum}

\begin{document}

\fbox{\begin{minipage}{10cm}\color{red}%
  \begin{enumerate}
    \item abc
  \end{enumerate}
\end{minipage}}

\fbox{\begin{minipage}{10cm}
  \begin{enumerate}
    \item abc
  \end{enumerate}
\end{minipage}}


\begin{tcolorbox}[colupper=red]
  \begin{enumerate}
    \item abc
  \end{enumerate}
\end{tcolorbox}

\begin{tcolorbox}[parbox=false,colupper=red]
  \begin{enumerate}
    \item abc
  \end{enumerate}
\end{tcolorbox}

\end{document}
```

![abstand](https://user-images.githubusercontent.com/7982989/95091378-ad258100-0726-11eb-9732-bf2bedd8076a.png)

For color stack support, the color *has* to be inserted. Insertion with some `\everypar` trick is error-prone, if the text starts by opening a group. Also, this does not work for lists.

Besided inserted color directly (like in the minipage example above) or using `\everypar` I have no other clue for a solution. I am open to suggestions.
The only other way would be to remove color stacks and revert the implementation back to 4.31

**Comment by T-F-S** [comment]
I have an idea now using `\pdfcolSetCurrentColor` and some mixture of pre-4.32-code with 4.41-code.
Currently, I am quite busy and it will take some time (days) until I can test this idea.

**Comment by T-F-S** [comment]
Unfortunately, `\pdfcolSetCurrentColor` also inserts a whatsit (or whatever):

A short failing example is:

```latex
\fbox{\begin{minipage}{10cm}\pdfcolSetCurrentColor%
  \begin{enumerate}
    \item abc
  \end{enumerate}
\end{minipage}}
```

I made a lot of tests, but nothing works. What is needed is some method to set the private color stack to some color without influencing the vertical list. If the makes a difference: the color has not actually to be set, just to be saved to the color stack.
I found no way to do this.

**Comment by T-F-S** [comment]
There should be no extra top space any more with version 4.42 (2020-10-09), if NO color stack is used.

If a color stack is used, this extra top space cannot be avoided; see https://tex.stackexchange.com/questions/565801/color-stack-switch-with-current-color-interferes-with-vertical-list

In this special case, `\parsep` has to be corrected manually (see below) or you do not use a color stack.
There is nothing, I can do about it.

```latex
\documentclass{article}
\usepackage[breakable]{\tcbpkgprefix tcolorbox}
\usepackage{lipsum}

\begin{document}

\begin{tcolorbox}[colupper=red]
  \begin{enumerate}
    \item abc
  \end{enumerate}
\end{tcolorbox}

\begin{tcolorbox}[colupper=red,breakable]
  \begin{enumerate}
    \item abc
  \end{enumerate}
\end{tcolorbox}

\begin{tcolorbox}[colupper=red,breakable,use color stack]
  \vspace{-\parsep}
  \begin{enumerate}
    \item abc
  \end{enumerate}
\end{tcolorbox}

\begin{tcolorbox}[colupper=red,breakable,use color stack,before upper=\vspace{-\parsep}]
  \begin{enumerate}
    \item abc
  \end{enumerate}
\end{tcolorbox}

\end{document}
```

**Comment by muzimuzhi** [comment]
Many thanks. Color support by using whatsit is truly restricted.

**Comment by mbertucci47** [comment]
This fix was working as late as texlive 2021 but by 2022 the extra space is back.
```tex
\documentclass{article}
\usepackage{tcolorbox}

\begin{document}

\begin{tcolorbox}
  \begin{enumerate}
    \item abc
  \end{enumerate}
\end{tcolorbox}

\begin{tcolorbox}[parbox=false]
  \begin{enumerate}
    \item abc
  \end{enumerate}
\end{tcolorbox}

\end{document}
```
![tex-1](https://github.com/T-F-S/tcolorbox/assets/61854785/5be479f9-4dfb-4bf9-80c7-24e3af36902b)

**Comment by muzimuzhi** [comment]
@mbertucci47 I opened #262.
