### ISSUE TITLE
Remove or calculate vertical space introduced by a tcolorbox

### ISSUE THREAD

**Issue by MLNW** [T-F-S/tcolorbox#130]
Hey, I am trying to either straight-up remove or calculate the vertical space introduced by a `tcolorbox` in order to align two that are next to each other. Is there a way to accomplish this?

Here is an example of what I would like to fix:

![image](https://user-images.githubusercontent.com/20930814/106728675-fc17f000-660c-11eb-8af5-cbf6deb62c3b.png)

The `Meeting Context` box on the left should be aligned with the `Date` box on the right.

I create the boxes with this environment:

```latex
\NewTColorBox[]{term}{ m }
{
    width=.325\textwidth,
    bookmark*={rellevel=1}{#1},
}

\NewDocumentEnvironment{titlednote}{ om }
{
    \IfNoValueF{#1}{
        \begin{term}{#1}
            #1
        \end{term}
    }
    \begin{tcolorbox}[
            enhanced,
            breakable,
            title=#2,
            bookmark*={rellevel=2}{#2},
            enlarge left by=.34\textwidth,
            width=.66\textwidth,
            parbox=false,% restore main text formatting behavior
        ]
}
{
    \end{tcolorbox}
}
```

I asked a similar question on [tex.stackexchange.com](https://tex.stackexchange.com/questions/581459/set-tcolorbox-overlay-bookmark-to-be-above-its-parent).

**Comment by T-F-S** [comment]
IMHO, that is an application question and no *issue*. Therefore, asking at stackexchange was the right thing to do.

I added a comment there which may help to solve your problem.
