### ISSUE TITLE
Missing example for fading style definitions in vignete library

### ISSUE THREAD

**Issue by nignasi** [T-F-S/tcolorbox#133]
When I tried to answer this question in TX.SX https://tex.stackexchange.com/q/580379/1952 I proposed a solution with `vignete` library. Today I wanted to particularise on fading styles for every side. And although it's possible to do it with `north|south|west|east fading` styles. There is no example (I couldn't find it) about how to do it in tcolorbox documentation. I had to open the library file and find the particular combination of `{color, path fading=...}`. I think a little example could be added to avoid investigations in code files.

**Comment by T-F-S** [comment]
Yes, I think that would be helpful. I intend to add such an example for the next version.

**Comment by T-F-S** [comment]
Documentation adapted with version 4.50 (2021/05/21)
