### ISSUE TITLE
write register allocations

### ISSUE THREAD

**Issue by u-fischer** [T-F-S/tcolorbox#134]
Simply loading tcolorbox allocates two write registers:

~~~~
\tcb@out=\write4
\tcb@record@out=\write5
~~~~

Both are not needed for typical tcolorbox uses. As write registers are a rather scarce resource with pdflatex and xelatex I would suggest to allocate them only if really needed at the first use of verbatimout/recording.

**Comment by T-F-S** [comment]
Yes, I will do that for the next version.

**Comment by T-F-S** [comment]
Implemented with version 4.50 (2021/05/21)
