### ISSUE TITLE
auto counter, number within, hyperref

### ISSUE THREAD

**Issue by rbeezer** [T-F-S/tcolorbox#135]
The minimal example below causes `pdflatex` to issue warnings about "duplicate" identifiers.  The actual links seem to be fine (i.e. functional).

Is this a bug?

Moving the `\usepackage{hyperref}` before the construction of the  `tcolorbox`  stops the warnings.  Of course, the folk wisdom is that `hyperref` should be last.  I didn't find anything about this in the documentation, but could have missed it.

This post got me going in the right direction to fix this for PreTeXt:

https://tex.stackexchange.com/questions/485251/tcolorbox-potential-bug-with-duplicate-label-for-hyperref-link

Thanks!

```tex
\documentclass{book}
\usepackage{tcolorbox}

\newtcolorbox[auto counter, number within=section]{block}{}
\newtcolorbox[use counter from=block]{remark}[2]{title={{Remark~\thetcbcounter\space#1}}, phantomlabel={#2}, }
\newtcolorbox[use counter from=block]{example}[2]{title={{Example~\thetcbcounter\space#1}}, phantomlabel={#2}, }

\usepackage{hyperref}

\begin{document}

\chapter{Chapter One}
  \section{Section One}
    \begin{example}{Title One}{Label1}
    Foo. \hyperref[Label2]{To Two}
    \end{example}
  \newpage
  \section{Section Two}
    \begin{remark}{Title Two}{Label2}
    Bar. \hyperref[Label1]{To One}
    \end{remark}
\end{document}
```

**Comment by muzimuzhi** [comment]
> Of course, the folk wisdom is that `hyperref` should be last.

Here the "last" means the last package to be loaded, not necessarily the last line of preamble.

**Comment by T-F-S** [comment]
I see it similar to @muzimuzhi  for the preamble:
1) load all packages needed
2) load `hyperref` as last package (with exceptions)
3) add your own stuff, especially `\newtcolorbox` commands which do *counterish* things

```latex
\documentclass{book}
\usepackage{tcolorbox}
\usepackage{hyperref}

\newtcolorbox[auto counter, number within=section]{block}{}
\newtcolorbox[use counter from=block]{remark}[2]{title={{Remark~\thetcbcounter\space#1}}, phantomlabel={#2}, }
\newtcolorbox[use counter from=block]{example}[2]{title={{Example~\thetcbcounter\space#1}}, phantomlabel={#2}, }

%\usepackage{hyperref}

\begin{document}

\chapter{Chapter One}
  \section{Section One}
    \begin{example}{Title One}{Label1}
    Foo. \hyperref[Label2]{To Two}
    \end{example}
  \newpage
  \section{Section Two}
    \begin{remark}{Title Two}{Label2}
    Bar. \hyperref[Label1]{To One}
    \end{remark}
\end{document}
```

I will add a hint at the begin of the **Initialization Option Keys** section to advise using these options after loading `hyperref`.

**Comment by rbeezer** [comment]
Sounds good.  Thanks both, for the clarifications.  I've got the re-arrangement in place for PreTeXt, but could probably do a better job generally of not loading packages so close to their employment.

**Comment by T-F-S** [comment]
Documentation adapted with version 4.50 (2021/05/21)
