### ISSUE TITLE
How to change the placement of the footnotes inside `tcolorbox`?

### ISSUE THREAD

**Issue by farshadrasuli** [T-F-S/tcolorbox#140]
When I use `\footnote` inside `tcolorbox`, the footnote marks on footnotes inside the box are not raised from the text and placed inside of the box because LaTeX handles footnotes in `minipages` differently from footnotes in the main text. How can I improve my `tcolorbox` to raise the footnote marks inside the box from the text and place them to the bottom of each page (even if I used the breakable option)?

```latex
\documentclass[10pt,a4paper]{article}

\usepackage{tcolorbox}

\begin{document}

This is a sample text\footnote{sample footnote number 1} with a footnote\@.

\begin{tcolorbox}
Text inside the box with a footnote\footnote{sample footnote number 2}\@.
\end{tcolorbox}

This is a another sample text\footnote{sample footnote number 3} with a footnote\@.

\begin{tcolorbox}
Another text inside the box with a footnote\footnote{sample footnote number 4}\@.
\end{tcolorbox}

\end{document}
```

[mini.pdf](https://github.com/T-F-S/tcolorbox/files/6602565/mini.pdf)

**Comment by muzimuzhi** [comment]
Try [my answer](https://tex.stackexchange.com/a/558922) to question "Tcolorbox - footnotes at end of each page" on TeX-SX.
