### ISSUE TITLE
Custom spacing between posterboxes

### ISSUE THREAD

**Issue by nichtkorebeds** [T-F-S/tcolorbox#142]
I would like to structure a poster such that the spacing between the title box on the top and the other boxes is larger than normal. So far I have achieved it by using `yshift`. However, when I have a column with only one box (such as the middle column in the sketch below) the bottom alignment of this box is messed up: `above=bottom` or `between=title and bottom` do not work anymore.
Is there a clean way of setting this additional spacing in the poster options?

![boxes](https://user-images.githubusercontent.com/80164540/123970318-500ae300-d9b9-11eb-95a7-1d233387ca5a.png)

**Comment by T-F-S** [comment]
It would be helpful to provide an MWE for such questions.

Nevertheless, every poster box is a `tcolorbox` and can be adapted with `tcolorbox` options. Here, I would insert additional space by fiddling with the bounding box for the title box. In the folloing example I used

`enlarge bottom finally by=5mm`

to increase the vertical space by additional 5mm.

```latex
\documentclass[a4paper]{article}
\usepackage[poster]{tcolorbox}
\thispagestyle{empty}

\begin{document}
\begin{tcbposter}[
poster = {spacing=3mm, columns=3, rows=6},
coverage = {spread},
boxes =  {beamer,colframe=blue!50!black,colback=blue!50,colupper=yellow!50},
]

\posterbox[colframe=red!50!black, colback=red!50, enlarge bottom finally by=5mm]
  {name=title,column=1,row=1,span=3}{}

\posterbox{name=A,column=1,below=title,rowspan=2}{}
\posterbox{name=B,column=1,below=A,rowspan=1.2}{}
\posterbox{name=C,column=1,between=B and bottom}{}

\posterbox{name=D,column=2,between=title and bottom}{}

\posterbox{name=E,column=3,below=title,rowspan=2.2}{}
\posterbox{name=G,column=3,between=E and bottom}{}

\end{tcbposter}

\end{document}
```

![test_361_output](https://user-images.githubusercontent.com/7982989/123976500-7aab6a80-d9be-11eb-86bd-ad660e5387fc.png)

**Comment by nichtkorebeds** [comment]
It works, thank you very much! I didn't know about `enlarge bottom finally by=5mm`, it is actually what I was looking for.
