### ISSUE TITLE
bib: link for book `sturm:latex` seems dead

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#145]
In
https://github.com/T-F-S/tcolorbox/blob/e25e8f51ff49417ff96d0435f7bbd9483f321dfe/doc/latex/tcolorbox/tcolorbox.doc.bib#L50-L60

the link https://www.luis.uni-hannover.de/buch.html?&titel=latex returns error 404.

**Comment by T-F-S** [comment]
Thank you for reporting this. I did not know that the link has changed.

The new link is https://www.luis.uni-hannover.de/de/services/schulung-beratung-und-support/handbuecher/it-handbuecher-und-ebooks/details/manuals/latex/

**Comment by T-F-S** [comment]
Updated for `5.0.0 (2021-12-16)`.

**Comment by muzimuzhi** [comment]
Just for the info, resolved in https://github.com/T-F-S/tcolorbox/commit/b0e2c27bcdbc3fa3eb830200aa55c81e9ce7bc5b#diff-2693e7bee3b4af7a56013796ec7def80f1dc80d6a0b24d4213ba3ec2fca701ad .
