### ISSUE TITLE
How to get specific geometric properties of a tcolorbox?

### ISSUE THREAD

**Issue by claell** [T-F-S/tcolorbox#146]
This is basically a duplicate of https://tex.stackexchange.com/questions/605786/how-to-get-specific-geometric-properties-of-a-tcolorbox. Hopefully I can get useful feedback through this direct channel.

I am currently styling a `tcolorbox`. For that, I plan to use a boxed title that should be shifted. For that, ideally relative lengths can be used to remain versatile.

The documentation mentions `\tcboxedtitleheight` that is ideal for shifting in y direction. However, there does not seem to be good accessible properties for the width (there is `\tcbtextwidth` which I currently use as a workaround).

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[most]{tcolorbox}

% Define base style
\tcbset{stdbox/.style 2 args={
    enhanced,
    % A bit of indent to further distinguish from normal text
    left skip=\textwidth/20,
    colback=#1!10!white,
    colframe=#1!50!black,
    colbacktitle=#1!50!black,
    title=#2,
    % Bold title
    fonttitle=\bfseries,
    boxed title style={size=small},
    % yshift* combines yshift and yshifttext
    attach boxed title to top left={xshift=\tcbtextwidth/20,yshift*=-\tcboxedtitleheight/2}
  }
}
% Define boxes based on the base style
\newtcolorbox{examplebox}[1]{stdbox={blue}{#1}}

\begin{document}
\begin{examplebox}{Test}
    Test
\end{examplebox}
\end{document}
```

Ideally, one could also access the other writable properties like `/tcb/width` etc.

Maybe this is already possible. I am not that experienced in LaTeX. To me it looks as if those properties are write only and their value cannot be used currently.

**Comment by muzimuzhi** [comment]
I think the box width is (finally) stored in `\tcb@width`.
https://github.com/T-F-S/tcolorbox/blob/e25e8f51ff49417ff96d0435f7bbd9483f321dfe/tex/latex/tcolorbox/tcolorbox.sty#L199
https://github.com/T-F-S/tcolorbox/blob/e25e8f51ff49417ff96d0435f7bbd9483f321dfe/tex/latex/tcolorbox/tcolorbox.sty#L949

**Comment by claell** [comment]
Nice, I'll have a look! Ideally, this can be added to the documentation.

One more idea I had is to position the title box in a way that the text of the title lines up (vertically) with the text inside the text box (not sure whether this looks good, but to at least use the text margins to specify the box position). I'll have a look whether the needed values can also be accessed like the width.

The given options to position the title box (`xshift` and `yshift`) are sufficient for me, so I guess I won't use the `underlays` option for now.

**Comment by claell** [comment]
Hm, accessing the width with `\tcb@width` doesn't work for me.

**Comment by muzimuzhi** [comment]
`\tcb@width` has `@` in its name, so need be surrounded in `\makeatletter ... \makeatother`. See https://tex.stackexchange.com/questions/8351/what-do-makeatletter-and-makeatother-do.

```tex
\documentclass{article}
%\usepackage[utf8]{inputenc}
\usepackage[most]{tcolorbox}
\usetikzlibrary{calc}

% Define base style
\makeatletter
\tcbset{stdbox/.style 2 args={
    enhanced,
    % A bit of indent to further distinguish from normal text
    left skip=\textwidth/20,
    colback=#1!10!white,
    colframe=#1!50!black,
    colbacktitle=#1!50!black,
    title=#2,
    % Bold title
    fonttitle=\bfseries,
    boxed title style={size=small},
    % yshift* combines yshift and yshifttext
    attach boxed title to top left={xshift=\tcb@width/20,yshift*=-\tcboxedtitleheight/2},
    %%% just for assertion
    geometry nodes,
    overlay={\draw[orange, thick] ($(frame.north west)!.05!(frame.north east)$) -- ($(frame.south west)!.05!(frame.south east)$);}
  }
}
\makeatother

% Define boxes based on the base style
\newtcolorbox{examplebox}[1]{stdbox={blue}{#1}}

\begin{document}
\begin{examplebox}{Test}
    Test
\end{examplebox}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/127040638-f46ec105-0d90-4c27-bea3-1452f9aee949.png)

**Comment by claell** [comment]
Thanks, probably should have read the error messages of the compilation.

**Comment by claell** [comment]
`\tcb@leftupper` etc. don't seem to work, though.

**Comment by muzimuzhi** [comment]
What do you expect to get from `\tcb@leftupper`, a dimension or a coordinate? It seems you want something like a tikz node anchor, like `frame.north west`. Perhaps better explained with an example.

**Comment by claell** [comment]
I expect a dimension (lenth) to use with `xshift`.

**Comment by muzimuzhi** [comment]
Which dimension, something like `/tcb/boxsep + /tcb/left`?

**Comment by muzimuzhi** [comment]
> I guess the gap is not only the missing user friendly "interface", but also how to automatically adjust the bounding box.

Call for a more powerful and configurable key `/tcb/attach boxed title to xxx`. The key point is how to (auto) extend the bounding box, which is currently done in 
https://github.com/T-F-S/tcolorbox/blob/e25e8f51ff49417ff96d0435f7bbd9483f321dfe/tex/latex/tcolorbox/tcbskins.code.tex#L1115-L1126
and called by
https://github.com/T-F-S/tcolorbox/blob/e25e8f51ff49417ff96d0435f7bbd9483f321dfe/tex/latex/tcolorbox/tcbskins.code.tex#L1142

**Comment by claell** [comment]
The same dimension as is documented for `/tcb/left`. In practice, I might have to combine some dimensions (and subtract some) to get the dimension I want (currently I don't know exactly which output I want).

What would probably be nice as a result is to have both the text in the title box and the text in the normal box vertically aligned.

For that I planned to add up all dimensions that contribute to the normal box text left margin, then subtract all dimensions that contribute to the title box text left margin and use the result for `xshift`.

**Comment by muzimuzhi** [comment]
To fetch both the geometric settings for the whole tcolorbox, and the settings for the boxed title (through `boxed title size` and `boxed title style`), some tricks are used.

```tex
\documentclass{article}
\usepackage[skins]{tcolorbox}
\usetikzlibrary{calc}

% Define base style
\makeatletter
\tcbset{stdbox/.style 2 args={
    enhanced,
    % A bit of indent to further distinguish from normal text
    left skip=\textwidth/20,
    colback=#1!10!white,
    colframe=#1!50!black,
    colbacktitle=#1!50!black,
    title=#2,
    % Bold title
    fonttitle=\bfseries,
    boxed title style={size=small},
    % yshift* combines yshift and yshifttext
    attach boxed title to top left={%
      /tcb/code={%
        \begingroup
          \pgfkeysalso{/tcb/.cd}%
          \pgfkeysalsofrom\tcb@trans@boxedsize
          \pgfkeysalsofrom\tcb@trans@boxedstyle
          \xdef\mytcb@title@left@sep{\dimexpr\mytcb@calc@left@sep}%
        \endgroup
      },
      xshift=\mytcb@calc@left@sep-\mytcb@title@left@sep,
      yshift*=-\tcboxedtitleheight/2
    },
    %%% just for assertion
    overlay={\draw[orange, thick] ($(frame.north west)!.05!(frame.north east)$) -- ($(frame.south west)!.05!(frame.south east)$);}
  }
}

% tcolorbox internals used
\def\mytcb@calc@left@sep{%
  \kvtcb@left@rule+\kvtcb@boxsep+\kvtcb@lefttitle
}
\makeatother

% Define boxes based on the base style
\newtcolorbox{examplebox}[1]{stdbox={blue}{#1}}

\begin{document}
\begin{examplebox}{Test}
  Test
\end{examplebox}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/127232594-baa53a14-a853-4052-b79b-b12fd8ec49fe.png)

To avoid using internals directly (in `\mytcb@calc@left@sep`), as far as the corresponding `/tcb` keys are all defined by key handler `/.store in`, one could patch `pgfkeys`.
```tex
\usepackage{pgfkeys}

% \pgfkeysValueOfStoredIn{<full path>} accepts the path of a key defined by
% handler /.store=\cmd, and expands to \cms.
\makeatletter
\pgfkeys{/handlers/.store in/.code=
  \pgfkeysalso{\pgfkeyscurrentpath/.code=\def#1{##1}}%
  % added
  \def\pgfkeys@temp{#1}%
  \pgfkeyslet{\pgfkeyscurrentpath/.@stored}{\pgfkeys@temp}%
}

\def\pgfkeysValueOfStoredIn#1{\csname pgfk@#1/.@stored\endcsname}

% \usepackage[most]{tcolorbox}
% the rest preamble

\def\mytcb@calc@left@sep{%
  \dimexpr
  \pgfkeysValueOfStoredIn{/tcb/leftrule}+
  \pgfkeysValueOfStoredIn{/tcb/boxsep}+
  \pgfkeysValueOfStoredIn{/tcb/lefttitle}%
}
\makeatother
```

**Comment by T-F-S** [comment]
IMHO, since a box with a specific design is created with a special aligned title box, all dimensions are known and can be set specifically - I see no need to extract data from keys which are set within the same style `stdbox` where also the title is set.

If the left space should be configurable, I suggest to use a private key like `myleft` which sets all needed options appropriately.

**Comment by claell** [comment]
@muzimuzhi Thanks! I'll have a closer look later.

@T-F-S This is only true if the values are set explicitly, right? Currently, I don't do that, so I assume some default values are used (which I don't know and which also might change at some point in the future).

**Comment by claell** [comment]
@muzimuzhi Thanks for the code. It works fine for me and I guess I'll use it for now. Hopefully some less "tricky" way can be established for the future, though.

**Comment by T-F-S** [comment]
Version `5.0.0 (2021-12-16)` contains new options to align the boxed title:

### Added
- Library `skins`: Option `attach boxed title to top text left`
- Library `skins`: Option `attach boxed title to top text right`
- Library `skins`: Option `attach boxed title to bottom text left`
- Library `skins`: Option `attach boxed title to bottom text right`

**Comment by muzimuzhi** [comment]
Many thanks to the newly added options.

**Comment by claell** [comment]
@T-F-S Thanks for that! Since my question here has been answered and now there are also nice options for this available by default, I'll close this issue.
