### ISSUE TITLE
Usage of `\autoref`

### ISSUE THREAD

**Issue by claell** [T-F-S/tcolorbox#147]
Ideally, I want to be able to reference my boxes with name and number. So that for a box (theorem) with the title "Definition 1: Test" the reference would be "Definition 1".

The documentation does not seem to list such an example. When I use `\autoref` (which does this for other references), I get the message `No autoref name for 'tcb@cnt@exampletheorem'.` and only the number is used for reference (in this case "1").

Is it possible to achieve what I want currently (or if not - can this functionality be added)?

**Comment by muzimuzhi** [comment]
How is the box configured? If you know the name of the underlying counter, for example `theorem`, then add `\newcommand*\theoremautorefname{Theorem}`. See the doc for `\autoref` in `hyperref` manual v7.00m, sec. 4 "Additional user macros".

**Comment by claell** [comment]
This is the code.

```
\makeatletter
\tcbset{stdbox/.style={
    enhanced,
    % A bit of indent to further distinguish from normal text
    left skip=\textwidth/20,
    colback=#1!10!white,
    colframe=#1!50!black,
    colbacktitle=#1!50!black,
    % Bold title
    fonttitle=\bfseries,
    boxed title style={size=small},
    % yshift* combines yshift and yshifttext
    attach boxed title to top left={xshift=\tcb@width/40,yshift*=-\tcboxedtitleheight/3}
  }
}
\makeatother
% Define boxes based on the base style
% Use theorem because of more provided functionality out of the box
\newtcbtheorem{exampletheorem}{Example}{stdbox={blue}}{ex}
```

I tried to play around a bit with the example you gave, but did not come up with a version that worked for me.

(Ideally in the future `tcolorbox` could provide a name for `autoref` automatically)

**Comment by muzimuzhi** [comment]
In your case, the used counter is named `tcb@cnt@exampletheorem`, as you can see from the log
```
Package hyperref Warning: No autoref name for `tcb@cnt@exampletheorem' on input
 line 36.
```
So what you need is
```tex
\makeatletter
\providecommand*{\tcb@cnt@exampletheoremautorefname}{Example}
\makeatletter
```
------

A first attempt on supporting `\autoref`:
```tex
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{skins, theorems}

\usepackage{hyperref}
\usepackage{xpatch}

\makeatletter
% new option "autoref name=<name>"
% BEGIN
\tcbset{
  new/autoref name/.store in=\kvtcb@autorefname
}

\def\tcb@proc@counter@auto#1{%
  \newcounter{tcb@cnt@#1}%
  % BEGIN
  \@ifpackageloaded{hyperref}{%
    \expandafter\providecommand\expandafter*\csname tcb@cnt@#1autorefname\expandafter\endcsname
      \expandafter{\kvtcb@autorefname}%
  }{}%
  % END
  \csxdef{tcb@cnt@#1}{tcb@cnt@#1}%
  \tcb@proc@counter@autoanduse{#1}%
}

% patch for theorems lib
\xpatchcmd\new@tcbtheorem
  {auto counter}
  {auto counter,autoref name=#3}
  {}{\fail}
% END


\tcbset{stdbox/.style={
    enhanced,
    % A bit of indent to further distinguish from normal text
    left skip=\textwidth/20,
    colback=#1!10!white,
    colframe=#1!50!black,
    colbacktitle=#1!50!black,
    % Bold title
    fonttitle=\bfseries,
    boxed title style={size=small},
    % yshift* combines yshift and yshifttext
    attach boxed title to top left={xshift=\tcb@width/40,yshift*=-\tcboxedtitleheight/3}
  }
}
\makeatother

% Define boxes based on the base style
% Use theorem because of more provided functionality out of the box
\newtcbtheorem{exampletheorem}{Example}{stdbox={blue}}{ex}

% test non-theorem tcolorbox
\newtcolorbox[auto counter, autoref name=Box]{mybox}[2][]{title=Box~\thetcbcounter\space (#2), #1}

\begin{document}
\begin{exampletheorem}{Title}{marker}
  content \texttt{\tcbcounter}
\end{exampletheorem}

\ref{ex:marker}, \autoref{ex:marker}

\begin{mybox}[label=box:test]{test}
  contents
\end{mybox}

\ref{box:test}, \autoref{box:test}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/127364024-24e21a03-6995-43d2-9db0-d90b7a638173.png)


PS: In mosts cases, a complete example is always welcome, and even expected.

**Comment by muzimuzhi** [comment]
> In your case, the used counter is named `tcb@cnt@exampletheorem`, as you can see from the log
> 
> ```
> Package hyperref Warning: No autoref name for `tcb@cnt@exampletheorem' on input
>  line 36.
> ```
> 
> So what you need is
> 
> ```
> \makeatletter
> \providecommand*{\tcb@cnt@exampletheoremautorefname}{Example}
> \makeatletter
> ```

Also see https://tex.stackexchange.com/questions/179948/using-autoref-with-tcolorbox

**Comment by T-F-S** [comment]
`tcolorbox` provides various options for numbering a box, see Section 5.1 Numbered Boxes of the documentation.

If the counter name is needed, here for `\autoref`, I suggest to use an own counter which can be given an autorefname as described in the `hyperref` manual. Also,  a common problem is discussed there, if e.g. lemmas and definitions should share a counter. The solution provided makes use of the `aliascnt` package. I foresee a bunch of problems and incompatibilities, if `tcolorbox` would try to automate all these things (plus new packages in the future). On the other hand, it is really very easy to achieve the desired goal following the manuals, when an own counter is used:

```latex
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{skins, theorems}

\usepackage{hyperref}

\tcbset{stdbox/.style={
    enhanced,
    % A bit of indent to further distinguish from normal text
    left skip=\textwidth/20,
    colback=#1!10!white,
    colframe=#1!50!black,
    colbacktitle=#1!50!black,
    % Bold title
    fonttitle=\bfseries,
    boxed title style={size=small},
    % yshift* combines yshift and yshifttext
    attach boxed title to top left={xshift=3.2mm,yshift*=-\tcboxedtitleheight/3}
  }
}

% Define boxes based on the base style
% Use theorem because of more provided functionality out of the box
\newcounter{myexample}
\providecommand*\myexampleautorefname{Example}
\newtcbtheorem[use counter=myexample]{exampletheorem}{Example}{stdbox={blue}}{ex}

% test non-theorem tcolorbox
\newcounter{mybox}
\providecommand*\myboxautorefname{Box}
\newtcolorbox[use counter=mybox]{mybox}[2][]{title=Box~\thetcbcounter\space (#2), #1}

\begin{document}
\begin{exampletheorem}{Title}{marker}
  content \texttt{\tcbcounter}
\end{exampletheorem}

\ref{ex:marker}, \autoref{ex:marker}

\begin{mybox}[label=box:test]{test}
  contents
\end{mybox}

\ref{box:test}, \autoref{box:test}
\end{document}
```

I am very fond of automation, but here I would go for the direct way which gives full control.

Nevertheless, @claell, you can alternatively use the fine patch of @muzimuzhi .

**Comment by claell** [comment]
@T-F-S Mh, I might not know the internals. From my perspective, it would be a good thing to have a name provided by default (which then can be overwritten by power users who want to change it to their needs). The current solutions require more effort even for simple usages. Also, one has to give the name "Example" twice. Once for the custom command for hyperref and once when creating the theorem. This might lead to unwanted inconsistencies. (I know one can use another command and possibly other ways to make sure that both always use the same name, but that is even more additional work required).

For now, I'll use this way, though. So thanks for the help to both of you!

@muzimuzhi Do you mean a MWE with "complete example"? Or is an excerpt of the code like I provided good enough?

**Comment by muzimuzhi** [comment]
Personally I prefer complete examples, so others can run and test them with a simple copy-and-paste.

**Comment by claell** [comment]
@muzimuzhi Alright, I will consider that for the future. This seems to be special for LaTeX (MWE), while programming language topics (for example on Stack Exchange) often only contain single functions etc. in question, at least that is my impression.
