### ISSUE TITLE
title after break and \url bug

### ISSUE THREAD

**Issue by Felipe-Math** [T-F-S/tcolorbox#150]
When there exists a multiline \url link exactly when the box breaks, so the link bugs. The "title after break" became part of the link.
It follows a MWE of the bug:
```
\documentclass{article}
\usepackage[breakable]{tcolorbox}
\usepackage{lipsum, hyperref}
\begin{document}
	\begin{tcolorbox}[breakable, title={This is my title}, title after break={This is my title (continuation)}]
		\lipsum[1-4]

		Text text text text Text text text text Text text text text Text text text text 
                Text text text text Text text text text Text text text text Text text text text
                Text text text text Text text text text Text text text text Text text text text
                Text text text text Text text text text \url{https://www.google.com/textextextextextextext}
                Text text text text Text text text text Text text text text 
	\end{tcolorbox}
\end{document}
```
The code above generates the following result (at least for me):
![Captura de tela de 2021-09-22 17-09-29](https://user-images.githubusercontent.com/67498248/134414645-648259b4-382a-48f9-9beb-abf6efd3f127.png)
The bug just make sense with the library `breakable` and the package `hyperref`.

Moreover, if you add the library `skins`, then 3 litlle link blocks apear.

I'm not sure if it is a bug or if there exists some option that needs to be load.

**Comment by muzimuzhi** [comment]
a known `hyperref` limitation, see https://tex.stackexchange.com/questions/54136/hyperref-link-spans-a-pagebreak-looks-ugly
