### ISSUE TITLE
When I try to use boxes in vertical formatting using upLaTeX and jlreq, the boxes are not formatted correctly.

### ISSUE THREAD

**Issue by huideyeren** [T-F-S/tcolorbox#151]
I use [Re:VIEW](https://github.com/kmuto/review) and upLaTeX to create vertical books using [jlreq](https://github.com/abenori/jlreq), an environment that meets the requirements of Japanese typesetting.

I am using tcolorbox to handle boxes in Re:VIEW, but in the vertical typesetting, the following box is created in a position that is out of the text.

[https://github.com/kmuto/review/issues/1751](https://github.com/kmuto/review/issues/1751) (Written in Japanese)

There is a box package ascmac that supports vertical writing, but it doesn't display correctly when there is a page break.

It would be nice if tcolorbox could also support vertical writing.

**Comment by T-F-S** [comment]
Here, I would need an MWE (Minimal Working Example) to see what kind of formatting problem happens...

**Comment by T-F-S** [comment]
Closed, because this is out of my scope.
