### ISSUE TITLE
Percent sign in tcblisting

### ISSUE THREAD

**Issue by ryuking177** [T-F-S/tcolorbox#152]
I'm using XeLaTeX on Overleaf and I can't successfully display the % in tcblisting.

In the following, I set `verbatim ignore percent=false`.

When I type a percent sign as "`\%`", it is displayed as "`\%`".

![result1](https://user-images.githubusercontent.com/72437594/136672630-ee8c9013-c377-47f2-b388-3014bba9e1d3.png)

If only "`%`" is entered, it will be shown but will be faded and commented out.

![result2](https://user-images.githubusercontent.com/72437594/136672635-332ca093-bfd4-47f1-a05b-09ea7784387d.png)

Here is the MWE:

```
\documentclass[11pt,dvipdfmx,b5paper,oneside]{book}

\usepackage{zxjatype}

\usepackage{tcolorbox}
\tcbuselibrary{listings}
\tcbuselibrary{minted}
\tcbuselibrary{breakable}

\begin{document}

\begin{center}
    \begin{tcblisting}{
        listing engine=minted,
        minted style=trac,
        colback=lightgray!20!white,
        colframe=darkgray,
        listing only,
        verbatim ignore percent=false,
        width=10.5cm,
        arc=0mm}
    1  print(5 % 2) # --> 1
    \end{tcblisting}   
\end{center}

\end{document}
```

There are two possible solutions to this problem I suppose.

1. define a command that can only display `%` in tcblisting (e.g. `\tcbpercent`)
2. make it possible to change the font of commented-out parts in tcblisting.

Please consider this.

If you have a solution to this problem, please let me know.

**Comment by muzimuzhi** [comment]
Add option `minted language=python` (and use `%` instead of `\%`).
