### ISSUE TITLE
lib documentation: Check existence of packages `pifont` and `marvosym`

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#153]
Just to convert my previous comments ([1] and [2]) under https://github.com/T-F-S/tcolorbox/commit/e25e8f51ff49417ff96d0435f7bbd9483f321dfe into a real issue.

[1]: https://github.com/T-F-S/tcolorbox/commit/e25e8f51ff49417ff96d0435f7bbd9483f321dfe#r52158370
[2]: https://github.com/T-F-S/tcolorbox/commit/e25e8f51ff49417ff96d0435f7bbd9483f321dfe#r52158566

**Problem Restatement**

To avoid naming clashes, v4.51 established soft reliances to symbol font packages `pifont` and `marvosym`: packages are not loaded, while the fonts coming up with them are directly used.

Now If a user don't have these packages installed, confusing font error(s) like ``Font shape `U/mvs/m/n' undefined using `U/cmr/m/n' ...`` will be thrown, which is hard to be connected with the actual cause "missing package xxx" (for average users).

```tex
% Assume `marvosym` is not installed.
\documentclass{article}
\begin{document}
% Mimic \tcb@doc@mvchr{39}, which mimics \Righttorque from `marvosym.sty`
{\fontfamily{mvs}\fontencoding{U}\fontseries{m}\fontshape{n}%
 \selectfont\char39}
\end{document}
```

To keep a minimal reliance, `tcolorbox` could just check the existence of font files `upzd.fd` and `umvs.fd` (`<enc> + <family>.fd`, in lowercase). But checking for `pifont.sty` and `marvosym.sty` is also ok and even preferable since versions before v4.51 directly loads them (through `\RequirePackage`).

**Comment by T-F-S** [comment]
The next version will contain

```latex
\IfFileExists{pifont.sty}{}{\tcb@warning{Library 'documentation' may need symbols from package 'pifont' (not installed)}}
\IfFileExists{marvosym.sty}{}{\tcb@warning{Library 'documentation' may need symbols from package 'marvosym' (not installed)}}
```

So, to avoid warnings, these packages have to be installed, but they are not required to be loaded.

**Comment by T-F-S** [comment]
With version `5.0.0 (2021-12-16)`:

### Changed
- Library `documentation`: warn about not installed `marvosym` and `pifont` (issue #153)
