### ISSUE TITLE
Magic number `yshift=0.1mm` in bicolor skin

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#166]
With `skin=bicolor`, the lower part is filled with a possibly different color. But the top of that filling is `0.1mm` higher than the y-coord of `segmentation` node. Since `0.1mm ~= 0.28pt` is comparable to the default line with `0.4pt`, this shifting is noticeable in certain use cases, for example the one in https://tex.stackexchange.com/q/628634 as noticed by @dbitouze .

The introduce of such magic number dates back to [`v3.0.5`](https://github.com/T-F-S/tcolorbox/commit/8787eb0f236f76efc6039a697116705b063d7c7b#diff-f5f726dc38586afe564f49315a0934608d5790b7ea53ded696631400fdd5919c) and I suspect it is used to prevent the "thin white line" issue when upper and lower parts are filled with the same color (with `skin=bicolor`).

Multiple workarounds/improvements exist:
 - use a smaller length, e.g., `.01mm`
 - make it configurable (ugly)
 - if what I suspect is close to the truth, then the better way, instead of setting a magic number, would be to compute a "distance" between the two filling colors and when they're too close, degenerate to normal skin (fill the colored box in a whole) and raise a warning.

Related code lines
https://github.com/T-F-S/tcolorbox/blob/adb84d65cdbacf3dd3066b166a827470e2a467bf/tex/latex/tcolorbox/tcbskins.code.tex#L219-L227

**Comment by T-F-S** [comment]
Yes, it is connected to **thin white line** issue. As far as I remember

- a smaller length leads to visible lines depending on PDF viewers. In theory, no overlap is needed. In theory, a *very* small overlap is needed, if the first theory does not meet practice. Unfortunately, a considerable overlap is needed (or was needed in my tests a few years ago). *If* 0.1mm is considered considerable, here.

- The white line glitch also appears, if colors are different (as far as I remember) and there is no overlap.

**Comment by muzimuzhi** [comment]
Sorry I forgot to provide a link to "thin white line" [example](https://tex.stackexchange.com/questions/53576/very-thin-white-line-in-colortbl) (also the ones linked to this question on tex-sx). According to feedbacks on tex-sx ([1](https://tex.stackexchange.com/a/53578) and [2](https://tex.stackexchange.com/questions/501147/remove-space-between-table-cell?noredirect=1&lq=1#comment1265734_501147)), it seems `.1pt` is enough.

Imho the specific small shifting amount is not cared about until users add some visual benchmark. In this case, either canceling the shifting (by providing a new option) or making the shifting amount accessible (so user drawings can be around a fake `segmentation` y-coord) would help.

**Comment by dbitouze** [comment]
For what it is worth, here is an example of the need to deal with the magic number `yshift=0.1mm` in bicolor skin. The glitch is visible even with not so large zoom values:

```latex
\documentclass{article}
\usepackage{tcolorbox}

\tcbuselibrary{listings,skins}

\begin{document}
\begin{tcblisting}{%
    sharp corners,
    skin=bicolor,
    top=0.5cm,
    middle=0.5cm,
    overlay={
      \node[minimum width=1cm,minimum height=0.5cm,outer sep=auto,
      anchor=north east,fill=white] at (interior.north east)
      {\itshape\small code};
      \node[minimum width=1cm,minimum height=0.5cm,outer sep=auto,
      anchor=north east,fill=white] at (% [yshift=.1mm]
      segmentation.east)
      {\itshape\small result};
    }
  }
Foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foooo
foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foooo
\end{tcblisting}
\end{document}
```

![image](https://user-images.githubusercontent.com/1032633/148828425-3bfba8a7-8b25-423e-b1ed-31d4c83761f1.png)

**Comment by T-F-S** [comment]
I will add configuration of the *magic number* as new feature:

- Library `skins`: overlap of lower part for `bicolor`, `tile`, and `beamer`
    made configurable (issue #166) by
    + Option `overlaplower`
    + `\tcboverlaplower`

This allows the following:

```latex
\documentclass{article}
\usepackage{tcolorbox}

\tcbuselibrary{listings,skins}

\begin{document}

\begin{tcolorbox}[bicolor, sharp corners,
    colframe=blue!50!black, colback=blue!10, colbacklower=red!10,
    top=5mm, bottom=2mm, middle=3.5mm, overlaplower=1.5mm,
    underlay={
      \node[minimum width=1cm,minimum height=0.5cm,outer sep=auto,
        anchor=north east,fill=white] at (interior.north east)
        {\itshape\small upper};
      \node[minimum width=1cm,minimum height=0.5cm,outer sep=auto,
        anchor=north east,fill=white]
        at ([yshift=\tcboverlaplower]segmentation.east)
        {\itshape\small lower};
    }
  ]
This is the upper part.
\tcblower
And that is the lower part.
\end{tcolorbox}
\end{document}
```
![grafik](https://user-images.githubusercontent.com/7982989/148976677-c6c7e59a-dd1f-49f2-80b1-74411a24e677.png)

**Comment by T-F-S** [comment]
Done with https://github.com/T-F-S/tcolorbox/releases/tag/v5.1.0
