### ISSUE TITLE
attach boxed title to top with left and right rules enlarges title box

### ISSUE THREAD

**Issue by nignasi** [T-F-S/tcolorbox#167]
I wanted to answer this question https://tex.stackexchange.com/a/629689/1952. But when I applied a `leftrule` and `rightrule` to the `boxed title style` for `attach boxed title to top` (which mimmics normal titles), the title box grows to the left and right. This doesn't happen when left and right rules are applied to a tcolorbox. Is this the expected behaviour?

```
\documentclass{article}
\usepackage[most]{tcolorbox}

\begin{document}

\begin{tcolorbox}[title=Title, colbacktitle=white, coltitle=black]
Some text
\end{tcolorbox}

\begin{tcolorbox}[title=Title, colbacktitle=white, coltitle=black, leftrule=2mm, rightrule=2mm]
Some text
\end{tcolorbox}

\begin{tcolorbox}[enhanced, title=Title, colbacktitle=white,coltitle=black, attach boxed title to top,
boxed title style={leftrule=2mm, rightrule=2mm}]
Some text
\end{tcolorbox}

\end{document}
```

**Comment by T-F-S** [comment]
Yes, this is the expected behaviour since `attach boxed title to top` adapts the inner text width of the title box to the main box.

For special rules, `attach boxed title to top center` may be more appropriate (?). Or, use `underlay` or `overlay` (as you did on stackexchange).
