### ISSUE TITLE
Tcolorboxes in itemize: additional vertical spacing in first item

### ISSUE THREAD

**Issue by kiryph** [T-F-S/tcolorbox#17]
I have opened following question on tex.stackexchange.com:

http://tex.stackexchange.com/questions/341467/tcolorboxes-in-itemize-additional-vertical-spacing-in-first-item

Do you know what is responsible for the additional vertical space?

**Comment by T-F-S** [comment]
Answered on tex.stackexchange.com

http://tex.stackexchange.com/questions/341467/tcolorboxes-in-itemize-additional-vertical-spacing-in-first-item/341483#341483
