### ISSUE TITLE
Why `/tcb/before` not used for floating boxes?

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#172]
According to the documentation (currently page 81), `/tcb/before` is not used for floating boxes.

However, this option would be useful with floats in some cases. E.g., in case of floating boxes not on their call out pages, one may want to automatically insert (just before theses boxes call out locations), text such as "See example ⟨n⟩ page ⟨m⟩." (for this, one can rely on `/tcb/label` and tests such as `\int_compare:nNnF {\getpagerefnumber{⟨label⟩}} = {\thepage}{...}`, thanks to `refcount` package).

**Comment by dbitouze** [comment]
> It is not used, because mainly `before` and `after` are used to control the vertical distance of a box to the preceding and following text. These options are not empty be default, but set such that _normally_ the vertical distance looks alright.

I see.

> After headings,

I'm not sure what you mean here.

>  the `before` code is typically removed, also for floating boxes. In both cases the space settings would be disturbing since in these cases there already is space provided.

OK for floating boxes.

> Using `before` to output texts like `see example` is not the intended purpose (even if you can use it like that).

That's what I guessed. And I was desperate to not find any hook that let me insert something  _before_ the boxes.

> In the use case you mentioned, I could image wrapping the `tcolorbox` into an environment which also outputs the intended text before the `tcolorbox`.

I'm not sure it could be an option: the "See example x on page y" text is supposed to appear only if the floating box is located on a page other than its call out page so I have to performed the test (on pages numbers) within (the options of) the `tcolorbox` (BTW a `TCBListing` in my use case).

> Or, if the text is always a one-liner like "See example x on page y", `enlarge top initially by` could be used to reserve space before the box and an `underlay` to print the text.

Is it necessary to "enlarge top initially" since the "See example x on page y" text is supposed to appear only if the floating box is located on a page other than its call out page?

About `underlay`:

- since it is documented as `/tcb/underlay=⟨graphical code⟩`, I couldn't imagine use it for something else than, well, graphical code,
- is it appropriate for inserting something which is supposed to be located on a page other than the page where is located its corresponding `tcolorbox`?

**Comment by muzimuzhi** [comment]
Seems to be an opportunity for a set of new options like `/tcb/before float`, `/tcb/after float`, and their `pre/app` variants. Currently tcolorbox already provides `/tcb/every float=<code>` which will insert `<code>` at the beginning of a floating boxes.

**Comment by T-F-S** [comment]
@dbitouze Maybe, I had not completely understood what you like to achieve. `underlay` can contain a `\node` to position text outside a `tcolorbox` frame, but this is useful for static or near-static text like a one-liner. If it is context dependend, if the text is to be shown or not, this is not a good option since the space reservation is fixed.

@muzimuzhi  Adding `/tcb/before float` and `/tcb/after float` is a reasonable feature request. Alas, changing the very sensible `before`/`after` code has a high danger of influencing the interaction of all tcolorboxes with other text elements. In the past, every tiny change caused many, many hours of debugging. The float part should not be as critical, but I will postpone investigation of such a feature until I have more time.

**Comment by dbitouze** [comment]
> Adding `/tcb/before float` and `/tcb/after float` is a reasonable feature request.

Good news! :smile: 

> Alas, changing the very sensible `before`/`after` code has a high danger of influencing the interaction of all tcolorboxes with other text elements. In the past, every tiny change caused many, many hours of debugging. The float part should not be as critical, but I will postpone investigation of such a feature until I have more time.

Since `before`/`after` code is disabled for floats, new `/tcb/before float` and `/tcb/after float` should not change anything to `before`/`after`, isn't it?

**Comment by T-F-S** [comment]
> > Alas, changing the very sensible `before`/`after` code has a high danger of influencing the interaction of all tcolorboxes with other text elements. In the past, every tiny change caused many, many hours of debugging. The float part should not be as critical, but I will postpone investigation of such a feature until I have more time.
> 
> Since `before`/`after` code is disabled for floats, new `/tcb/before float` and `/tcb/after float` should not change anything to `before`/`after`, isn't it?

That's why I hope a change is not *critical*. I will look into that matter with more time.

**Comment by T-F-S** [comment]
The next version will contain the requested option.

- Options to insert code at begin and end of floats (issue #172)    
    - Option `before float`
    - Option `after float`
    - Option `before float app`
    - Option `before float pre`
    - Option `after float app`
    - Option `after float pre`    

But, these options are restricted to unbreakable floating objects. For breakable floating objects, the space needed for these code parts cannot be computed in advance and therefore the break algorithm cannot be adapted (For non-floating boxes, the situation is different).

**Comment by T-F-S** [comment]
Done with https://github.com/T-F-S/tcolorbox/releases/tag/v5.1.0
