### ISSUE TITLE
Warning in the `.log` about the necessity for the library `documentation` to be loaded after...

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#173]
The documentation warns (currently page 487): 

>The package `makeidx` is loaded only, if `\printindex` is not already defined. Therefore,
one can include an alternative to `makeidx` like `imakeidx` before the library `documentation`
is used.

I'm not sure the trouble I encountered (namely, page numbers in the index not hyperlinked, see MCE below) is related to this, but it took me some time to figure out that loading `imakeidx` before the library `documentation` solved it. 

Hence my feature request: issuing this warning in the `.log` file instead than (only) in the documentation, lost in the middle of 540 pages :smile:

```latex
\documentclass{article}

\usepackage{tcolorbox}
\tcbuselibrary{documentation}

\usepackage{imakeidx}
\makeindex

\usepackage{hyperref}

\begin{document}
foo\index{foo}
\newpage
bar\index{bar}
\newpage
\printindex
\end{document}
```

**Comment by T-F-S** [comment]
I'm quite sure that I put in the check for `\printindex` on request of somebody some years ago. I guess, you were the *somebody*, but I cannot tell exactly... ;-)

So, loading

```latex
\usepackage{imakeidx}
\tcbuselibrary{documentation}
```

prevents loading of `makeidx`, while

```latex
\tcbuselibrary{documentation}
\usepackage{imakeidx}
```

is troublesome.

But, what kind of warning you would expect `tcolorbox` to log?

If you use the first code, no warning is needed. If you use the second code, the `documentation` library does not know that you include `imakeidx` afterwards. If a warning like *I loaded makeidx* is issued, it is **always** issued. I do not think that a LaTeX package should permanentely issue a warning without reason.

**Comment by dbitouze** [comment]
> I'm quite sure that I put in the check for `\printindex` on request of somebody some years ago. I guess, you were the _somebody_, but I cannot tell exactly... ;-)

(As I already told you,) If it was me, please trust me: don't trust this guy! :smile: 

> If you use the second code, the `documentation` library does not know that you include `imakeidx` afterwards.

What about the following added in `tcbdocumentation.code.tex:`

```latex
\AddToHook{begindocument/before}{%
  \@ifpackageloaded{imakeidx}{%
    \tcb@warning{`imakeidx' package should be loaded before `documentation' library}%
  }{%
  }
}
```

Maybe even better thanks to hooks, with something like `\DeclareHookRule{env/document/begin}{imakeidx}{before}{tcolorbox}` (but all my attempts failed).

> I do not think that a LaTeX package should permanently issue a warning without reason.

I fully agree.

**Comment by T-F-S** [comment]
OK, I will adopt your suggestion and add such a warning which is issued, if `imakeidx` is loaded after the `documentation` library.

Besides, I wonder, if the `imakeidx` package should issue such a warning itself, if it is loaded after or in combination with `makeidx`? I skipped through the manual of `imakeidx`, but found no immediate clue that is should not used together with `makeidx`, even it that may be obvious.

Anyhow, the `documentation` library will contain a warning in the next version.

**Comment by muzimuzhi** [comment]
> Besides, I wonder, if the `imakeidx` package should issue such a warning itself, if it is loaded after or in combination with `makeidx`? I skipped through the manual of `imakeidx`, but found no immediate clue that is should not used together with `makeidx`, even it that may be obvious.

`imakeidx.sty` contains
```tex
\@namedef{ver@makeidx.sty}{3000/12/31}
```
which will cheat latex as if `makeidx.sty` is already loaded hence make any following `\usepackage{makeidx}` silently ignored.

**Comment by T-F-S** [comment]
> > Besides, I wonder, if the `imakeidx` package should issue such a warning itself, if it is loaded after or in combination with `makeidx`? I skipped through the manual of `imakeidx`, but found no immediate clue that is should not used together with `makeidx`, even it that may be obvious.
> 
> [`imakeidx.sty`](https://tug.org/svn/texlive/trunk/Master/texmf-dist/tex/latex/imakeidx/imakeidx.sty?view=markup#l61) (2016/10/15 v1.3e) contains
> 
> ```
> \@namedef{ver@makeidx.sty}{3000/12/31}
> ```
> 
> which will cheat latex as if `makeidx.sty` is already loaded hence make any following `\usepackage{makeidx}` silently ignored.

Yes, but the critical sequence is loading `makeidx` and afterwards `imakeidx` where the OP asked for a warning by `tcolorbox` (which I add, but which *may* be better suited inside `imakeidx`).

**Comment by dbitouze** [comment]
>[...] which may be better suited inside `imakeidx`).

BTW, I drawn the attention of the author of `imakeidx` on this matter.
