### ISSUE TITLE
[documentation library] In the index, gather the indexed LaTeX macros as well

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#174]
Currently, the index automatically gathers the indexed:

- colors,
- counters,
- environments,
- fadings,
- keys,
- path operations,
- values.

Why not the LaTeX macros documented thanks to the `docCommand(s)` environments?

**Comment by muzimuzhi** [comment]
Not sure I get the point, but it seems `docCommand` env does create an index entry, for example the `\foomakedocSubKey(*)` in the package manual v5.0.2, sec. 26.1.

**Comment by muzimuzhi** [comment]
Ah guess that's on purpose, cause an index entry for command is the "normal" case, and any entries for non-command things are special hence has their sub-item form. (Assume most entries are for commands.)

Compare
https://github.com/T-F-S/tcolorbox/blob/20805e947fa5453f2ada5a26f457c537515062df/tex/latex/tcolorbox/tcbdocumentation.code.tex#L423-L428
with
https://github.com/T-F-S/tcolorbox/blob/20805e947fa5453f2ada5a26f457c537515062df/tex/latex/tcolorbox/tcbdocumentation.code.tex#L480-L486
It's the second `\kvtcb@index@command` used in `\__tcobox_index_environment:` that creates the sub-item form `\index{Environments!<envname>@\tcbIndexPrintEnvC {<envname>}}`.

**Comment by dbitouze** [comment]
Well, in the index of the `tcolorbox` documentation, commands look the exceptions and e.g. keys the "normal" entries :smile:
IMHO, it is worth for commands to have their own subitem...

**Comment by T-F-S** [comment]
> Currently, the index automatically gathers the indexed:
> 
>     * colors,
> 
>     * counters,
> 
>     * environments,
> 
>     * fadings,
> 
>     * keys,
> 
>     * path operations,
> 
>     * values.
> 
> 
> Why not the LaTeX macros documented thanks to the `docCommand(s)` environments?

I think one can argue direction of adding a makro collection or doing not.

Why is is not included? Well, I imitated the index entries of the TikZ manual to a certain (or even large) degree. There, commands are not gathered inside the index. As @muzimuzhi presumed, I see macros as **normal** case and the TikZ manual does also. Therefore, it is on purpose to not gather the commands.

Beside the **normal** case argument, commands of a package often use a common prefix like `\gtr...` and `\getree_...` for `genealogytree` which implies a natural gathering inside the index. Therefore, listing these sorted commands again under a heading `Commands` makes less sense than e.g. gathering key names which could be anything.

**Comment by dbitouze** [comment]
In the case of `tcolorbox`, many commands indeed share the `\tcb` prefix, but that's not the case for many other ones. 

Here is why I consider useful to add a macros collection: sometimes, you used to use a package and learn in its documentation a very useful macro, but the name of which you don't remember when you use again this package a long time later. You may want to look for this command in the index (if any) and, if the commands are gathered in a collection, this will surely save your time (e.g. in a 34 pages index, such as the `tcolorbox` one :wink:).

**Comment by dbitouze** [comment]
About "macros as normal case", the author of a package may decide to not create a dedicated package for commands, environments, keys, etc. In such a case, the index may be "cluttered" with ordinary words, which can be more numerous than the macros names which, then, may be considered as not "normal".

**Comment by T-F-S** [comment]
> In the case of `tcolorbox`, many commands indeed share the `\tcb` prefix, but that's not the case for many other ones.
> 
> Here is why I consider useful to add a macros collection: sometimes, you used to use a package and learn in its documentation a very useful macro, but the name of which you don't remember when you use again this package a long time later. You may want to look for this command in the index (if any) and, if the commands are gathered in a collection, this will surely save your time (e.g. in a 34 pages index, such as the `tcolorbox` one 😉).

Hmm... but instead of 34 pages we will get (I guess now) 41 pages with repeated things ...

**Comment by dbitouze** [comment]
> Hmm... but instead of 34 pages we will get (I guess now) 41 pages with repeated things ...

Indeed, but in the case of the `tcolorbox` documentation, the length of the index would be due to the repetition more of the keys than the commands.

**Comment by dbitouze** [comment]
>On the technical side, of course, I would see no problems to add such a collection of command in the index.

What about an option `/tcb/index ...` that would enable this feature?

**Comment by T-F-S** [comment]
Done with https://github.com/T-F-S/tcolorbox/releases/tag/v5.1.0
