### ISSUE TITLE
In the documentation, most _but not all of_ the commands, keys etc. are hyperlinked to where they are documented

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#175]
In the documentation of the `tcboutputlisting` environment (currently p. 323), the mentioned key `listing file` isn't hyperlinked to where it is documented. But in the documentation of `/tcb/compilable listing` (currently p. 345), the same key is hyperlinked to where it is documented.

Is there any reason for that? If not, it would be helpful for them to systematically be hyperlinked.

**Comment by T-F-S** [comment]
> Is there any reason for that? If not, it would be helpful for them to systematically be hyperlinked.

No, the only reason is, I think, that some documentation parts are older than other parts. I agree that hyperlinking should be done systematically. 

I run through the `listings` section now for hyperlinking. I'm sure that there is more in other parts of the documentation. When I overhaul other sections, I try to keep hyperlinking in mind where not done already.

**Comment by T-F-S** [comment]
Resolved with https://github.com/T-F-S/tcolorbox/releases/tag/v5.1.0
