### ISSUE TITLE
Triangular shadow to tcbox

### ISSUE THREAD

**Issue by cab-1729** [T-F-S/tcolorbox#178]
I want to achieve something that looks like this
![image](https://user-images.githubusercontent.com/60106638/168439844-5e9e6a52-e2c5-4615-9e24-fd5b0cb92dc6.png)

The shadow is triangular.
I couldn't find a way to do this from the manual. Is there a possible solution?

If not, could you perhaps provide an argument to ```/tcb/shadow```  that allows for this?

Also, is it possible to make ```borderline south``` extend beyond the boundaries of the box as shown in the above image?

**Comment by muzimuzhi** [comment]
Can you please provide an example showing what you've tried, so others can use it as a start point? For me it's unclear which part the desired triangular shadow is appended to, the box title or the whole box?

**Comment by cab-1729** [comment]
This is the base code I am using:
```tex
\tcbox[
	on line,
	colback=H2Color,
	colframe=white,
	top=0.1041667in,
	bottom=0.1041667in,
	right=0.1041667in,
	left=0.1041667in,
	notitle,
	boxrule=0pt,
	boxsep=0em,
	fontupper=\fontsize{1.3em}{\baselineskip}\bfseries\color{white},
	sharp corners=south,
	arc=0.031250001in,
	outer arc=0.031250001in,
	enhanced,
]{#1}
```

If I use one of the generic shadows in the manual, for example by adding ```shadow={2em}{0em}{0mm}{black}```, the resulting shadow is rectangular in shape.
![image](https://user-images.githubusercontent.com/60106638/168454296-bdafe87a-1f05-4000-bffa-4fa9df086545.png)

What I want to do is have this be triangular in shape. Using ```tikz``` doesn't help either because the ```(0,0)``` begins at the base of the line, not the base of the box : 

```tex
	\tcbox[
			on line,
			colback=H2Color,
			colframe=white,
			top=0.1041667in,
			bottom=0.1041667in,
			right=0.1041667in,
			left=0.1041667in,
			notitle,
			boxrule=0pt,
			boxsep=0em,
			fontupper=\fontsize{1.3em}{\baselineskip}\bfseries\color{white},
			sharp corners=south,
			arc=0.031250001in,
			outer arc=0.031250001in,
			enhanced,
		]{#1}
		\begin{tikzpicture}
			\filldraw[black] (0,0) -- (1,0) -- (0,0.7) -- cycle;
		\end{tikzpicture}
```
![image](https://user-images.githubusercontent.com/60106638/168454595-166cffaa-47d6-4004-b88a-c4881380ca5c.png)

even if I want tikz to make my shadow dip below the line, to align it with the box using negative coordinates it just adjusts the line height:

```tex
			\filldraw[black] (0,-1) -- (1,-1) -- (0,0.7) -- cycle;
````
![image](https://user-images.githubusercontent.com/60106638/168454627-44d20ffb-a48a-4b84-a060-c88f1f38bfed.png)

**Comment by muzimuzhi** [comment]
An attempt, using `overlay={<tikz graphic code>}` with geometry node `frame`, and enlargement options.

```tex
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{skins}

\colorlet{H2Color}{red!70!orange!80}

\newtcbox{\mybox}[1][]{
 	on line,
 	colback=H2Color,
 	colframe=white,
 	top=0.1041667in,
 	bottom=0.1041667in,
 	right=0.1041667in,
 	left=0.1041667in,
 	notitle,
 	boxrule=0pt,
 	boxsep=0em,
 	fontupper=\fontsize{1.3em}{\baselineskip}\bfseries\color{white},
 	sharp corners=south,
 	arc=0.031250001in,
 	outer arc=0.031250001in,
 	enhanced,
  overlay={
    \fill[gray!50] ([shift={(1pt,5pt)}]frame.north east) 
      -- ([xshift=1pt]frame.south east) -- +(.5,0)  -- cycle;
  },
  #1
}

\begin{document}
text before \mybox{Title} text after

text before \mybox[enlarge top by=5pt, enlarge right by=.5cm]{Title} text after
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/168468490-58d12dc5-2bf8-4869-bb2c-53b5d7773b9a.png)

> Using `tikz` doesn't help either because the `(0,0)` begins at the base of the line, not the base of the box : ...

This is caused by the option `on line`.

**Comment by cab-1729** [comment]
Your code pointed me in the right direction. Now I have got I wanted. Thanks a lot!
