### ISSUE TITLE
Feature Request: new option that wraps `\ifstrempty` 

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#179]
It will help users in checking if an argument is empty, especially when the argument is optional.

_Edit:_ Perhaps also a wrapper for `\ifblank`.

An example taken from https://tex.stackexchange.com/a/645447 (my own answer)
```tex
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{xparse}

\tcbset{
  ifstrempty/.code n args={3}{\ifstrempty{#1}{\pgfkeysalso{#2}}{\pgfkeysalso{#3}}},
}

\DeclareTColorBox[auto counter, number within=section]{mybox}{ o }
  {
    title={mybox \thetcbcounter},
    % add label only if #1 has value and is non empty
    IfNoValueTF={#1}{}{ifstrempty={#1}{}{label={mybox:#1}}}
  }

\begin{document}
\section{test}
\begin{mybox}        \end{mybox}
\begin{mybox}[]      \end{mybox}
\begin{mybox}[label] \end{mybox}

\ref{mybox:},     % label is undefined, hence typesets "??"
\ref{mybox:label} % typesets "1.3"
\end{document}
```

**Comment by T-F-S** [comment]
How about adopting `\tl_if_empty:nTF` and/or `\tl_if_blank:nTF` directly from expl3?

I agree that such options would be helpful. Actually, TikZ should provide such options since they are general and not really tcolorbox-specific. Anyhow, I am willing to add these options to tcolorbox. I just wonder where to document them? Maybe, under 4.24 Miscellaneous, since there also is `code`, another very general option.

```latex
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{xparse}

\ExplSyntaxOn
\tcbset
  {
    IfBlankTF/.code~n~args={3}{\tl_if_blank:nTF{#1}{\pgfkeysalso{#2}}{\pgfkeysalso{#3}}},
    IfBlankT/.code~n~args={2}{\tl_if_blank:nT{#1}{\pgfkeysalso{#2}}},
    IfBlankF/.code~n~args={2}{\tl_if_blank:nF{#1}{\pgfkeysalso{#2}}},
    IfEmptyTF/.code~n~args={3}{\tl_if_empty:nTF{#1}{\pgfkeysalso{#2}}{\pgfkeysalso{#3}}},
    IfEmptyT/.code~n~args={2}{\tl_if_empty:nT{#1}{\pgfkeysalso{#2}}},
    IfEmptyF/.code~n~args={2}{\tl_if_empty:nF{#1}{\pgfkeysalso{#2}}},
  }
\ExplSyntaxOff


\DeclareTColorBox[auto counter, number within=section]{mybox}{ o }
  {
    title={mybox \thetcbcounter},
    % add label only if #1 has value and is non empty
    IfNoValueTF={#1}{}{IfEmptyF={#1}{label={mybox:#1}}}
  }

\begin{document}
\section{test}
\begin{mybox}        \end{mybox}
\begin{mybox}[]      \end{mybox}
\begin{mybox}[labelx] \end{mybox}

\ref{mybox:},     % label is undefined, hence typesets "??"
\ref{mybox:labelx} % typesets "1.3"
\end{document}

```

**Comment by muzimuzhi** [comment]
> How about adopting `\tl_if_empty:nTF` and/or `\tl_if_blank:nTF` directly from expl3?

Yes it's better. Providing wrappers for kernel functions than providing wrappers for package macros is better.

> Actually, TikZ should provide such options since they are general and not really tcolorbox-specific.

I agree. Maybe as a `pgfkeys` library https://github.com/pgf-tikz/pgf/pull/1129, a recently introduced and not yet released (pity) mechanism.

> Maybe, under 4.24 Miscellaneous, since there also is `code`, another very general option.

Yes currently I'm afraid there's no better places.

To make them more noticeable, with adoption of #180, maybe options `IfValue(TF)`, `IfNoValue(TF)`, `IfBoolean(TF)`, `IfEmpty(TF)`, and `IfBlank(TF)` can live in a separate new subsection under sec. 4, named like "4.xx Value Determination/Conditionals". A good reason to rewrite the first three groups of options (and document their specific use case for `xparse`-style tcolorbox cmds/envs) so that all the five groups are wrappers of expl3 functions, uniformly.

**Comment by T-F-S** [comment]
Done with https://github.com/T-F-S/tcolorbox/releases/tag/v5.1.0
