### ISSUE TITLE
FR: Generalized text alignment options

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#184]
Currently, all the `halign` and `valign` options [1] are implemented as (pgfkeys) choice options, and the underlaying alignment code corresponding to each choice value is hard-coded. For example, `halign=justify` is defined by
```tex
\tcbset{
  % halign/.is choice,
  halign/justify/.code={\let\kvtcb@halignupper=\@empty},
}
```

Thus there's no user interface to use any other alignment possibilities, for example `\justifying` and `\RaggedRight` from `ragged2e` package.

Inspired by TeX-SX question https://tex.stackexchange.com/q/648711.

[1] Full list is `halign`, `halign upper`, `halign lower`, `halign title`, `valign`, `valign upper`, and `valign lower`.

**Proposal:**

Something like `halign code/.store in=\kvtcb@halignupper`. Check if `\hbox{<value>}` is a zero-sized box would make it a little bit more robust. Following is an attempt for `\tcb_if_zero_size:NTF <box> {<true>} {<false>}`, just for fun (or as a latex3 exercise :D).
```tex
\ExplSyntaxOn
\box_new:N \tcb_temp_box

% def
\prg_new_conditional:Nnn \tcb_if_zero_size:N { TF }
  {
    \bool_lazy_and:nnTF
      { \dim_compare_p:nNn { \box_wd:N \tcb_temp_box } = \c_zero_dim }
      { \dim_compare_p:nNn { \box_ht_plus_dp:N \tcb_temp_box } = \c_zero_dim }
      { \prg_return_true: }
      { \prg_return_false: }
  }

% use
\hbox_set:Nn \tcb_temp_box {\raggedright}
\tcb_if_zero_size:NTF \tcb_temp_box {True} {False} % typesets "True"

% this won't work, box is non-empty
\box_if_empty:NTF \tcb_temp_box {True} {False} % typesets "False"
\ExplSyntaxOff
```

**Comment by T-F-S** [comment]
Adding something like `halign code/.store in=\kvtcb@halignupper` is no problem.

If I understand you correctly, you also propose to check, if the code inside `\kvtcb@halignupper` has no dimensional effect? I like your `\tcb_if_zero_size:N` per se, but I would omit such a check here, because there are very numerous spots where such checks, warnings and error messages could be added theoretically, but are'nt. Think of `fontupper`, etc.pp.

**Comment by T-F-S** [comment]
Added to https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.0
