### ISSUE TITLE
FR: Exporting tikz filling options to a tikz library

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#185]
Currently tcb library `skins` provides several useful tikz filling options, which

> (These options) can be used in any `tikzpicture`.

according to the doc, Sec. 13 "TikZ Image and Picture Fill Extensions; Auxiliary Macros".

Hence exporting them to a tikz library would make them more accessible, and enables use cases outside of tcolorbox.

------
A tikz library is just a file named `tikzlibrary<lib-name>.code.tex`, that can start with an optional `\ProvidesFile{<file-name>}[<release-info>]`, see pgf-tikz/pgf#1162.

Possible problems when exporting:
 - Loading guard: `\tikzuselibrary` ensures each library (if loaded by `\tikzuselibrary`) can be loaded at most once.
 - Portability: A tikz library need not be portable (format independent), for example `external` library is supported for LaTeX only.
 - Independence:
   - `graphicx` is loaded by tikz in LaTeX, hence `\includegraphics` is not a problem.
   - `\tcbdimto` can be simply simulated if it's not yet defined.
   - About tcolorbox itself, `skins` lib will (surely) use `\tikzuselibrary{filling}`.

See https://github.com/T-F-S/tcolorbox/compare/v5.1.1...muzimuzhi:tcolorbox:tikz-lib-filling for my attempt. All the `docTikzKey` envs in `tcolorbox.doc.filling.tex` are copied to a new file `tikzlibraryfilling.test.tex`, to test if `filling` library can be used outside of tcolorbox.

**Comment by T-F-S** [comment]
Thank you for your detailed proposal. The idea is not bad to extract these TikZ options into a separate library.

I think there is no hurry to make this, since a normal user will see no difference (if `tcolorbox` is used), but I put this on my TODO list.

**Comment by T-F-S** [comment]
Done with https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.0. The new separate library is https://github.com/T-F-S/tikzfill
