### ISSUE TITLE
FR: Short title text for `list inside` and tcb theorems

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#186]
From https://tex.stackexchange.com/questions/651173/how-to-set-a-short-title-for-a-tcolorbox

For normal tcolorboxes, a new option `short title` and some patch to `\tcb@addcontentsline` will do the work.

For tcb theorems, it seems the short title must be given outside of general tcb options, like how theorem title is treated. See [current implementation of `\__tcobox_new_tcbtheorem:w`](https://github.com/T-F-S/tcolorbox/blob/5fead2b866401dc925c9881001d92b6ec6fd7e87/tex/latex/tcolorbox/tcbtheorems.code.tex#L150-L167).

**Attempt:**

```tex
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{theorems}
\usepackage{hyperref}

\makeatletter
% case 1, normal tcolorbox
\tcbset{
  short title/.store in=\kvtcb@shorttitle,
  % init
  short title=
}

% add a conditional on \kvtcb@shorttitle
\def\tcb@addcontentsline#1#2{%
  \ifx\kvtcb@listentry\@empty%
    \ifx\kvtcb@shorttitle\@empty % <<< added
      \ifx\kvtcb@title\@empty%
        \ifx\tcbtitletext\@empty%
          \addcontentsline{#1}{#2}{\protect\numberline{\thetcbcounter}{\ignorespaces\kvtcb@savedelimiter}}%
        \else%
          \addcontentsline{#1}{#2}{\protect\numberline{\thetcbcounter}{\ignorespaces\tcbtitletext}}%
        \fi%
      \else%
        \addcontentsline{#1}{#2}{\protect\numberline{\thetcbcounter}{\ignorespaces\kvtcb@title}}%
      \fi%
    \else % else branch for `\ifx\kvtcb@shorttitle\@empty`
      \addcontentsline{#1}{#2}{\protect\numberline{\thetcbcounter}{\ignorespaces\kvtcb@shorttitle}}%
    \fi
  \else%
    \addcontentsline{#1}{#2}{\kvtcb@listentry}%
  \fi%
}

\ExplSyntaxOn
% case 2, tcb theorem

% Syntax of theorem envs to be created
%   \begin{<thmname>}[<options>]{<title>}{<label>}
%   \begin{<thmname>}[<options>][<short title>]{<title>}{<label>} <<< new
%   \begin{<thmname>*}{<title>}{<label>}
\NewDocumentCommand \NewTcbTheorem {}
  {
    % "x" stands for xparse (actually latex kernel uses `ltcmd.dtx`)
    \__tcobox_new_tcbtheorem_x:w \NewTColorBox
  }
% and its Declare..., Renew..., and Provide... variants

\NewDocumentCommand \__tcobox_new_tcbtheorem_x:w { m O{} m m +m m }
  {
    #1 [auto~counter,#2] {#3} { +O{} +o +m m }
      {
        #5,
        title      = {\__tcobox_theo_title:nnn{#4}{\thetcbcounter}{##3}},
        IfValueTF  = {##2}
          { % short title is given
            list~entry = {\protect\numberline{\thetcbcounter}##2},
            nameref    = {##2},
          }
          {
            list~entry = {\protect\numberline{\thetcbcounter}##3},
            nameref    = {##3},
          },
        theo@label = {#6}{##4},
        ##1
      }
    #1 [#2,no~counter,list~inside=] {#3*} { +O{} +m }
      {
        #5,
        title = {\__tcobox_theo_title:nnn{#4}{}{##2}},
        ##1
      }
  }
\ExplSyntaxOff
\makeatother

\begin{document}
\tcblistof[\section*]{tcb}{List of Tcolorboxes}
\tcblistof[\section*]{th}{List of Theorems}

\section{Normal tcolorboxes}
\newtcolorbox[auto counter, number within=section, list inside=tcb]
  {mytcb}[1][]{before title=\thetcbcounter~, #1}

\begin{mytcb}[title=Loooooong title]
  content
\end{mytcb}

\begin{mytcb}[title=Loooooong title, short title=Short title]
  content
\end{mytcb}

\section{Tcb theorems}
\NewTcbTheorem[auto counter, number within=section, list inside={th}]
  {theorem}
  {Theorem}
  {}
  {th}

\begin{theorem}{Loooooong title}{a}
  \begin{equation}
      E= m c^2
  \end{equation}
\end{theorem}

\begin{theorem}[][Short title]{Loooooong title}{b}
  \begin{equation}
      E= m c^2
  \end{equation}
\end{theorem}

Theorems \nameref{th:a} and \nameref{th:b}.
\end{document}
```

![image](https://user-images.githubusercontent.com/6376638/179401411-05367282-2629-4cc6-b883-b0cb6508cded.png)

**Comment by T-F-S** [comment]
Actually, there is a `short title` option. It is called `list text`. So, your example would look like the following:

```latex
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{theorems}
\usepackage{hyperref}

\begin{document}
\tcblistof[\section*]{tcb}{List of Tcolorboxes}
\tcblistof[\section*]{th}{List of Theorems}

\section{Normal tcolorboxes}
\newtcolorbox[auto counter, number within=section, list inside=tcb]
  {mytcb}[1][]{before title=\thetcbcounter~, #1}

\begin{mytcb}[title=Loooooong title]
  content
\end{mytcb}

\begin{mytcb}[title=Loooooong title, list text=Short title]
  content
\end{mytcb}

\section{Tcb theorems}
\newtcbtheorem[auto counter, number within=section, list inside={th}]
  {theorem}
  {Theorem}
  {}
  {th}

\begin{theorem}{Loooooong title}{a}
  \begin{equation}
      E= m c^2
  \end{equation}
\end{theorem}

\begin{theorem}[list text=Short title]{Loooooong title}{b}
  \begin{equation}
      E= m c^2
  \end{equation}
\end{theorem}

Theorems \nameref{th:a} and \nameref{th:b}.
\end{document}
```

However, your answer to https://tex.stackexchange.com/questions/651173/how-to-set-a-short-title-for-a-tcolorbox would not work with `short title`, because `\footnotemark` etc. causes trouble inside `nameref`.

**Normal tcolorbox:**

Here, I would not do changes to `\tcb@addcontentsline`, but I see three possibilities:
- Not adding `short title` at all
- Making `short title` an alias for `list text`
- Making `short title` an abbreviation for setting `list text` and `nameref` together (currently, I like this variant best)

**Theorems:**

I really like your suggestion for `\NewTcbTheorem`. It feels natural too have the short title as (second) option and this avoids the `nameref` problem. Also `\NewTcbTheorem` is a drop-in replacement for `\newtcbtheorem`.

If nothing new comes up, I plan to use this and make `\newtcbtheorem` an alias for `\NewTcbTheorem`. I see no reason to keep a real `\newcommand` version here as I did for `tcolorbox` (to be on the save side there).

**Comment by T-F-S** [comment]
> \NewDocumentCommand \NewTcbTheorem {}
>   {
>     % "x" stands for xparse (actually latex kernel uses `ltcmd.dtx`)
>     \__tcobox_new_tcbtheorem_x:w \NewTColorBox
>   }

Is this `x` something you invented to denote `xparse` syntax or is it a common convention? I did not see it before, but I like it.

**Comment by muzimuzhi** [comment]
> Is this `x` something you invented to denote `xparse` syntax or is it a common convention? I did not see it before, but I like it.

I invented :). By convention I think`x` stands for extended version: packages color, xcolor, xxcolor (provided by pgf/tikz), backends dvipdf, dvipdfm, dvipdfmx, xdvipdfmx

**Comment by rickstaa** [comment]
@T-F-S Thanks a lot for your answer. I also overlooked the `/tcb/list text=⟨text⟩` option in the documentation. Feel free to answer https://tex.stackexchange.com/questions/651173/how-to-set-a-short-title-for-a-tcolorbox. @muzimuzhi Thanks again for all the help solving my issue. I learned a lot about expl3 and how to position footnotes correctly. 🚀

**Comment by T-F-S** [comment]
Added to https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.0
