### ISSUE TITLE
Problems of vertical spacing around equations inside tcolorbox

### ISSUE THREAD

**Issue by HuangXiaoKai** [T-F-S/tcolorbox#188]
# Problem 1 Asymmetric vertical spacing around equation
If I use `\begin{tcolorbox}[math]` to render a colorbox of equation (eqn 0 in figure below), it sits vertically at the center of the box, which is fine.
However, when I switch from `[math]` to `[ams equation]`, the above and below spacings are asymmetric as shown in eqn 2 below. 
In eqn 3, the vertical spacing of a equation in a normal paragraph is symmetric. So I suggest the asymmetry of eqn 2 in tcolorbox environment may be a bug to fix? 

(Eqn 1 is what you use in the package document, as a reference,  which looks fine, though.)

![image](https://user-images.githubusercontent.com/22166802/183230283-bd2f9576-b9ea-4485-85cd-1c939fe83202.png)
```
\documentclass[fleqn]{article}
\usepackage{amsmath} 
\usepackage[most]{tcolorbox}
\usepackage{lipsum} 

\begin{document}

\begin{tcolorbox}[math]
A+B=C \hfill (0)
\end{tcolorbox}

\begin{tcolorbox}[ams equation]
\sum\limits_{n=1}^{\infty} \frac{1}{n} = \infty.
\end{tcolorbox}

\begin{tcolorbox}[ams equation]
A+B=C
\end{tcolorbox}

\abovedisplayskip0pt
\belowdisplayskip0pt
Here I set {\ttfamily\textbackslash{}abovedisplayskip0pt} and {\ttfamily\textbackslash{}belowdisplayskip0pt}. Equation: 
\begin{equation}A+B=C\end{equation}
Here I set {\ttfamily\textbackslash{}abovedisplayskip0pt} and {\ttfamily\textbackslash{}belowdisplayskip0pt}. 

Compiled by XeLaTeX on OverLeaf.

\end{document}
```

# Problem 2 Abnormal spacing over equation with option [fleqn]

When puting a equation as the first element of a colorbox, even though the box starts a new paragraph (rather than new line), there's a big skip before the equation. This problem only shows with [fleqn] option. It may be another bug?

I can mannually cancel this skip by `\abovedisplayskip0pt`, but it's ugly and obviously not a good idea.
![image](https://user-images.githubusercontent.com/22166802/183231196-d1254d9c-4e23-447d-994e-fce928e10247.png)

```
\documentclass[fleqn]{article}
\usepackage{amsmath} 
\usepackage[most]{tcolorbox}
\usepackage{lipsum} 


\begin{document}

\lipsum[][2-3] Here's the end of the {\bfseries paragraph!}

\begin{tcolorbox}
\begin{equation}A+B=C\end{equation}
\end{tcolorbox}

\lipsum[][2] Here I set {\ttfamily\textbackslash{}abovedisplayskip0pt} and {\ttfamily\textbackslash{}belowdisplayskip0pt}.

\abovedisplayskip0pt
\belowdisplayskip0pt
\begin{tcolorbox}
\begin{equation}A+B=C\end{equation}
\end{tcolorbox}

\end{document}
```

# A comprehensive example
I tried to use your idea in [https://tex.stackexchange.com/questions/270939/list-environment-with-vertical-lines-along-nested-lists]() to generat an environment nested itself and has left lines, which is suitable to write complicated homework derivations. It looks like:
![image](https://user-images.githubusercontent.com/22166802/183231841-3bbd7c12-d159-42ec-b33d-4e94ccaa7ac6.png)
The reason for its spacing abnormality may be explained by my former 2 problems.

```
\documentclass[fleqn]{article}
\usepackage{amsmath} 
\usepackage[most]{tcolorbox}

\newtcolorbox{derivationNested}{
blanker,
breakable,
right=0mm,top=2mm,bottom=2mm,
before skip=5pt,
after skip=5pt,
every box/.style={left skip=15mm,borderline west={1.5pt}{-10mm}{gray!25!white}},
before upper={\abovedisplayskip4pt \belowdisplayskip4pt  }
%left skip=15mm,borderline west={1.5pt}{-10mm}{gray!25!white}
}
\setlength{\mathindent}{3mm}

\begin{document}

\begin{derivationNested}
Write down equation:
\[A=B\]
\begin{derivationNested}
\[B=C+D\]
\begin{derivationNested}
First term on the right,
\[C=E\]
\end{derivationNested}
\begin{derivationNested}
Second term on the right,
\[D=F\]
\end{derivationNested}
\[B=E+F\]
\end{derivationNested}
\[A=E+F\]
\begin{derivationNested}
Explain why.
\end{derivationNested}
\[A+G\]
So we conclude that bla.
\end{derivationNested}

\end{document}

```

**Comment by muzimuzhi** [comment]
It seems the behavior is inherited from `amsmath` and reproducible with `minipage`. My guess is that `amsmath` inserts `\(math)strut` to each line of its displayed equation environments. Tcolorbox option `parbox=false` seems to give better result, see right column in the below example.

```tex
\documentclass{article}
\usepackage{amsmath} 
\usepackage[theorems]{tcolorbox}

\makeatletter
\long\def\minipage@test#1{\par
  \fbox{\begin{minipage}[b]{\dimexpr.45\linewidth-2\fboxrule}#1\end{minipage}}
  \par
}

\def\minipageTest{%
  % emulate tcolorbox option `math`
  \noindent\texttt{minipage + inline displaystyle}
  \minipage@test{$\displaystyle A + B = C \hfill (0)$}
  % emulate tcolorbox option `ams equation`
  \noindent\texttt{minipage + equation env}
  \minipage@test{%
    \if@fleqn\vskip-\abovedisplayskip\fi
    \begin{equation} A + B = C \end{equation}}
}
\makeatother

\def\tcolorboxTest#1{%
  \noindent\texttt{tcolorbox + \detokenize{#1}}\par
  \begin{tcolorbox}[#1]               A + B = C \end{tcolorbox}
  \quad
  \begin{tcolorbox}[parbox=false, #1] A + B = C \end{tcolorbox}\par
}

\begin{document}
\fboxsep=0pt
\tcbset{width=.45\textwidth, nobeforeafter, size=fbox}

\subsection*{fleqn off}
\minipageTest
\tcolorboxTest{math}
\tcolorboxTest{ams equation}

\subsection*{fleqn on} \csname @fleqntrue\endcsname
\minipageTest
\tcolorboxTest{math}
\tcolorboxTest{ams equation}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/183245737-68428d24-5ef6-4e6b-a249-e7ecda55dd07.png)

**Comment by HuangXiaoKai** [comment]
Thank you! `parbox=false` solves the problem a lot!

However, are you willing to spend some time looking my "comprehensive example" and give some advices? Because `parbox=false` don't solve all problems about vertical spacing. As you can see below, the space befor an equation is still larger than below. (red arrows) Althrough I set `top` = `bottom`, `before skip` = `after skip`. And a used-to-be-good example now has wrong vertical spacing with `parbox=false`. (orange circle)

Thanks again.

p.s. I searched information about `\strut`, but found nothing valuable for this question.

![image](https://user-images.githubusercontent.com/22166802/183279227-6d074783-1bff-4d92-9fda-b1f89e31f307.png)
```
\documentclass[fleqn]{article}
\usepackage{amsmath} 
\usepackage[most]{tcolorbox}
\usepackage{lipsum}

\newtcolorbox{derivationNested}{
blanker,
breakable,
right=0mm,top=2mm,bottom=2mm,
before skip=5pt,
after skip=5pt,
parbox=false,
every box/.style={left skip=15mm,borderline west={1.5pt}{-10mm}{gray!25!white}},
before upper={\abovedisplayskip4pt \belowdisplayskip4pt  }
}
\setlength{\mathindent}{3mm}

\begin{document}

\begin{derivationNested}
Write down equation:
\[A=B\]
\begin{derivationNested}
\[B=C+D\]
\begin{derivationNested}
First term on the right,
\[C=E\]
\end{derivationNested}
\begin{derivationNested}
Second term on the right,
\[D=F\]
\end{derivationNested}
\[B=E+F\]
\end{derivationNested}
\[A=E+F\]
\begin{derivationNested}
Explain why.
\end{derivationNested}
\[A=G\]
So we conclude that bla.
\end{derivationNested}


\begin{derivationNested}
\lipsum[][10-11]\par
\begin{derivationNested}
\lipsum[][10-11]
\end{derivationNested}
\noindent\lipsum[][10-11]
\begin{derivationNested}
\lipsum[][10-11]
\end{derivationNested}
\noindent\lipsum[][10-11]
\end{derivationNested}


\end{document}
```

**Comment by muzimuzhi** [comment]
It's not recommended for a displayed equation to be on its own paragraph, and if so some extra above skip is added. Compare, for example `text \[ A = B \]` with `text\par \[ A = B \]`. But by setting `after skip=5pt`, a `derivationNested` env will always end with a new paragraph and a 5pt vskip. Thus you get asymmetric spacing as pointed by red arrows. 

Manual workarounds: add `\unskip` before such displayed equations, or add `after=` to the corresponding `derivationNested` envs. You may have to adjust the definition of `derivationNested` so that it can accept an optional arg.

Automatic solution: (La)TeX has very limited ability to do a look ahead (a `tcolorbox` env may not know it's followed by a displayed equation), thus _theoretically_ one could add some look behind code at the beginning of every displayed equation env.

With `tcolorbox` v5.1.1, I can't reproduce the problem pointed by orange circle.

> I tried to use your idea in https://tex.stackexchange.com/questions/270939/list-environment-with-vertical-lines-along-nested-lists to generat an environment nested itself and has left lines, which is suitable to write complicated homework derivations.

The example below also includes a modified attempt to detect if a `tcolorbox` is nested, by introducing a new option `IfExprTF={<if expr>}{<true options>}{<false options>}`.

<details>
  <summary>Full example</summary>

```tex
\documentclass[fleqn]{article}
\usepackage{amsmath}
\usepackage[most]{tcolorbox}
\usepackage{lipsum}

\makeatletter
\tcbset{
  % IfExprTF={<\ifxxx "expression">}{<true options>}{<false options>}
  IfExprTF/.code n args={3}{%
    #1\relax
      \expandafter\@firstoftwo
    \else
      \expandafter\@secondoftwo
    \fi{\pgfkeysalso{#2}}{\pgfkeysalso{#3}}%
  }
}
\makeatother

\newtcolorbox{derivationNested}[1][]{
  blanker,
  breakable,
  right=0mm, top=2mm, bottom=2mm,
  before skip=5pt,
  after skip=5pt,
  parbox=false,
  IfExprTF={\ifnum\value{tcblayer}>1}{
    left skip=15mm,
    borderline west={1.5pt}{-10mm}{gray!25!white}
  }{},
  before upper={\abovedisplayskip4pt \belowdisplayskip4pt },%
  #1
}
\setlength{\mathindent}{3mm}

\begin{document}

\noindent\textbf{Plain examples}\par
text     \[ A = B + C \] \par
text\par \[ A = B + C \]

\begin{derivationNested}
  Write down equation:
  \[A=B\]
  \begin{derivationNested}[after=] % workaround 1
    \[B=C+D\]
    \begin{derivationNested}
      First term on the right,
      \[C=E\]
    \end{derivationNested}
    \begin{derivationNested}
      Second term on the right,
      \[D=F\]
    \end{derivationNested}\unskip % workaround 2
    \[B=E+F\]
  \end{derivationNested}
  \[A=E+F\]
  \begin{derivationNested}
    Explain why.
  \end{derivationNested}\unskip
  \[A=G\]
  So we conclude that bla.
\end{derivationNested}

\begin{derivationNested}
  \lipsum[][10-11]\par
  \begin{derivationNested}
    \lipsum[][10-11]
  \end{derivationNested}
  
  \noindent\lipsum[][10-11]
  \begin{derivationNested}
    \lipsum[][10-11]
  \end{derivationNested}
  \noindent\lipsum[][10-11]
\end{derivationNested}

\end{document}
```

</details>

![image](https://user-images.githubusercontent.com/6376638/183282525-c3374fed-8986-4eff-bf08-a606386c911f.png)
![image](https://user-images.githubusercontent.com/6376638/183282534-17a00e1c-b1b8-49a8-ac6a-e5149f429644.png)
![image](https://user-images.githubusercontent.com/6376638/183282542-f293bb6b-415b-43eb-924f-fecf00597fa7.png)

**Comment by HuangXiaoKai** [comment]
Thanks! The result is good enough now!
