### ISSUE TITLE
coltitle in subtitle not working.

### ISSUE THREAD

**Issue by Tetragramm** [T-F-S/tcolorbox#189]
The subtitle always inherits the color of the main title, instead of being overridden by specific options.
Small example:
```latex
\begin{tcolorbox}[colback=red!20,colframe=red,size=small, boxrule=0pt,
    subtitle style={coltitle=black, boxrule=0pt, toprule=1pt, bottomrule=1pt, colback=white},
    title={First Title}]
    First Content
    \tcbsubtitle[coltitle=black]{SubTitle}
    Second Content
\end{tcolorbox}
```
produces
![image](https://user-images.githubusercontent.com/9815373/183360013-5933fdb5-4306-4394-ba05-e4967ee7943f.png)

Similarly, setting the main coltitle to black produces
![image](https://user-images.githubusercontent.com/9815373/183360641-eb638609-0848-4f72-953b-a0a9fee084e1.png)

**Comment by muzimuzhi** [comment]
`\tcbsubtitle` is itself a `tcolorbox` in which the subtitle is actually the upper part of the box, hence you need `colupper=black` instead of `coltitle=black`. Not sure if it's too late to add redirection for title options used in `<options>` of `\tcbsubtitle[<options>]{<subtitle>}`.

**Comment by T-F-S** [comment]
I think, @muzimuzhi has given all needed explanations. So, using `colupper` instead of `coltitle` for the subtitle does the trick.

```latex
\documentclass{article}
\usepackage{tcolorbox}

\tcbuselibrary{skins}

\begin{document}

\begin{tcolorbox}[colback=red!20,colframe=red,size=small, boxrule=0pt,
    subtitle style={boxrule=0pt, toprule=1pt, bottomrule=1pt, colback=white},
    title={First Title}]
    First Content
    \tcbsubtitle[colupper=black]{SubTitle}
    Second Content
\end{tcolorbox}

\begin{tcolorbox}[colback=red!20,colframe=red,size=small, boxrule=0pt,
    subtitle style={colupper=black, boxrule=0pt, toprule=1pt, bottomrule=1pt, colback=white},
    title={First Title}]
    First Content
    \tcbsubtitle{SubTitle}
    Second Content
\end{tcolorbox}

\end{document}
```

![grafik](https://user-images.githubusercontent.com/7982989/183850667-8af06745-6ca9-4315-b4d9-e874d66d0528.png)

**Comment by Tetragramm** [comment]
Sorry for disappearing.  Perhaps add a clarification to the documentation?  Page 26, where subtitle is described talks about how it's an independent tcolorbox, which implies the same settings work.  One of the examples could be given a different title color, or maybe a list of settings that don't get inherited (if there's more than one).

**Comment by T-F-S** [comment]
> Sorry for disappearing. Perhaps add a clarification to the documentation? Page 26, where subtitle is described talks about how it's an independent tcolorbox, which implies the same settings work. One of the examples could be given a different title color, or maybe a list of settings that don't get inherited (if there's more than one).

The next version will have an example with redish subtitles:

![grafik](https://user-images.githubusercontent.com/7982989/218089286-dc5469ce-82cb-4384-bcbe-957969d72175.png)

**Comment by T-F-S** [comment]
Documented in https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.0
