### ISSUE TITLE
I can't new a initialization option with `/.code`.

### ISSUE THREAD

**Issue by syvshc** [T-F-S/tcolorbox#191]
I want to set another initialization option with `/.code`, and I simplify my code as below:

```tex
\documentclass{article}
\usepackage{tcolorbox}
\tcbset{
  new/cnt/.code = {
      auto counter
  }
}
\newtcolorbox[cnt]{mybox}{title=MYBOX \thetcbcounter}
\begin{document}
  \begin{mybox}
    test
  \end{mybox}
\end{document}
```

After compiling with PDFLaTeX, there is an error:

```
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.8 ...box[cnt]{mybox}{title=MYBOX \thetcbcounter}
```

If I change `/.code` to `/.style`, it works. However, in my actual work, I have to use `/.code` with some parameters. Why would it happen?

**Comment by muzimuzhi** [comment]
> However, in my actual work, I have to use `/.code` with some parameters. Why would it happen?

Maybe you can show an actual example in which you have to use handler `/.code`.

In general, `key/.style={<key-val list>}` is equivalent to `key/.code=\pgfkeysalso{<key-val list>}`. See https://tikz.dev/pgfkeys#pgf./handlers/.style.

**Comment by syvshc** [comment]
Thanks for your reply, here is my simplified actual work: I'm writing a class, and I want to use a class option to control how counters behave. If I don't use `/.code`, I have to write

```latex
\documentclass{article}
\usepackage{tcolorbox}
\newif\ifRoman
% \Romantrue
\ifRoman
  \tcbset{new/cnt/.style = {auto counter, number format = \Roman}}
\else
  \tcbset{new/cnt/.style = {auto counter, number format = \roman}}
\fi
% \tcbset{
%   new/cnt/.code = {
%     auto counter, 
%     \ifRoman
%       number format = \Roman
%     \else
%       number format = \roman
%     \fi
%   }
% }
\newtcolorbox[cnt]{mybox}{title=MYBOX \thetcbcounter}
\begin{document}
\begin{mybox}
  test
\end{mybox}
\end{document}
```


If I use `/.code`, I can write things like what I commented.

**Comment by syvshc** [comment]
OH, I forgot I have to write `\tcbset` in `/.code`. I change my code to 

```latex
\documentclass{article}
\usepackage{tcolorbox}
\newif\ifRoman
\Romantrue
% \ifRoman
%   \tcbset{new/cnt/.style = {auto counter, number format = \Roman}}
% \else
%   \tcbset{new/cnt/.style = {auto counter, number format = \roman}}
% \fi
\tcbset{
  new/cnt/.code = {
    \ifRoman
      \tcbset{new/auto counter=true, new/number format = \Roman}
    \else
      \tcbset{new/auto counter, new/number format = \roman}
    \fi
  }
}
\newtcolorbox[cnt]{mybox}{title=MYBOX \thetcbcounter}
\begin{document}
\begin{mybox}
  test
\end{mybox}
\end{document}
```

things worked all right.

**Comment by muzimuzhi** [comment]
In `pgfkeys` layer, nesting `\pgf(q)keys`-derived commands (here `\tcbset`) might alter the current default key and cause unexpected results. `\pgfkeysalso`, the one I mentioned before, will _not_ alter default key hence is more suitable for use here. Also be careful with possibly excess space(s) coming from EOL(s).
```tex
\tcbset{
  new/cnt/.code = {%
    \ifRoman
      % when `/tcb/new/cnt` is used, the default key is `/tcb/new/`
      \pgfkeysalso{auto counter, number format = \Roman}%
    \else
      \pgfkeysalso{auto counter, number format = \roman}%
    \fi
  }
}
```

The example below shows another approach, with the help of a new utility key `LegacyIfTF={<name of bool>}{<true options>}{<false options>}`.
```tex
\documentclass{article}
\usepackage{tcolorbox}
\newif\ifRoman

\ExplSyntaxOn
% /tcb/LegacyIfTF={<name of bool>}{<true options>}{<false options>}
\tcbset{
  LegacyIfTF/.code~n~args={3}{
    \legacy_if:nTF {#1} {\pgfkeysalso{#2}} {\pgfkeysalso{#3}}
  }
}
\ExplSyntaxOff

\tcbset{
  new/cnt/.style = {
    auto counter,
    /tcb/LegacyIfTF={Roman}{number format=\Roman}{number format=\roman}
  }
}

\Romantrue
\newtcolorbox[cnt]{mybox}{title=MYBOX \thetcbcounter}
\Romanfalse
\newtcolorbox[cnt]{mybox2}{title=MYBOX \thetcbcounter}

\begin{document}
\begin{mybox}
  test
\end{mybox}

\begin{mybox2}
  test
\end{mybox2}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/186828375-049c4cd3-21fa-4c56-8f9e-df43af5324ca.png)

**Comment by muzimuzhi** [comment]
To be able to use in more general scenarios, for example in `tikz`, key path `/utils/LegacyIfTF` is better than `/utils/LegacyIfTF`. Note `pgfkeys` already provides `/utils/exec` which behaves exactly as `/tcb/code`.

**Comment by syvshc** [comment]
Thanks for @muzimuzhi 's reply. I'm not familiar with the `pgf` system, I have to read more documents. :)

**Comment by muzimuzhi** [comment]
And here's another possibility, using `pgfkeys`' `/.expand twice` key handler ([html doc](https://tikz.dev/pgfkeys#handlers/.expand:twice)):
```tex
\tcbset{
  new/cnt/.style = {
    auto counter,
    number format/.expand twice=
      \ifRoman\expandafter\Roman\else\expandafter\roman\fi
  }
}
```

Note both ways (`/utils/LegacyIfTF` and `/.expand twice`) are "lazy" (compared to "eager" evaluation), which means the value of `\ifRoman` is used every time when  `/tcb/new/cnt` is used, not when `/tcb/new/cnt` is defined. An eager implementation could be
```tex
\tcbset{
  new/cnt/.ecode = {%
    \noexpand\pgfkeysalso{
      auto counter, number format=
      \ifRoman
        \expandafter\noexpand\expandafter\Roman
      \else
        \expandafter\noexpand\expandafter\roman
      \fi
    }%
  }
}
```

**Comment by muzimuzhi** [comment]
Sorry for late comment, but I do think the `/.append style` way below is more readable:
```tex
\tcbset{new/cnt/.style=auto counter}
\ifRoman
  \tcbset{new/cnt/.append style={number format=\Roman}}
\else
  \tcbset{new/cnt/.append style={number format=\roman}}
\fi
```
