### ISSUE TITLE
`add to list`: only for _numbered_ boxes?

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#194]
The compilation of the following MCE:
```latex
\documentclass{article}
\usepackage{tcolorbox}
\usepackage{hyperref}

\setcounter{secnumdepth}{-10}

\begin{document}
\tableofcontents

\section{Foo section}

\begin{tcolorbox}[title=Foo box 1,phantom={\addcontentsline{toc}{section}{Foo box 1}}]
  Bar box 1
\end{tcolorbox}

% \begin{tcolorbox}[title=Foo box 2,add to list={⟨toc⟩}{⟨section⟩}]
%   Bar box 2
% \end{tcolorbox}
\end{document}
```
works like a charm and gives the expected result: the additional entry “Foo box 1” in the table of contents and in the bookmarks.

But, if the commented lines are uncommented, it fails with the error is:
```
! Undefined control sequence.
<argument> ...ction⟩}{\protect \numberline {\thetcbcounter 
                                                  }{\ignorespaces \kvtcb@tit...

l.16 ...ox 2,add to list={⟨toc⟩}{⟨section⟩}]
```
Does it mean `add to list` can be used only with _numbered_ boxes? If so, too bad!... and this should be specified in the documentation.

BTW, the documentation says (currently p. 111):

> `/tcb/add to list={⟨list⟩}{⟨type⟩}` [...] issues `\addcontentsline{⟨list⟩}{⟨type⟩}{⟨entry text⟩}`

but it is unclear what `⟨entry text⟩` is.

**Comment by muzimuzhi** [comment]
> Does it mean `add to list` can be used only with _numbered_ boxes?

Seems so. It's unclear if `add to list` is generally available or only works with `<init options>`.

Also I find for `\newtcolorbox`, no `<init options>` and empty `<init options>` behave differently.
```tex
\documentclass{article}
\usepackage{tcolorbox}

\newtcolorbox  {mytcbA}[1][]{add to list={toc}{section},#1} % no <init options>
\newtcolorbox[]{mytcbB}[1][]{add to list={toc}{section},#1} % empty <init options>

\begin{document}
\tableofcontents

\begin{mytcbA}[title=mytcb A] % error, \thetcbcounter undefined
  content
\end{mytcbA}

\begin{mytcbB}[title=mytcb B] % no error
  content
\end{mytcbB}
\end{document}
```
This (not the original issue) is a regression bug introduced by [v5.1.0](https://github.com/T-F-S/tcolorbox/commit/596e62ed064d24fe345c8c6aeb29633753dfc53b#diff-44d905050db2fcf15c6adeec1023018aff520f938884a90e6e5e1128a826ed5bL2077).

A possible fix would be
```diff
diff --git a/tex/latex/tcolorbox/tcolorbox.sty b/tex/latex/tcolorbox/tcolorbox.sty
index 21447f7..2fe54de 100644
--- a/tex/latex/tcolorbox/tcolorbox.sty
+++ b/tex/latex/tcolorbox/tcolorbox.sty
@@ -2139,10 +2139,7 @@
   {
     \edef\tcb@new@boxname{#2}
     \def\tcb@new@colopt{}
-    \tl_if_novalue:nF { #1 }
-      {
-        \tcb@proc@options@init{#1}{#2}
-      }
+    \tcb@proc@options@init{#1}{#2}
     \preto\tcb@new@colopt{savedelimiter=#2}
     \exp_args:Nc \cs_set_eq:NN { tcb@opt@#2 } \tcb@new@colopt
   }
@@ -2156,7 +2153,7 @@
   }
 
 
-\NewDocumentCommand \__tcobox_new_tcolorbox:w { m +o m o +o +m }
+\NewDocumentCommand \__tcobox_new_tcolorbox:w { m +O{} m o +o +m }
   {
     \__tcobox_process_newtcolorbox:nn { #2 }{ #3 }
     \tl_if_novalue:nTF { #4 }
```

**Comment by T-F-S** [comment]
I will look into this with more time.

But in short: 
- `add to list` is intended for numbered boxes only. Maybe, this option and similar like `list entry` should be moved to the initialization option chapter to make this more obvious.
- the regression bug is possibly no bug but a correction... But I will check.

**Comment by dbitouze** [comment]
> * `add to list` is intended for numbered boxes only.

Too bad. Though there are easy workarounds, it would be useful in the context of my example, i.e. when the section (and friends) are unnumbered.

**Comment by T-F-S** [comment]
>     * the regression bug is possibly no bug but a correction... But I will check.

I withdraw this statement and consider this to be a bug. There is no reason, why `\newtcolorbox{mytcbA}` should differ from `\newtcolorbox[]{mytcbA}`.

**Comment by T-F-S** [comment]
>     * `add to list` is intended for numbered boxes only. Maybe, this option and similar like `list entry` should be moved to the initialization option chapter to make this more obvious.

While it is in general true that `add to list` is intended for numbered boxes, you *may* use it for unnumbered boxes also, but you should set `list entry` to overwrite settings done for numbered boxes.

**Comment by T-F-S** [comment]
Resolved resp. documented with https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.0
