### ISSUE TITLE
filename typo in ctan install instructions

### ISSUE THREAD

**Issue by koreyhinton** [T-F-S/tcolorbox#196]
Hi,

I followed the CTAN install instructions, and realized there was just 1 file in the list that had a typo in it when pasted to a mv command.

```sh
mv tcbdocumenation.code.tex ~/texmf/tex/latex/tcolorbox
[stderr] mv: cannot stat 'tcbdocumenation.code.tex': No such file or directory

ls
[stdout] tcbdocumentation.code.tex
```

This is the corresponding list item:
* tcbdocumenation.code.tex -> /tex/latex/tcolorbox

**Proposed fix in 2 sections of README.md (Contents of the package, Installation)**

The file itself has a correct spelling, just the README.md needs an update to match the real filename.

It is just missing a 't':

tcbdocume`na`tion.code.tex -> tcbdocume`nta`tion.code.tex

Thanks, 
Korey Hinton

**Comment by T-F-S** [comment]
Thank you for hinting me to that typo. I think it is there quite a long time...
I will fix it for the next version.

**Comment by T-F-S** [comment]
Resolved with https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.0
