### ISSUE TITLE
Pstricks node connections and tcolorbox

### ISSUE THREAD

**Issue by martijor** [T-F-S/tcolorbox#197]
I noticed an issue when using specific pstricks commands inside a tcolorbox.
Here is some code illustrating the issue :
```latex
\documentclass[11pt,a4paper]{article}
\usepackage{pstricks}
\usepackage{pstricks-add}
\usepackage{tcolorbox}

\begin{document}
\begin{tcolorbox}
\psset{unit=1cm}
\begin{pspicture}(-1,-1)(3,3)
\pnode(0,0){A}
\pnode(2,2){B}
\ncdiag{A}{B}
\end{pspicture}
\end{tcolorbox}
End of document
\end{document}
```

The tcolorbox and the node connection are rendered but nothing that follows is. In this case, the part "End of document" is not rendered at all.
I used `ncdiag` but apparently the issue remains with any node connection with "arms".
Everything seems to work with `ncarc`.

I'm using Miktex and updated all the packages mentionned in the example.

**Comment by hvoss49** [comment]
Running the document with `lualatex`   and an up-to-date TeXLive works fine. Same with `xelatex`. Only with the sequence
`latex`->`dvips`->`ps2pdf`. If I remember well, then the dvips driver of tikz was buggy.

**Comment by martijor** [comment]
Correct. I only have this issue with  the combination `latex`->`dvips`->`ps2pdf`.

**Comment by muzimuzhi** [comment]
I've simplified the example to pgf + pstricks only, hence reported to pgf. See https://github.com/pgf-tikz/pgf/issues/1211.

**Comment by T-F-S** [comment]
> I've simplified the example to pgf + pstricks only, hence reported to pgf. See [pgf-tikz/pgf#1211](https://github.com/pgf-tikz/pgf/issues/1211).

I close this issue since it is a `pgf` / `pstricks` issue.
