### ISSUE TITLE
\end{document} error when newtcolorbox is wrapped by newcommand

### ISSUE THREAD

**Issue by nutti** [T-F-S/tcolorbox#198]
I'm working on the Pandoc environment with using tcolorbox package.
Pandoc could not parse the markdown between `\begin` and `\end`, so I tried to apply [this workaround](https://github.com/jgm/pandoc/issues/3145#issuecomment-402291782).
But this workaround does not work when `\newtcolorbox` has `capture=hbox` option.

I will show you the simple example.
When I delete the line `capture=hbox`, the error is gone.
Is there any workaround of this error?

* Tex file

```tex
\documentclass{ltjbook}

\usepackage{tcolorbox}
\tcbuselibrary{breakable,skins,raster,listings}
\tcbuselibrary{external}
\tcbuselibrary{minted}
\tcbEXTERNALIZE

\newtcolorbox{mybox}[1][]{
    tcbox width=auto limited,
    capture=hbox,         % If this line is deleted, the error is gone.
    enhanced,
    breakable,
    arc=5pt,
    top=5pt,
    right=5pt,
    left=5pt,
    bottom=5pt,
    boxrule=0pt,
    frame hidden,
    grow to left by=-20pt,
    title={\hspace{6pt}},
    #1
}

\newcommand\Wrap[1]{#1}
\let\Begin\begin
\let\End\end

\begin{document}

\Wrap{\Begin{mybox}}
aaa
\Wrap{\End{mybox}}

\end{document}
```

* Command

```bash
lualatex -halt-on-error -shell-escape test.tex
```

* Error message

```
! LaTeX Error: \begin{mybox} on input line 32 ended by \end{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.36 \end{document}
```

**Comment by muzimuzhi** [comment]
When `capture=hbox` is set, `\begin{mybox}` will collect the content of environment, hence it must see `\end{mybox}` directly. But in your example the end part `\end{mybox}` is first replaced by `\End{mybox}` then wrapped in a pair of braces, hence can't be seen directly.

This is a restriction inherited from `environ` package, which is used by `tcolorbox` to implement `capture=hbox`.

**Comment by nutti** [comment]
> What's the purpose and usage of your wrapping?

The purpose is a workaround of pandoc issue described at [here](https://github.com/jgm/pandoc/issues/3145#issuecomment-402291782).
We could not use both `\begin` and `\end` directly for avoiding the parsing problem of pandoc.
So we aliased them by other strings like `\Begin` and `\End`.

**Comment by muzimuzhi** [comment]
I'm not an experienced pandoc user so can you perhaps provide a complete pandoc example (input, command, and expected output)? A bit off-topic here. Maybe tex.stackexchange.com is better.

`tcolorbox`-derived environment is not the only one that will collect its content, always or in some cases (here  `capture=hbox`). For example, math envs like `align` from `amsmath` package always collect env content. Thus I'm afraid a general solution from latex side is harder than both you and I thought. Maybe it's feasible by introducing an extra [pandoc filter](https://pandoc.org/filters.html)?

**Comment by nutti** [comment]
Thanks. I understood this is not only `tcolorbox` problem.
pandoc filter is also interesting. I will check it. Thanks for your information.

I will close this issue because my problem seems beyond the scope of `tcolorbox`.
