### ISSUE TITLE
option parbox=false broke in itemize within tcolorbox within proof between tcolorbox and 4.42 and 5.1.1

### ISSUE THREAD

**Issue by SvendeVries** [T-F-S/tcolorbox#199]
Thanks to [make text invisible](https://tex.stackexchange.com/questions/562828/make-text-invisible/563327#563327) I use an environment hidebox based on tcolorbox, that hides material in the handoutversion of my lecture notes. This worked fine in TeXLive21 but I just noticed it broke in TeXLive22. As much as I see, the relevant versions of tcolorbox are 4.42 and 5.1.1. With 4.42 it works with 5.1.1 pdflatex complains

LaTeX Error: Something's wrong--perhaps a missing \item.
\item T est within proof .
MWE is:

```
\documentclass{scrbook}
\usepackage{amsthm}
\usepackage{tcolorbox}
\tcbuselibrary{skins,breakable}

\newenvironment{hidebox}{%
  \tcolorbox[%
  empty,
  invisible,
  parbox=false,
  noparskip,
  enhanced,
  breakable,
  frame style={draw=black!20,fill=none},
  boxrule=0pt, 
  colback=yellow, 
  left=-.5ex, right=-.5ex,
  before skip=0ex plus 2pt,
  after skip=1ex plus 2pt]
}{\endtcolorbox}

\begin{document}
a

\begin{hidebox}
 \begin{itemize}
  \item Test without proof
 \end{itemize}
\end{hidebox}

\begin{proof}
 \begin{hidebox}
   test
 \end{hidebox}
\end{proof}

\begin{proof}
 \begin{hidebox}
  \begin{itemize}
   \item Test within proof
  \end{itemize}
 \end{hidebox}
\end{proof}
\end{document}
```
The error goes away, if I comment out parbox=false. So in my usage case, I can just do that.

But given that my usage appears to be valid, there might be something underlying in tcolorbox that could be improved (further).

best,
sven

ps: reposted from: https://tex.stackexchange.com/questions/663638/option-parbox-false-broke-in-itemize-within-tcolorbox-within-proof-between-tcolo

**Comment by T-F-S** [comment]
I can confirm this behaviour. It is certainly connected with the chances done for https://github.com/T-F-S/tcolorbox/issues/171

A workaround would be to add a `\noindent` between `\begin{proof}` and  `\begin{hidebox}`...

The same is seen with the following code where something like `\noindent` is needed, if `parbox=false` us used.

```latex
\documentclass{article}
\usepackage{tcolorbox}

\begin{document}

\begin{itemize}
  \item
  \noindent
  \begin{tcolorbox}[parbox=false]
  \begin{itemize}
    \item Test
  \end{itemize}
  \end{tcolorbox}
\end{itemize}

\end{document}
```

Currently, I see no easy way to get the old behaviour back without breaking various other things. Still, `parbox=false` is an experimental setting and, unfortunately, is often cause of side effects...

**Comment by muzimuzhi** [comment]
I didn't dig into this, but have a feeling that something like
```diff
diff --git a/tex/latex/tcolorbox/tcolorbox.sty b/tex/latex/tcolorbox/tcolorbox.sty
index 21447f7..4b15b11 100644
--- a/tex/latex/tcolorbox/tcolorbox.sty
+++ b/tex/latex/tcolorbox/tcolorbox.sty
@@ -297,6 +297,9 @@
   after/.code={\def\kvtcb@afterbox{#1}\let\tcb@use@autoparskip=\relax},
   before skip balanced/.style={before={%
     \ifnum\lastnodetype=-1\relax%
+      \ifnum\parshape>0\relax % in case it's right after a list \item
+        \noindent
+      \fi
     \else%
       \par%
       \ifvmode%
```
might help.  Quoting from the _eTeX Manual_ (`texdoc etex`), sec. 3.4 Status Enquiries:

> When used as number, `\parshape` returns the number of lines of the current parshape specification (or zero).

In normal situations `\parshape` returns 0, and when it's right after an `\item`, `\parshape` returns 1.

**Comment by muzimuzhi** [comment]
I realized that `\ifnum\parshape>0\relax\noindent\fi` is too strong an assumption. It seems currently there's no reliable conditional to check if it's right after an `\item`.

**Comment by T-F-S** [comment]
Try the new release https://github.com/T-F-S/tcolorbox/releases/tag/v6.2.0
With the updated `parbox=false` mechanism I get no longer errors with your MWE.
