### ISSUE TITLE
Font color of `\section` not honored just after a page break

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#202]
As shown by the two following MCEs, the font color of `\section` (set thanks to either `sectsty` or `titlesec` packages) is not honored just after a page break within a breakable `\tcolorbox` environment:
```latex
\documentclass{article}
\usepackage{lipsum}
\usepackage{sectsty}
\usepackage{tcolorbox}

\tcbuselibrary{breakable}

\allsectionsfont{\color{red}}

\begin{document}
\begin{tcolorbox}[breakable]
  \section{Foo}
  \lipsum[1-3]
  Bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla.
  \section{Bar}
\end{tcolorbox}
\end{document}

\documentclass{article}
\usepackage{lipsum}
\usepackage{tcolorbox}
\usepackage[pagestyles]{titlesec}

\tcbuselibrary{breakable}

\titleformat{\section}{\color{red}}{\thesection.\enspace}{-3pt}{}

\begin{document}
\begin{tcolorbox}[breakable]
  \section{Foo}
  \lipsum[1-3]
  Bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla.
  \section{Bar}
\end{tcolorbox}
\end{document}
```
By contrast, no problem without `tcolorbox`:
```latex
\documentclass{article}
\usepackage{sectsty}
\usepackage{lipsum,xcolor}

\allsectionsfont{\color{red}}

\begin{document}
\section{Foo}
\lipsum[1-4]
Bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla.
\section{Bar}
\end{document}

\documentclass{article}
\usepackage{lipsum,xcolor}
\usepackage[pagestyles]{titlesec}

\titleformat{\section}{\color{red}}{\thesection.\enspace}{-3pt}{}

\begin{document}
\section{Foo}
\lipsum[1-4]
Bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
bla bla bla bla bla bla.
\section{Bar}
\end{document}
```

**Comment by muzimuzhi** [comment]
I didn't carefully rank the causes, but this looks very like a color stack issue, and option `use color stack` seems to fix (or work around) the problem.

`use color stack` is turned off by default because it works by inserting whatsit (more specifically color special) which might mess the typeset in certain conditions. See related issues #110 and #123, and the doc for `use color stack` for more info.

```tex
\documentclass{article}
\usepackage{lipsum}
\usepackage{sectsty}
\usepackage{tcolorbox}

\tcbuselibrary{breakable}

\allsectionsfont{\color{red}}

\begin{document}
\begin{tcolorbox}[breakable, use color stack=true]
  \section{Foo}
  \lipsum[1-4]\par
  Bla
  \section{Bar}
\end{tcolorbox}
\end{document}
```
- `use color stack=false` (default)
  ![image](https://user-images.githubusercontent.com/6376638/208315585-3091d059-f892-4f5f-b2ea-0f544d8b03bb.png)
- `use color stack=true`, noted the color of section 2 "Bar" is in red now
  ![image](https://user-images.githubusercontent.com/6376638/208315410-a8416bdd-6876-4df1-949f-aa6a087cec18.png)

**Comment by muzimuzhi** [comment]
Confirmed, this _is_ a color stack issue.

When you use `\color{red}` to style a section title, a `\section{Bar}` is like
```tex

\vskip ...
\begingroup
\color{red}
\thesection. Bar
\endgroup
\vskip ...
```
`\vskip` ensures TeX is in vertical mode, `\thesection` ensures TeX is in horizontal mode, but `\color{red}`, which results in  a color special (after some assignments), won't switch TeX's v- or h-modes. Therefore the vertical mode ends _after_ `\color{red}` (not before!), so there's a possible page break point right after `\color{red}`. Finally, when a `tcolorbox` truly breaks at such point, you encounter a color stack issue. That is, the state of the (default) color stack at the end of one page (or the first part of a broken vbox) is not restored at the beginning of next page (or the second part of a broken vbox), like
```tex
% first page
text \color{red}
% second page
\thesection % expected: "\thesection" is in red; actual: bar is in default color, normally black
```

`use color stack` makes use of multiple color stack supported by engines, at the cost of inserting extra color specials.
```tex
% first page
text \color{red}
<push current color to color stack 2>
% second page
<pop from color stack 2>
\thesection % now "\thesection" is in red
```

Another approach is to force switch to horizontal mode right before color special. `\leavevmode` is qualified for this job.  Among color commands, `\textcolor` inserts `\leavevmode` internally.
```tex
% for sectsty
\usepackage{sectsty}
\allsectionsfont{\leavevmode\color{red}}

% for titlesec
\usepackage[pagestyles,explicit]{titlesec}
\titleformat{\section}{}{\textcolor{red}{\thesection.\enspace#1}}{-3pt}{}
```

Personally I suggest to use this more robust `\leavevmode` trick.
It seems `breakable` tries to break the vbox right between `\color{red}` and `\thesection. Bar`, thus

**Comment by dbitouze** [comment]
@muzimuzhi  Many thanks for these very detailed answers and for the workarounds!

Unfortunately, my real use case sets the sections format thanks to `titlesec`, and `\textcolor{...}{...}`, being in h-mode, prevents any line break which makes the long sections titles cause margin overflows (this happens quite often since my real use case is a two-column document).

**Comment by muzimuzhi** [comment]
> ```
> \titleformat{\section}{}{\textcolor{red}{\thesection.\enspace#1}}{-3pt}{}
> ```

My previous demo was wrong use. With package option `explicit` applied, `#1` is normally used in the last marg of `\titleformat`, so the example below works
```tex
\documentclass{article}
\usepackage{lipsum}
\usepackage{tcolorbox}
\usepackage[pagestyles,explicit]{titlesec}

\tcbuselibrary{breakable}

\titleformat{\section}{}{\color{red}\thesection.\enspace}{-3pt}{\color{red}#1}

\begin{document}
\begin{tcolorbox}[breakable]
  \section{Foo}
  \lipsum[1-4]\par
  Bla\par
  \section{Bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar}
\end{tcolorbox}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/208320408-ccc02677-c907-4115-b7b6-2a4a4c12edd4.png)

BTW I think it's a bit wired to use `\section` inside a box. Among other things, `\mark` is lost if used inside a box. That means, `\section` in `tcolorbox` won't update page headers (see https://tex.stackexchange.com/q/509817/).

**Comment by dbitouze** [comment]
@muzimuzhi However, the `use color stack=true` workaround does the trick (and the drawback of this option isn't currently a problem for me): thanks again!

**Comment by dbitouze** [comment]
> BTW I think it's a bit wired to use `\section` inside a box.

I agree! In fact, it is an (ab)use of a class of mine by a user who has strong, strange and ugly requests :wink:
