### ISSUE TITLE
\tcbincludegraphics not working with accents

### ISSUE THREAD

**Issue by 135Sky** [T-F-S/tcolorbox#209]
Hello,
I have an error with accent caractere in filename or folders name.
It works with the \includegraphics but not with \tcbincludegraphics .
Can you fix this ?
Thank's you !
MWE :

```
\documentclass[10pt,a4paper]{report}
\usepackage[utf8]{inputenc}
\usepackage[french]{babel}
\usepackage[T1]{fontenc}
\usepackage{tcolorbox}
\tcbuselibrary{skins}
\begin{document}
	\includegraphics[scale=1]{Règle de Klechowski Z18}
	\tcbincludegraphics[title=\imagename]{Règle de Klechowski Z18}
\end{document}
```
![Règle de Klechowski Z18](https://user-images.githubusercontent.com/123827802/215279090-04f449da-f234-4f86-bc70-eab60ece25e8.png)

**Comment by muzimuzhi** [comment]
The patch contained in the example below seems to work.

```tex
\documentclass[10pt,a4paper]{report}
\usepackage[utf8]{inputenc}
\usepackage[french]{babel}
\usepackage[T1]{fontenc}

\usepackage{tcolorbox}
\tcbuselibrary{skins}

\usepackage{xpatch}
\makeatletter
\xpatchcmd\tcb@scanfilename
  % use a softer \protected@edef instead
  {\edef\x{\scantokens\expandafter{#2}}}
  {\protected@edef\x{\scantokens\expandafter{#2}}}
  {}{\PatchFailed}
\makeatother

\begin{document}
  % To get a so-named image, run
  % cp $(kpsewhich example-image-a.pdf) 'Règle de Klechowski Z18.pdf'
  \includegraphics[scale=1]{Règle de Klechowski Z18}
  \tcbincludegraphics[title=\imagename]{Règle de Klechowski Z18}
\end{document}
```
<img width="380" alt="image" src="https://user-images.githubusercontent.com/6376638/215281934-1ed36f74-6bc5-4fbd-8712-39f3fdb00194.png">

**Comment by 135Sky** [comment]
It doesn't work for me. I have the same error :
`! LaTeX Error: File `R�gle de Klechowski Z18' not found.` (using pdflatex)
I try it in a new distribution (Ubuntu 22.04), with tcolorbox 5.1.1
Thanks for the answer and the tips for a so-named image !
[test.pdf](https://github.com/T-F-S/tcolorbox/files/10528177/test.pdf)

**Comment by muzimuzhi** [comment]
My fault. On macOS I can't even reproduce the problem with your initial example. May be caused by different file systems used by different OS.

The following revised patch now works on overleaf.com (which runs on Linux 5.15.65+), using texlive 2022 + pdflatex.

```tex
\documentclass[10pt,a4paper]{report}
% \usepackage[utf8]{inputenc} % utf8 is the new default since latex2e 2018-04-01
\usepackage[french]{babel}
\usepackage[T1]{fontenc}

\usepackage{tcolorbox}
\tcbuselibrary{skins}

\usepackage{regexpatch}
\makeatletter
% use softer \protected@edef to prevent accents from being expanded by \edef
\xpatchcmd\tcb@scanfilename
  {\edef\x}
  {\protected@edef\x}
  {}{\PatchFailed}

\xpatchcmd*\tcb@include@graphics@preparefile
  {\edef\imagepath}
  {\protected@edef\imagepath}
  {}{\PatchFailed}
\makeatother

% create image on-the-fly since overleaf prevents uploading a file having
% special characters in its name
\usepackage{shellesc} % overleaf always uses -shell-escape
\ShellEscape{\detokenize{cp $(kpsewhich example-image-a.pdf) 'Règle de Klechowski Z18.pdf'}}

\begin{document}
  \includegraphics[scale=1]{Règle de Klechowski Z18}
  \tcbincludegraphics[title=\imagename]{Règle de Klechowski Z18}
\end{document}
```

**Comment by muzimuzhi** [comment]
BTW do `\tcb@scanfilename` and `\tcb@include@graphics@preparefile` really need the `\edef` on image file name?

**Comment by 135Sky** [comment]
I don't understand, can you give me an example of what you say ?
The solution works good for me (really helpful, thanks!).

**Comment by muzimuzhi** [comment]
Never mind, my previous comment is to the package/repository maintainer who is probably busy these days (which is fully understandable and I'm in no mean in a hurry to get a response). I'd like to keep my comment "soft" hence didn't at the maintainer.

The point in previous comment is, maybe in the two patched macros it's possible to avoid both `\protected@edef` and `\edef`, just `\def` with some expansion control. (In another word, I'm still not 100% confident about that `\protected@edef` will work for all valid but corner use cases.) Leaving the image file name/path to be only (fully) parsed by the LaTeX2e internals will probably prevent problems caused by the pre-processing of file name/path done in `tcolorbox` as much as possible.
