### ISSUE TITLE
Wrong padding when boxes break at tcblower position

### ISSUE THREAD

**Issue by nignasi** [T-F-S/tcolorbox#21]
I'm not sure if this question in tex.stackexchange shows a bug, but I can confirm the problem even with non bicolor boxes.

http://tex.stackexchange.com/questions/357908/breaking-tcolorbox-between-upper-and-lower-part/357969#357969

When break position is at page end, a little padding appears on next page before segmentation line. 

    \documentclass[11pt]{scrbook}
    \usepackage{lipsum}
    \usepackage[many]{tcolorbox}
    \newtcolorbox{example}[1][]{breakable, colback=black!10!white, 
                colbacklower=red!5!white, title={Example}, #1}
    \begin{document}
    \begin{example}%[pad after break=0mm]
    \lipsum[3-7]
    \tcblower
    \lipsum[8]
    \end{example}
    \end{document}

**Comment by T-F-S** [comment]
Indeed, this is not a bug but just the normal (and intended) behaviour.

But, I think that this can be optionally changed. For this, see my answer at

http://tex.stackexchange.com/questions/357908/breaking-tcolorbox-between-upper-and-lower-part/358218#358218

**Comment by T-F-S** [comment]
With version `4.03` and higher, there is an option `segmentation at break=false` to change this behaviour.
