### ISSUE TITLE
Typo in 6.0.0 release note: theorema -> theorems

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#211]
> **Added**
> - [...]
> - Library theorems: New theorem generation macros. Generated theorema
support an optional short title now (part of issue #<span></span>186):

https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.0

**Comment by T-F-S** [comment]
OK, thank you.

**Comment by T-F-S** [comment]
Fixed with https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.1
