### ISSUE TITLE
docs: update list of commands that `<init options>` can be used for

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#213]
List in package manual, beginning of sec. 5 _Initialization Option Keys_, which is not updated since it was firstly documented in [v3.05](https://github.com/T-F-S/tcolorbox/commit/8787eb0f236f76efc6039a697116705b063d7c7b):
https://github.com/T-F-S/tcolorbox/blob/92fd4672950e19e610cb8b77b25b975a485c157b/doc/latex/tcolorbox/tcolorbox.doc.initoptions.tex#L6-L16

Full list as of v6.0.1:
```tex
- \newtcolorbox,        \NewTColorBox,      \NewTotalTColorBox
- \newtcbox,            \NewTCBox,          \NewTotalTCBox
- \newtcblisting,       \NewTCBListing
- \newtcbinputlisting,  \NewTCBInputListing
- \newtcbtheorem,       \NewTcbTheorem
- \newtcboxfit,         \NewTCBoxFit,       \NewTotalTCBoxFit
```
Among them the `\NewTC...` variants may be considered not very necessary to be listed , but `\NewTotalTC...` ones, from my point of view, worth to be added.

**Comment by T-F-S** [comment]
Done with https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.2
