### ISSUE TITLE
Add fallback for `\tcbox` + capture mode `fitbox`

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#217]
In #156 and hence since v5.0.0, `\tcb@@capture@fitbox` will fallback to `\tcb@@capture@minipage` with an informative prompt, if `fitting` library is not loaded.

But I omitted the corresponding `\tcbox@inner@fitbox` used by `\tcbox` which should fallback to `\tcbox@inner@hbox`. Or, more likely, at that time I didn't know the existence of `\tcbox@inner@<capture mode>`.

```tex
\def\tcbox@inner@fitbox{%
  \tcb@error{You need to load `fitting' library to use capture mode `fitbox'}{}%
  % fallback
  \tcbox@inner@hbox
}
```

To end users, this means
```tex
\documentclass{article}
\usepackage{tcolorbox}
%\tcbuselibrary{fitting}

\begin{document}
\begin{tcolorbox}[capture=fitbox] upper \tcblower lower \end{tcolorbox}
% throw error
%   ! Package tcolorbox Error: You need to load `fitting' library to use capture mode `fitbox'.
% and fallback to "capture=minipage"

\tcbox[capture=fitbox]  {abc def}
% no capture mode related error, box is NOT captured
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/218720829-b062f79b-b469-4fc7-89fc-b1f7f391404b.png)

**Comment by T-F-S** [comment]
Good point. By adding the default `\tcb@@capture@fitbox`, the capture check for `fitbox` gives no error and `\tcbox` runs into void. I will add the supposed `\tcbox@inner@fitbox` to throw the error message.

**Comment by T-F-S** [comment]
Added to https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.2
