### ISSUE TITLE
What about L-formed boxes?

### ISSUE THREAD

**Issue by micheld93** [T-F-S/tcolorbox#22]
Hi, 

I would like to use your package for L-formed boxes. Is there a built-in possibility? How could it be possible?

Wishes

**Comment by T-F-S** [comment]
Could you explain what you would like to achieve?

There is no built-in stuff for non-rectangular text. `TeX` provide `\parshape` to do tricks with the shape of a text, see http://tex.stackexchange.com/questions/tagged/parshape for examples.

Special combinations of `\parshape` and `tcolorbox` may give the result you are looking for.

**Comment by micheld93** [comment]
I attached a picture to illustrate what I mean. I use your package to
create a scientific poster for conferences and there it would be helpful to
have a box in L-shape. Is it clearer, now?

Wishes,
Michel

2017-03-20 13:07 GMT+01:00 Thomas F. Sturm <notifications@github.com>:

**Comment by T-F-S** [comment]
There seems to be a problem with the example picture... (it is missing here).

**Comment by micheld93** [comment]
Oh, sorry. I replyed on the mail via my mail programme. There must be a problem. The picture should be available,
![l-block](https://cloud.githubusercontent.com/assets/7882686/24197070/70fa87e2-0f00-11e7-888e-f9e492716285.png)
 now.

**Comment by T-F-S** [comment]
I understand, what you want to do, but I fear that there is no simple solution. 

TeX does not provide specially shaped text areas apart from the things you can do with `\parshape`. All `\parshape`-based examples need special manual care for setting the shape. Therefore, there is nothing like a generic L-shaped `minipage` which would be needed here.

The second thing is box drawing. This is not really a problem, but there is no built-in stuff. Therefore, all components  would have to be drawn with basic TikZ commands. Further, a `tcolorbox` library for that makes no sense as long as there are no L-shaped `minipage` environments...

So, I do not see a sensible way to implements such a feature.

**Comment by micheld93** [comment]
Ok, I see. I wasn't aware of the complexity of this problem.
