### ISSUE TITLE
Option to draw frame *after* content

### ISSUE THREAD

**Issue by cdelledonne** [T-F-S/tcolorbox#220]
Hi! First of all, thank you for this insane package.

I am trying to find a way to output a box where the frame is drawn *after* the content. In my use case, the content is a colored table with sharp corners, and the box has rounded corners, thus the corners of the table overlap with the frame.

<details><summary>Click to expand a minimal working example</summary>
<p>

```tex
\documentclass{standalone}

\usepackage{tcolorbox}
\usepackage{nicematrix}

\begin{document}

\begin{tcolorbox}[
    boxsep=0cm,
    left=0cm,right=0cm,top=0cm,bottom=0cm,
    hbox,
]
\begin{NiceTabular}{ccccc}
    \CodeBefore
    \rowcolors{1-3}{green!30}{green!15}
    \Body
    A & B & C & D & E \\
    1 & 2 & 3 & 4 & 5 \\
    6 & 7 & 8 & 9 & 0 \\
\end{NiceTabular}
\end{tcolorbox}

\end{document}
```

</p>
</details>

The output is like the following:

![box-arc1mm](https://user-images.githubusercontent.com/24732205/221561320-1952c119-9559-4785-9106-83a8d9623ed7.png)

Additionally, when the arc of the boxed is more curved, e.g. by adding `arc=2mm` to the specification of the box, the content can spill out of the frame, as in the following screenshot:

![box-arc2mm](https://user-images.githubusercontent.com/24732205/221562366-c4b7767d-c7d9-4338-aae1-a8b6f3d7115b.png)

It would be great if there were a way to draw the frame after the content, so that the frame is always on top. It would be even better if there were some option to clip the content such that it does not overflow outside of the frame at all. The only workaround that I can think of is using `/tcb/finish` to draw an additional frame on top of the box, which doesn't seem very neat.

Thanks a lot in advance.

**Comment by T-F-S** [comment]
It is not possible to draw the frame after the content, but you can clip the content to stay inside the frame using `clip upper` from the `skins` library:

```latex
\documentclass{standalone}

\usepackage[skins]{tcolorbox}
\usepackage{nicematrix}

\begin{document}

\begin{tcolorbox}[
    enhanced,clip upper,
    boxsep=0cm,
    left=0cm,right=0cm,top=0cm,bottom=0cm,
    hbox,
]
\begin{NiceTabular}{ccccc}
    \CodeBefore
    \rowcolors{1-3}{green!30}{green!15}
    \Body
    A & B & C & D & E \\
    1 & 2 & 3 & 4 & 5 \\
    6 & 7 & 8 & 9 & 0 \\
\end{NiceTabular}
\end{tcolorbox}

\end{document}
```
![grafik](https://user-images.githubusercontent.com/7982989/221591618-3cf7fec9-39ce-4556-b1a0-70f30f821d4e.png)

**Comment by cdelledonne** [comment]
Ah that's awesome, I missed that. Thanks, you can close this issue as far as I'm concerned.
