### ISSUE TITLE
`\tcbhypernode` doesn't work in xetex

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#221]
(originally reported and answered in https://www.zhihu.com/question/586573750/answer/2913873055, in Chinese)

`\tcbhypernode{<macro>}{<node>}` is expected to use `<marco>` to create a hyperlink having the same size of tikz node `<node>`.  Currently in XeTeX such hyperlink is not created due to a XeTeX issue (actually I think the real culprit is xdvipdfmx).

As a workaround `hyperref` provides `\XeTeXLinkBox{<link text>}`, see `texdoc hyperref`, sec. 7.7 _`\XeTeXLinkBox`_ and [this answer](https://tex.stackexchange.com/a/67739) by Heiko Oberdiek.

One possible patch:
```tex
% !TeX TS-program = xelatex
\documentclass{article}
\usepackage[skins]{tcolorbox}
\usepackage{hyperref}

\makeatletter
\renewcommand{\tcbhypernode}[2]{\ifdefined\hypersetup\@ifundefined{pgf@sh@ns@#2}{}{%
  \node[inner sep=0pt,outer sep=0pt] at (#2.center){%
    \tcbsetmacrotowidthofnode\tcb@w@hn{#2}%
    \tcbsetmacrotoheightofnode\tcb@h@hn{#2}%
    % debug: show size of hyperlink hence the need of altering \XeTeXLinkMargin
    % \hypersetup{pdfborder=0 0 0}%
    % change: wrap hyperlink text in \tcb@XeTeXLinkBox
    #1{\tcb@XeTeXLinkBox{\vtop to \dimexpr\tcb@h@hn-2bp\relax{\hbox to \dimexpr\tcb@w@hn-2bp\relax{}\vfil}}}%
  };%
}\fi}

\ifdefined\XeTeXversion
  \long\def\tcb@XeTeXLinkBox{%
    \setlength{\XeTeXLinkMargin}{0pt}%
    \XeTeXLinkBox}
\else
  \let\tcb@XeTeXLinkBox=\@firstofone
\fi
\makeatother

\begin{document}
%\tcbset{mybox/.style={enhanced, colback=#1!10, colframe=#1!50!black}}

\begin{tcolorbox}[enhanced,
  colback=red!10,colframe=red!50!black,
  hypertarget=hypertwinA,
  hyperlink=hypertwinB,
  title=Box A
]
  Click me to jump to Box B.
\end{tcolorbox}

\begin{tcolorbox}[enhanced,
  colback=blue!10,colframe=blue!50!black,
  hypertarget=hypertwinB,
  hyperlink=hypertwinA,
  title=Box B (with \texttt{\string\XeTeXLinkBox})
]
  Click me to jump to Box A.
\end{tcolorbox}

\makeatletter
\let\tcb@XeTeXLinkBox=\@firstofone
\makeatother

\begin{tcolorbox}[enhanced,
  colback=blue!10,colframe=blue!50!black,
  hypertarget=hypertwinB2,
  hyperlink=hypertwinA,
  title=Box B2 (without \texttt{\string\XeTeXLinkBox})
]
  Click me to jump to Box A.
\end{tcolorbox}

\newpage % make enough room for hyperlink scrolling/jumping
\null
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/221687032-85f4b19b-c7fe-456e-b2bb-beb18be591b6.png)

Notes:
- Although `hyperref` provides `\XeTeXLinkBox` for all engines, I choose to only use it in XeTeX, to gain maximum backward compatibility for other engines.
- `\XeTeXversion` is used to test if it's in XeTeX. This is the same tester used by [`l3kernel` in defining `\c_sys_engine_str`](https://github.com/latex3/latex3/blob/8c8839aa7bea517803fd758f3aa793171ce77258/l3kernel/l3sys.dtx#L381-L403). Or if written in latex3 `\sys_if_engine_xetex:TF` can be used.

**Comment by T-F-S** [comment]
I will add this to the next version. Thank you!

**Comment by T-F-S** [comment]
Added to https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.2
