### ISSUE TITLE
`\tcbox` cannot auto-line break

### ISSUE THREAD

**Issue by futurelyf** [T-F-S/tcolorbox#223]
Hello there. I found the `\tcbox` cannot do the auto line break with option `on line`. Please have a look at the picture below.

```
\documentclass[11pt]{article}
\usepackage[dvipsnames]{xcolor}
\usepackage[most]{tcolorbox}

\newtcbox{\hlbox}[1][cyan]{enhanced jigsaw, on line, arc=0pt, outer arc=0pt, colback=#1!10!white, colframe=#1!80!black, boxsep=0pt, left=3pt, right=3pt, top=2pt, bottom=2pt, boxrule=0pt, bottomrule=1pt, toprule=1pt, breakable}

\begin{document}
The Canton System was a trade policy implemented by the Qing Dynasty in the 18th and 19th centuries that \hlbox[LimeGreen]{restricted foreign trade to the port of Canton (now Guangzhou) in southern China}.
\end{document}
```

<img width="658" alt="pic" src="https://user-images.githubusercontent.com/85407532/225446242-65c3857d-eb7a-47ec-97f6-944af82c4f5d.png">

As you can see, the green `on line` box has exceeded to the margin...
Thank you for your help and awesome package!

**Comment by T-F-S** [comment]
I fear, `\tcbox` is an unbreakable box. Marking lines with automatic line breaking is not supported by the `tcolorbox` package (would be nice, but is not possible).

**Comment by muzimuzhi** [comment]
In general TeX engines lack support for (arbitrary) text decorations, compared to Web techs.  For simple decorations (e.g., those leave text width intact, hence don't interact with line breaks) in simple situations (e.g., text mode only), one can try with underline packages with some configuration.

`ulem` is one choice (`\leaders` based), `zref` with drawing packages another (`\pdfsavepos` based, see TeX-SX question [Cool Text Highlighting in LaTeX](https://tex.stackexchange.com/q/5959)), `lua-ul` yet another (leaders based but won't interact with space stretching or shrinking), but LuaTeX only.  Also note
 - Unlike `\tcbox`, margins at very beginning and end of every line of decorated text are hard to achieve with `ulem`.
 - Sometimes box-leaders based solutions may cause observable thin overlaps (the `ulem` case), see https://github.com/CTeX-org/ctex-kit/issues/308 (in Chinese).

<details><summary>An example showing possibilities with <code>ulem</code> or <code>lua-ul</code></summary>

```tex
% !TeX TS-program = lualatex
\documentclass{article}
\ifdefined\directlua
  \usepackage{xcolor, luacolor} % xcolor must be loaded before luacolor
  \usepackage{lua-ul}
\fi
\usepackage{tcolorbox}
\usepackage[normalem]{ulem}

\makeatletter
\newbox\textdeco@box
% similar to initial value of `/tcb/adjust text`
\newcommand{\textdeco@text}{AHpgjy}

\AddToHook{selectfont}{%
  \savebox\textdeco@box{\textdeco@text}%
  \ht\textdeco@box=\dimexpr\ht\textdeco@box+2pt\relax
  \dp\textdeco@box=\dimexpr\dp\textdeco@box+2pt\relax
}

\newcommand\decorate[1][red]{\bgroup
  \markoverwith{%
    \rlap{\textcolor{#1!50!black}{\rule[\ht\textdeco@box]{2pt}{1pt}}}%
    \rlap{\textcolor{#1!10}{\rule[-\dp\textdeco@box]{2pt}{\dimexpr\ht\textdeco@box+\dp\textdeco@box}}}%
    \textcolor{#1!50!black}{\rule[-\dp\textdeco@box]{2pt}{1pt}}%
  }%
  \ULon
}

% based on \uuline in `ulem.sty`
\newcommand\uuuline[1][red]{\bgroup
  \markoverwith{\lower\dimexpr\dp\textdeco@box+1pt\hbox{%
    \vbox{{\color{#1!50!black}%
      \hrule width2pt height1pt
      {\color{#1!10}%
        \hrule height\dimexpr\ht\textdeco@box+\dp\textdeco@box\relax}%
      \hrule height1pt%
    }}%
  }}
 \ULon}

\ifdefined\directlua
  \NewDocumentCommand{\luaNestedUnderline}{ O{red} +m }
    {\underLine[color=#1!50!black, bottom=\ht\textdeco@box, height=1pt]{%
      \underLine[color=#1!10, top=\ht\textdeco@box, height=\ht\textdeco@box+\dp\textdeco@box]{%
        \underLine[color=#1!50!black, bottom=-\dp\textdeco@box, height=1pt]{#2}}}}
\fi
\makeatother

% copied from `\newtcbox` example in `texdoc tcolorbox` (v6.0.1), sec. 3.3
\newtcbox{\mybox}[1][red]{
  on line,
  arc=0pt, outer arc=0pt,
  colback=#1!10!white, colframe=#1!50!black,
  boxsep=0pt, left=1pt, right=1pt, top=2pt, bottom=2pt,
  boxrule=0pt, bottomrule=1pt, toprule=1pt
}

\begin{document}
\def\tests{%
  \hspace*{-2\parindent}No decoration\par
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
  eiusmod tempor incididunt ut labore et dolore
  magna aliqua.

  \hspace*{-2\parindent}\texttt{ulem} with configuration\par
  Lorem ipsum dolor sit amet, consectetur \decorate{adipiscing elit, sed do
  eiusmod tempor} incididunt ut labore et dolore
  \decorate[green]{magna aliqua.}
  
  Lorem ipsum dolor sit amet, consectetur \uuuline{adipiscing elit, sed do
  eiusmod tempor} incididunt ut labore et dolore
  \uuuline[green]{magna aliqua.}
  
  \ifdefined\directlua
    \hspace*{-2\parindent}\texttt{lua-ul \string\highLight} nested\par
    Lorem ipsum dolor sit amet, consectetur \luaNestedUnderline{adipiscing
    elit, sed do eiusmod tempor} incididunt ut labore et dolore
    \luaNestedUnderline[green]{magna aliqua.}
  \fi
}

\tests

\hspace*{-2\parindent}\texttt{\string\tcbox} with manual line breaks\par
Lorem ipsum dolor sit amet, consectetur \mybox{adipiscing elit, sed do eiusmod}
\allowbreak\mybox{tempor} incididunt ut labore et dolore
\mybox[green]{magna aliqua.}\par

\bigskip

%\newpage
\Large
\tests
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/225711935-73ed8015-ce43-4e75-b327-cfe4948ac2ac.png)
![image](https://user-images.githubusercontent.com/6376638/225711964-c940f1b0-79c2-4223-b7bd-4915f6b953db.png)

</details>

**Comment by muzimuzhi** [comment]
I forgot `soulpos`, which provides an easy-to-use interface to combine `\tcbox` with underline commands.  But still, it interacts with line-breaking and space stretching and strincking.

<details><summary>An <code>soulpos</code> example</summary>
<p>

```tex
\documentclass{article}
\usepackage{lipsum}
\usepackage{multicol}
\usepackage{soulpos}
\usepackage{tcolorbox}

\colorlet{ul}{red}
\newtcbox{\mybox}{
  on line,
  arc=0pt, outer arc=0pt,
  colback=ul!10!white, colframe=ul!50!black,
  boxsep=0pt, left=1pt, right=1pt, top=2pt, bottom=1pt,
  boxrule=0pt, bottomrule=1pt, toprule=1pt
}

\makeatletter
\newcommand\myul[1][red]{%
  \UseName{str_if_eq:nnF}{#1}{red}{\colorlet{ul}{#1}}
  \myul@}

\ulposdef\myul@[xoffset-start=1pt]{%
  \mybox{\vphantom{AHpgjy}\rule{\ulwidth}{0pt}}}
\makeatother

\begin{document}
\begin{multicols}{2}
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
  eiusmod tempor incididunt ut labore et dolore magna aliqua.
  \newcolumn
  
  Lorem ipsum dolor sit amet, consectetur \myul{adipiscing elit, sed do
  eiusmod tempor} incididunt ut labore et dolore
  \myul[green]{magna aliqua.}
\end{multicols}

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc facilisis vitae massa nec cursus. Fusce faucibus gravida dolor. Cras egestas eget nulla ut consequat. Nulla eu mi at mauris feugiat ornare. Etiam a efficitur sem, et scelerisque massa. Sed ipsum justo, posuere vitae leo vitae, fermentum dictum lacus. Morbi et ipsum vel neque congue elementum. In dolor orci, hendrerit vitae sagittis sit amet, pellentesque a magna.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc facilisis vitae massa nec cursus. Fusce faucibus gravida dolor. Cras egestas eget nulla ut consequat. Nulla eu mi at mauris feugiat ornare. \myul[orange]{Etiam a efficitur sem, et scelerisque massa. Sed ipsum justo, posuere vitae leo vitae, fermentum dictum lacus.} Morbi et ipsum vel neque congue elementum. In dolor orci, hendrerit vitae sagittis sit amet, pellentesque a magna.
\end{document}
```

</p>
</details> 

![image](https://user-images.githubusercontent.com/6376638/225751621-006ea58d-b1e5-4bf3-ac39-34b61ab8cbe5.png)

**Comment by futurelyf** [comment]
Hi @muzimuzhi , your suggestion of using `soulpos` is really helpful.
Thanks for your help!

@T-F-S Maybe you could consider integrate this mechanism into the package?

Thanks again for this awesome package and all the help :)

**Comment by T-F-S** [comment]
I close this for now, because I do not see an integration into the package. The suggested combined use of `\tcbox` and `soulpos` is a good application.

**Comment by muzimuzhi** [comment]
> > I forgot `soulpos`, which provides an easy-to-use interface to combine `\tcbox` with underline mechanism. But still, it interacts with line-breaking and space stretching and strincking.
> > An `soulpos` example
> > [...]
> 
> Is there a solution for using it with `mintinline`?

@Heziode In the `\tcbox` + `soulpos` case, the long input is first broken into (partial) lines by `soulpos`, then each partial line is decorated by `\tcbox`. But to have a similarly-working `\mintinline`, a different routine is needed: the long input needs first to be tokenized and highlighted by `minted`, then broken into (partial) lines, at last decorated.

I recommend asking on tex.stackexchange.com.
