### ISSUE TITLE
Inconsistent package versions, 6.0.2 vs 6.0.3

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#224]
In 
- commit message (https://github.com/T-F-S/tcolorbox/commit/67963e25ceb3a685c5521413eea52cb5128ddc1a),
- tag name (https://github.com/T-F-S/tcolorbox/tree/v6.0.2),
- release title (https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.2), and
- `CHANGES.md` (https://github.com/T-F-S/tcolorbox/blob/67963e25ceb3a685c5521413eea52cb5128ddc1a/doc/latex/tcolorbox/CHANGES.md),

the latest version released on 2023-03-17 is numbered 6.0.2.

But in all source files (hence in the title of package doc) and in the corresponding CTAN page (https://ctan.org/pkg/tcolorbox), the same release is numbered 6.0.3.

At least the next version has to start from 6.0.4. :)

**Comment by T-F-S** [comment]
Seems I mixed that up. I will name the next version (at least) 6.0.4 as you have suggested. Thank you.
