### ISSUE TITLE
Provide options that can test box and a given label fall onto the same page.

### ISSUE THREAD

**Issue by Sophanatprime** [T-F-S/tcolorbox#226]
In `varioref` package, we can test whether label and reference fall onto the same page.
Maybe `tcolorbox` can provide some options which can test if box and a given label fall onto the same page, 
say `if label is thepage={label}{true options}{false options}` (I haven't thought of a better name).
And by using `\ReadonlyShipoutCounter` (`\g_shipout_readonly_int`) or `zref-abspage` we can save the absolute page so that we can test whether a label is before or after the box even if we changed `\pagenumbering`.

**Comment by T-F-S** [comment]
Could you give an application example or an explanation where this option would be helpful?

If the absolute page is not essential, the following code may do the trick:

```latex
\documentclass{article}
\usepackage{lipsum}
\usepackage{tcolorbox}

\makeatletter

\ExplSyntaxOn
\NewDocumentCommand \tcbiflabeloncurrentpage { m }
  {
    \cs_if_exist:cTF {r@#1}
      {
        \int_compare:nNnTF { \exp_last_unbraced:Nv \use_ii:nn {r@#1} } = { \thetcolorboxpage }
          {
            \use_i:nn
          }
          {
            \use_ii:nn
          }
      }
      {
        \use_ii:nn
      }
  }
\ExplSyntaxOff

\tcbset{%
  if label on current page/.code n args={3}{%
    \tcbset{check odd page}%
    \tcbiflabeloncurrentpage{#1}{\tcbset{#2}}{\tcbset{#3}}%
  },
}
\makeatother


\NewTColorBox{mybox}{O{}m}
  {
    if label on current page={#2}%
      {
        title = {Label '#2' is on this page},
        colframe=red,colback=red!5
      }%
      {
        title = {Label '#2' is on not this page},
        colframe=blue,colback=blue!5
      },
    fonttitle=\bfseries,#1,
  }


\begin{document}

\lipsum[1]
\textcolor{red}{LABEL}\label{testlabel}

\begin{mybox}{testlabel}
  Some example content
\end{mybox}

\lipsum[2]

\begin{mybox}{testlabel}
  Some example content
\end{mybox}

\lipsum[3]

\begin{mybox}{testlabel}
  Some example content
\end{mybox}

\lipsum[4]

\begin{mybox}{testlabel}
  Some example content
\end{mybox}

\end{document}
```

![grafik](https://user-images.githubusercontent.com/7982989/229737889-9652d6b8-c967-4189-acd9-729897d7b8cc.png)

![grafik](https://user-images.githubusercontent.com/7982989/229737989-4a408002-8b08-458c-9f35-8ed7166c7676.png)

**Comment by Sophanatprime** [comment]
I'm trying to let the `multicol` package can add a frame around the text. When the frame is a `\tcbox`, it will look like the content of `\tcbox` can be split into multi-columns.
The user interface would be like this:
```tex
\blindtext[1]

\startmulticolumns[cols=2, framed=tcbox, framed-options={enhanced,watermark text=TCB multicols}]
\blindtext[4][1]
\stopmulticolumns
```
and the result is:
<img width="588" alt="image" src="https://user-images.githubusercontent.com/55335597/229774926-37e16de0-8d42-4dfb-80f7-21d41c876a19.png">

To support setting different options according if the box is `unbroken`, `first`, `middle`, or `last`, it needs to know if it is in those parts. 
The first approach that comes to my mind is using `\label`. We add labels before and after the `multicols` environment and test if the box is on the same page with one of those labels. I believe it will work.

And today I have another approach to test if the box is `unbroken` or else. But I am not confident it will always work. So maybe it still needs those label-testing options.

**Comment by muzimuzhi** [comment]
> To support setting different options according if the box is `unbroken`, `first`, `middle`, or `last`, it needs to know if it is in those parts.

@Sophanatprime Try `extras (unbroken|first|middle|last)` options, documented in package manual for v6.0.3 (2023/03/17), sec. 19.5 _Extra Options for Partial Boxes_:
```tex
\documentclass{article}
\usepackage[margin=.2in, noheadfoot, papersize={8cm,5cm}]{geometry}
\usepackage{lipsum}
\usepackage{tcolorbox}
\tcbuselibrary{breakable}

\tcbset{
  extras unbroken={colback=gray!20},
  extras first={colback=red!20},
  extras middle={colback=green!20},
  extras last={colback=blue!20}
}

\begin{document}
\begin{tcolorbox}[breakable]
  \lipsum[1][1]
\end{tcolorbox}

\begin{tcolorbox}[breakable]
  \lipsum[1]
\end{tcolorbox}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/229937804-2467a14b-7808-4012-a01b-1c9f2ecc598c.png)

**Comment by muzimuzhi** [comment]
Note `if odd page={<true options>}{<false options>}` has static behavior for a break sequence because it only checks if a `tcolorbox` starts from an odd page.  The deeper cause is, for `phantom=<code>` the `<code>` is executed for the first box of a break sequence only. (`if odd page` sets `check odd page` which then appends a label-like cmd to the internal macro that holds accumulated `phantom=<code>`.)

Also extracting page value from a label is specific to the currently in use label-ref mechanism. For example if `hyperref` (or its sub-package `nameref`) is loaded, `\cs{r@<label>}` will contain five, not two braced items.  Learnt from existing wheels like [`refcount`](https://ctan.org/pkg/refcount) ([`crossreftools`](https://ctan.org/pkg/crossreftools) another one), one possible improvement for `\tcbiflabeloncurrentpage` (though I think its name is misleading) could be

<details><summary><code>\tcbiflabeloncurrentpage</code> compatible with <code>hyperref</code></summary>
<p>

```tex
\documentclass{article}
\usepackage[margin=.2in, noheadfoot, papersize={8cm,5cm}]{geometry}
\usepackage{tcolorbox}
\usepackage[colorlinks]{hyperref}
%\usepackage{cleveref}

\ExplSyntaxOn
\NewDocumentCommand \tcbiflabeloncurrentpage { m }
  {
    \cs_if_exist:cTF {r@#1}
      {
        \int_compare:nNnTF { \tcb_extract_page_from_label:n {#1} } = { \thetcolorboxpage }
          \use_i:nn
          \use_ii:nn
      }
      {
        \use_ii:nn
      }
  }

\cs_new:Nn \tcb_extract_page_from_label:n
  {
    \exp_last_unbraced:Nv \tcb_extract_page_from_label_aux:nnw {r@#1} \q_nil
  }
\cs_new:Npn \tcb_extract_page_from_label_aux:nnw #1#2#3\q_nil
  % use 0 as default page
  { \tl_if_empty:nTF {#2} {0} {#2} }
\ExplSyntaxOff

\begin{document}
\def\dummybox{\begin{tcolorbox}[check odd page]
  \autoref{sec:first}:
  \tcbiflabeloncurrentpage{sec:first}{on same page}{on different pages}
  
  \autoref{sec:second}:
  \tcbiflabeloncurrentpage{sec:second}{on same page}{on different pages}
\end{tcolorbox}}

\dummybox
\section{title}\label{sec:first}
\newpage

\section{title}\label{sec:second}
\dummybox
\end{document}
```

</p>
</details> 

![image](https://user-images.githubusercontent.com/6376638/229944798-6da30bb4-de4c-498c-b7ad-2d7192b7203f.png)

**Comment by muzimuzhi** [comment]
> Note you also need to set sth like `extras={if odd page={...}{...}}` to have switching behaviors for a break sequence. Otherwise the `check odd page` is only executed for the first box of a break sequence.

Hmm I find I have to additionally pass `check odd page` to the box. Otherwise the first box in a break sequence may have off-by-1 `\thetcolorboxpage`.

<details><summary>Full example</summary>
<p>

```tex
\documentclass{article}
\usepackage[margin=.2in, noheadfoot, papersize={7.5cm,5cm}]{geometry}
\usepackage{lipsum}
\usepackage{tcolorbox}
\tcbuselibrary{breakable, skins}

\usepackage[colorlinks]{hyperref}

\ExplSyntaxOn
\NewDocumentCommand \tcbiflabeloncurrentpage { m }
  {
    \cs_if_exist:cTF {r@#1}
      {
        \int_compare:nNnTF { \tcb_extract_page_from_label:n {#1} } = { \thetcolorboxpage }
          \use_i:nn
          \use_ii:nn
      }
      {
        \use_ii:nn
      }
  }

\cs_new:Nn \tcb_extract_page_from_label:n
  {
    \exp_last_unbraced:Nv \tcb_extract_page_from_label_aux:nnw {r@#1} \q_nil
  }
\cs_new:Npn \tcb_extract_page_from_label_aux:nnw #1#2#3\q_nil
  % use 0 as default page
  { \tl_if_empty:nTF {#2} {0} {#2} }
\ExplSyntaxOff

\tcbset{
  enhanced,
  watermark color=blue!50,
  extras={
    check odd page,
    watermark text={%
      p\thetcolorboxpage,%
      \tcbiflabeloncurrentpage{sec:first}TF%,%
      \tcbiflabeloncurrentpage{sec:second}TF
    }
  }
}

\begin{document}
\long\def\dummybox#1{%
  \begin{tcolorbox}[breakable, check odd page] % <<< this "check odd page" is needed
    #1%
  \end{tcolorbox}}

\dummybox{dummy}

\section{title}\label{sec:first} text
\dummybox{\lipsum[1][1-12]}

\section{title}\label{sec:second}
\end{document}
```

</p>
</details> 

- With `extras={check odd page, ...}` + `\begin{tcolorbox}[breakable, check odd page]`
   ![image](https://user-images.githubusercontent.com/6376638/229952322-ff2a6fd4-1abf-478f-a82a-90c2f3aec677.png)
- With `extras={check odd page, ...}` + `\begin{tcolorbox}[breakable]`
   ![image](https://user-images.githubusercontent.com/6376638/229952617-13abfa0e-5d5e-4a6f-bfa3-7fd771d584c4.png)

**Comment by Sophanatprime** [comment]
I may not have made myself clear.
We know the `multicols` environment cannot break in a `tcolorbox-breakable` environment.
So instead of putting `multicols` in `tcolorbox`, we can patch `multicols` and let it can add a frame around it. So it will look like a `multicols` in a `tcolorbox`.
To do that, we have to patch the output routine changed by `multicols`. And I doubt that the `breakable` library can do its job properly in that circumstance. So unfortunately we cannot use the powerful `breakable` library. (but still use those --- `unbroken`, `first`, etc. --- terms)
So if `tcolorbox` can add some label-testing options, I can use them to test if the box is `unbroken` or else.

**Comment by muzimuzhi** [comment]
> To do that, we have to patch the output routine changed by `multicols`. And I doubt that the `breakable` library can do its job properly in that circumstance. So unfortunately we cannot use the powerful `breakable` library. (but still use those --- `unbroken`, `first`, etc. --- terms)

So the `tcolorbox` is added at the end stage of every `multicols` "shipout" routine, one by one. Not a single breakable `tcolorbox` added to the whole `multicols` env which will then be broken into a box sequence.  The words like "unbroken" and "first" are used to describe the box sequence of `multicols` env...

I believe these states can be told directly by `multicols`, and that's a more general solution (if you switch to another decoration solution other than `tcolorbox`, you don't need to ask a question similar to current again; or suppose someone wants to have variable-looking column rules). Also I think https://github.com/T-F-S/tcolorbox/issues/226#issuecomment-1495582357 plus an improved `\tcbiflabeloncurrentpage` in https://github.com/T-F-S/tcolorbox/issues/226#issuecomment-1496724304 should be sufficient.

**Comment by Sophanatprime** [comment]
> So the `tcolorbox` is added at the end stage of every `multicols` "shipout" routine, one by one.

Yes.

>I believe these states can be told directly by `multicols`

Indeed. (I tried yesterday. But when adding a frame around `multicols`, there are some occasions it cannot break the last box properly. I haven't found out why. Maybe it still needs labels.)
And I believe there must have other usages, I haven't thought out though 😂.

**Comment by T-F-S** [comment]
I close this for now.
