### ISSUE TITLE
vertical skip following display math at tail of tcolorbox content

### ISSUE THREAD

**Issue by Alex-Jordan** [T-F-S/tcolorbox#227]
If the last line of content in a `tcolorbox` is display math, the usual vertical skip that follows display math is sort of eaten up. The display math ends up closer to the bottom of the `tcolorbox` than I would expect. It's not symmetric with the vertical skip preceding the displaymath. Here is a MWE:

```
\documentclass{article}
\usepackage{tcolorbox,lipsum}

\begin{document}
\begin{tcolorbox}
\lipsum[1][1]
\[1+1=2\]
\end{tcolorbox}
\end{document}
```

which comes out looking like:

<img width="600" alt="Screen Shot 2023-04-04 at 3 59 15 PM" src="https://user-images.githubusercontent.com/4732672/229940470-920a2f85-42f4-4a9f-bf73-2d17a8d7664a.png">

I'm not sure what I should expect, but maybe something closer to:

<img width="600" alt="Screen Shot 2023-04-04 at 4 05 54 PM" src="https://user-images.githubusercontent.com/4732672/229941695-034ad261-7f80-4372-a593-61579127eef9.png">

**Comment by muzimuzhi** [comment]
It's inherited from `minipage` environment, which uses an `\unskip` in `\endminipage`.  `\parbox` doesn't have this "feature".

To keep such a vertical skip one could either manually append `\vskip0pt` to the `tcolorbox` content (so `\unskip` will only undo this zero-skip), or in a more dangerous way patch some internal to remove the `\unskip`.

<details><summary>Full example</summary>
<p>

```tex
\documentclass{article}
\usepackage[margin=.8in]{geometry}
\usepackage{tcolorbox,lipsum}
\usepackage{xpatch}

\makeatletter
\newcommand{\removeUnskipFromEndminipage}{%
  \makeatletter
  \xpatchcmd\endminipage
    {\unskip}
    {}
    {}{\PatchFailed}%
  \makeatother
}

\newcommand{\removeUnskipFromEndtcbsavebox}{%
  \makeatletter
  \xpatchcmd\endtcb@savebox
    {\unskip}
    {}
    {}{\PatchFailed}%
  \makeatother
}
\makeatother

\begin{document}
\fbox{\begin{minipage}[t]{.23\linewidth}
  \lipsum[1][1]
  \[1+1=2\]
\end{minipage}}
\fbox{\begin{minipage}[t]{.23\linewidth}
  \lipsum[1][1]
  \[1+1=2\] \vskip0pt
\end{minipage}}
\AddToHookNext{env/minipage/begin}{\removeUnskipFromEndminipage}%
\fbox{\begin{minipage}[t]{.23\linewidth}
  \lipsum[1][1]
  \[1+1=2\]
\end{minipage}}
\fbox{\parbox[t]{.23\linewidth}{\textbf{parbox} \lipsum[1][1]\[1+1=2\]}}

\tcbset{nobeforeafter, box align=top, width=.23\linewidth, size=small}
\begin{tcolorbox}
  \lipsum[1][1]
  \[1+1=2\]
\end{tcolorbox}
\begin{tcolorbox}[after upper=\vskip0pt]
  \lipsum[1][1]
  \[1+1=2\]
\end{tcolorbox}
\AddToHookNext{env/minipage/begin}{\removeUnskipFromEndtcbsavebox}%
\begin{tcolorbox}[after upper=\vskip0pt]
  \lipsum[1][1]
  \[1+1=2\]
\end{tcolorbox}
\end{document}
```

</p>
</details> 

![image](https://user-images.githubusercontent.com/6376638/229956893-70e0578b-9f0b-4f3a-bfc3-2d634763a39e.png)

**Comment by T-F-S** [comment]
In general, `tcolorbox` tries remove leading and trailing spaces, which sometimes is not successful (especially leading vertical skip in math is critical).
So, removing the trailing skip is the expected behaviour. @muzimuzhi listed several possibilities to stop removement. I add another example where the space is enlarged by setting `bottom=12pt` (or any other value). The example also shows the interior setup:

```latex
\documentclass{article}
\usepackage{tcolorbox,lipsum}
\tcbuselibrary{skins,raster}

\begin{document}

\begin{tcbraster}
%
\begin{tcolorbox}
\lipsum[1][1]
\[1+1=2\]
\end{tcolorbox}
%
\begin{tcolorbox}[draft]
\lipsum[1][1]
\[1+1=2\]
\end{tcolorbox}

\begin{tcolorbox}[bottom=12pt]
\lipsum[1][1]
\[1+1=2\]
\end{tcolorbox}
%
\begin{tcolorbox}[draft,bottom=12pt]
\lipsum[1][1]
\[1+1=2\]
\end{tcolorbox}
\end{tcbraster}

\end{document}
```

![grafik](https://user-images.githubusercontent.com/7982989/230013402-760a53f1-180e-489e-b2a9-c9a02e6e4d45.png)

**Comment by Alex-Jordan** [comment]
Thank you, I will close the issue.

**Comment by rbeezer** [comment]
Thanks, from PreTeXt, @muzimuzhi and @T-F-S, for your replies on this one.

We should be able to recognize when we have this situation and enact one of your suggestions.  And while I'm at it, thanks very much for `tcolorbox` - we are making very good use of it.
