### ISSUE TITLE
Why `extrude right by` doesn't alter lower part?

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#228]
The manual section 4.15.5 _Box Extrusion_ starts with a marker
https://github.com/T-F-S/tcolorbox/blob/67963e25ceb3a685c5521413eea52cb5128ddc1a/doc/latex/tcolorbox/tcolorbox.doc.coreoptions.tex#L3684-L3689

It may be hard or impossible to apply vertical extrusion to lower part or a break sequence, but why the horizontal extrusion `extrude left by` and `extrude right by` don't alter lower part as well?
https://github.com/T-F-S/tcolorbox/blob/67963e25ceb3a685c5521413eea52cb5128ddc1a/tex/latex/tcolorbox/tcolorbox.sty#L713-L714
Since the symmetric `\kvtcb@rightlower` is set by option `rightlower`, it seems to me `extrude right by=-1cm, rightlower=4mm-1cm` (using initial settings) does the work.  The related options and docs, including the marker, were added in v3.05 (https://github.com/T-F-S/tcolorbox/commit/8787eb0f236f76efc6039a697116705b063d7c7b) so I guess there really was some reason to not support lower part.  Maybe I missed some interactions between options.
```tex
\documentclass{article}
\usepackage{lipsum}
\usepackage{tcolorbox}

\makeatletter
\tcbset{
  extended extrude right by/.code={%
    \pgfkeysalso{extrude right by={#1}}%
    \tcbdimto\kvtcb@rightlower{\kvtcb@rightlower+#1}%
  }
}
\makeatother

\begin{document}
\def\dummyText{\lipsum[2][2-4]}
\def\dummyBox#1{%
  \ifstrempty{#1}{}{\dummyText}%
  \begin{tcolorbox}[IfEmptyTF={#1}{title=Default}{title=With \texttt{\detokenize{#1}}}, #1]
    \lipsum[1][1-2]
    \tcblower
    \lipsum[1][3-5]
  \end{tcolorbox}}

\dummyBox{}
\dummyBox{extrude right by=-1cm}
\dummyBox{extrude right by=-1cm, rightlower=4mm-1cm}
\dummyBox{extended extrude right by=-1cm}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/229964907-d07bad24-909f-4d33-8118-eff5e3660644.png)

In [answering](https://tex.stackexchange.com/q/681674) TeX-SX question _"How to get equation number outside of the tcolorbox?"_ I found and made use of `extrude right by`, and did an experiment to extend its effect to lower part.

**Comment by T-F-S** [comment]
Currently, I do not recall why the lower part was excluded. Maybe, the reason is not any longer valid. I will see into it with more time.

**Comment by T-F-S** [comment]
I will change the implementation of `extrude left by` and `extrude right by` to also adapt the lower part and the title. I see sensible use cases for such things and it should (hopefully) not hurt existing documents.

Examples with title and lower part which also use `extrude top by` or `extrude bottom by` are not so meaningful in my eyes and I will keep the documentation just for the upper part. But, of course, I will remove the warning to not use lower parts.

**Comment by T-F-S** [comment]
Done with https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.4
