### ISSUE TITLE
\newtcbox fails with key values containing square brackets without curly braces

### ISSUE THREAD

**Issue by Sophanatprime** [T-F-S/tcolorbox#229]
Using `\newtcbox` (and its families) with a key value that contains square brackets without curly braces causes an error. 

MWE:
```
\documentclass{article}
\usepackage{tcolorbox}
\begin{document}

\def\foo{}

\tcbset{foo/.store in=\foo}
\newtcbox{\mybox}{foo=[]}
\mybox{\foo}

\end{document}
```
I expected that `\newtcbox` would accept key values that contain square brackets without curly braces.

It turned out that when using `\newtcbox`, it internally used `\tcbox`, which could not correctly absorb its arguments.
https://github.com/T-F-S/tcolorbox/blob/67963e25ceb3a685c5521413eea52cb5128ddc1a/tex/latex/tcolorbox/tcolorbox.sty#L2306-L2332

**Comment by muzimuzhi** [comment]
The key is to change every `\tcbox[#6,options@for=#3]` to `\tcbox[{#6,options@for=#3}]` in `\__tcobox_new_tcbox_ii:w`, or define `\tcbox` through `\NewDocumentCommand` which will automatically support unbraced paired brackets used in optional argument, for example `\tcbox[foo=[]]{content}`.

TeX will strip possibly one level of brace when reading in delimited arguments. For example `\newcommand\mycmd[1]{}` and `\newcommand\mycmd[{1}]{}` do the same thing.  Thus passing values as delimited arguments of another macro must be careful.  For this reason, more places in `\__tcobox_new_tcbox_ii:w` and perhaps several other tcolorbox macros need braces.

```tex
\documentclass{article}
\usepackage{tcolorbox}
\usepackage{fvextra}

\begin{document}

\tcbset{foo/.store in=\foo, foo=}

\subsection*{Add braces to \EscVerb{\\__tcobox_new_tcbox_ii:w}}

\begingroup
\ExplSyntaxOn
\RenewDocumentCommand \__tcobox_new_tcbox_ii:w { m +m m o +o +m }
 {
   \__tcobox_process_newtcolorbox:nn { #2 }{ #3 }
   \tl_if_novalue:nTF { #4 }
     {
       \exp_args:Nc #1 { #3 }{ \tcbox[{#6,options@for={#3}}] }
     }
     {
       \tl_if_novalue:nTF { #5 }
       {
         \exp_args:Nc #1 { #3 }[ {#4} ]{ \tcbox[{#6,options@for={#3}}] }
       }
       {
         \exp_args:Nc #1 { #3 }[ {#4} ][ {#5} ]{ \tcbox[{#6,options@for={#3}}] }
       }
     }
 }
\ExplSyntaxOff

\newtcbox{\mybox}{foo=[]}
\mybox{\ttfamily\meaning\foo}
\endgroup

\subsection*{Redefine \EscVerb{\\tcbox}}

\begingroup
\ExplSyntaxOn
\makeatletter
\RenewDocumentCommand \tcbox { O +m }
  {
    \tcb@ox{capture=hbox,#1}{#2}
  }
\makeatother
\ExplSyntaxOff

\newtcbox{\mybox}{foo=[]}
\mybox{\ttfamily\meaning\foo}

\tcbox[foo=[]]{\ttfamily\meaning\foo}
\endgroup
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/233808732-81e338ac-d9cc-417f-bd66-ac22e1aece72.png)

**Comment by T-F-S** [comment]
Using `\NewDocumentCommand` for `\tcbox` would be possible, but `\NewDocumentEnvironment` could not be used for `tcolorbox` since `\tcolorbox` and `\endtcolorbox` are used (and changed) explicitely.

So, replacing `\tcbox[#6,options@for=#3]` by `\tcbox[{#6,options@for=#3}]` and similar at many places seems more appropriate, if this has no unwanted side effects. I do not see them now, but that may change with testing.

Of course, bracing square brackets `\newtcbox{\mybox}{foo={[]}}` always stays an option...

**Comment by T-F-S** [comment]
I added such a square bracket protection at several places. Should be more robust in the next version.

**Comment by T-F-S** [comment]
Done with https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.4.
Continued by issue #234
