### ISSUE TITLE
new LaTeX version introduces issue with parbox=false

### ISSUE THREAD

**Issue by mbertucci47** [T-F-S/tcolorbox#232]
The [newest LaTeX release](https://github.com/latex3/latex2e/releases/tag/release-2023-06-01) introduced an issue with the top spacing of a tcolorbox in a list environment with the setting `parbox=false` (I know, many qualifiers needed). Here's an example:
```latex
\documentclass{article}

\usepackage{tcolorbox}

\newtcolorbox{fncybox}{
	colback=yellow!2,
	colframe=yellow!90!black,
	parbox=false
	}

\begin{document}

\begin{fncybox}
some text
\end{fncybox}

\begin{enumerate}
\item abc
\begin{fncybox}
some text
\end{fncybox}
\end{enumerate}

\end{document}
```
With an older LaTeX (before 2023/06/01), the output looked like this:
![aaa-1](https://github.com/T-F-S/tcolorbox/assets/61854785/54fa2bfd-21df-4f50-b68c-c75e316f1b7f)

Now it looks like this:
![bbb-1](https://github.com/T-F-S/tcolorbox/assets/61854785/dba37a73-b079-4df8-8b2d-3ee68c79e44c)

The separation between the top of the box and the contents decreased significantly.

**Comment by muzimuzhi** [comment]
In 2023-06-01, LaTeX2e learnt to backout `\parskip` at top of `minipage` if it is due to whatsits, by replacing
```tex
  \group_begin:
    \tex_everypar:D {}
    \skip_zero:N \tex_parskip:D
    \tex_noindent:D
  \group_end:
```
with
```tex
  \group_begin:
    \tex_everypar:D {}
    \skip_set:Nn \tex_parskip:D
         { \if@minipage -\tex_parskip:D \else: \c_zero_skip \fi: }
    \tex_noindent:D
  \group_end:
```
in `\g__para_standard_everypar_tl`, see latex3/latex2e#990.

Therefore it seems the `\vspace{-\parskip}` in `\tcb@set@parbox@indent@` can be removed
https://github.com/T-F-S/tcolorbox/blob/67963e25ceb3a685c5521413eea52cb5128ddc1a/tex/latex/tcolorbox/tcolorbox.sty#L956-L959

<details><summary>An example showing differences in code level</summary>
<p>

```tex
\documentclass{article}
\usepackage{tcolorbox}

\def\test{%
  \begin{tcolorbox}[parbox=false]
    some text
  \end{tcolorbox}
  
  \begin{enumerate}
    \item abc
    \begin{tcolorbox}[parbox=false]
      some text
    \end{tcolorbox}
  \end{enumerate}
}

\begin{document}

\begingroup
\makeatletter
\IfFormatAtLeastTF{2023-06-01}{
  \def\tcb@set@parbox@indent@{%
  %  \vspace{-\parskip}%
    \noindent%
    \let\tcb@set@parbox@indent\@empty%
  }
  \let\tcb@set@parbox@indent\tcb@set@parbox@indent@
}{}
\makeatother

\textbf{\LaTeXe{} 2023-06-01}, \verb|\vspace{-\parskip}| removed from \verb|\tcb@set@parbox@indent@|
\test
\endgroup

\makeatletter
\ExplSyntaxOn
\tl_gset:Nn \g__para_standard_everypar_tl {
  \box_gset_to_last:N \g_para_indent_box
  \group_begin:
    \tex_par:D
  \group_end:
  \tex_everypar:D { \msg_error:nnnn { hooks }{ para-mode }{before}{vertical} }
  \@kernel@before@para@before
  \hook_use:n {para/before}
  \group_begin:
    \tex_everypar:D {}
    % pre 2023-06-01
    \skip_zero:N \tex_parskip:D
    % starting from 2023-06-01
    % \skip_set:Nn \tex_parskip:D
    %      { \if@minipage -\tex_parskip:D \else: \c_zero_skip \fi: }
    \tex_noindent:D
  \group_end:
  \tex_everypar:D{\g__para_standard_everypar_tl}
  \@kernel@before@para@begin
  \hook_use:n {para/begin}
  \if_mode_horizontal: \else:
    \msg_error:nnnn { hooks }{ para-mode }{begin}{vertical} \fi:
  \__para_handle_indent:
}
\cs_set:Npn \__para_tmp:w #1#2#3#4#5 { }
\tl_gput_right:Nx \g__para_standard_everypar_tl {
    \exp_not:N \the
    \exp_not:N \toks
    \exp_after:wN \__para_tmp:w \token_to_meaning:N \everypar
    \c_space_tl
}
\ExplSyntaxOff
\makeatother

\textbf{Pre 2023-06-01}
\test

\end{document}
```

</p>
</details> 

![image](https://github.com/T-F-S/tcolorbox/assets/6376638/2eb807a5-ccfb-47e5-9f96-6e3c6bc0f5c3)

**Comment by mbertucci47** [comment]
Yep that seems to be the culprit. Thanks for the debugging!

Just a note, all the tcolorboxes in your example have `parbox=false` set, even the ones containing text `parbox=true`.

**Comment by muzimuzhi** [comment]
> Just a note, all the tcolorboxes in your example have `parbox=false` set, even the ones containing text `parbox=true`.

Thank you! Example is corrected.

**Comment by T-F-S** [comment]
Thank you both for reporting and analzying / solving the problem. I will add a quite similar patch to the next version.

**Comment by T-F-S** [comment]
Resolved with https://github.com/T-F-S/tcolorbox/releases/tag/v6.0.4
