### ISSUE TITLE
About the composition of the lowerbox when lowerbox=ignored is used

### ISSUE THREAD

**Issue by fpantigny** [T-F-S/tcolorbox#240]
As far as I know, when the key `lowerbox=ignored` is used, the content of the so-called `\lowerbox` is composed in a box, even if that box is not used. That may have side effects if there are instructions with side effects in that `\lowerbox`. 

That may be a problem in particular when the key `savelowerto` is used (otherwise, the use of `\lowerbox` with `lowerbox=ignored` is rather point-less.

Maybe there would be possible to add a key to disable the composition in a TeX box of the `\lowercase`...

**Comment by fpantigny** [comment]
Here is an example.

```
\documentclass{article}
\usepackage{lipsum}
\usepackage{tcolorbox}

\newcounter{mycounter}

\begin{document}
\begin{tcolorbox}[savelowerto=\jobname-lower.tex, lowerbox=ignored]
 upper $a + b = c$ \par
 \lipsum[1][1-3]
 \tcblower
 lower $x + y = z$ \par
 \lipsum[1][4-6]
 \stepcounter{mycounter}
\end{tcolorbox}

\begin{minipage}{5cm}
  \input{\jobname-lower.tex}
\end{minipage}

\bigskip
Value of \verb|mycounter|: \arabic{mycounter}
\end{document}
```

![image](https://github.com/T-F-S/tcolorbox/assets/39270854/c238f0b0-8930-435d-9ff4-7adf8c6a9d54)

The LaTeX counter `mycounter` has been incremented twice.

**Comment by T-F-S** [comment]
It is true that the lower part is always composed into a box which is either
- drawn
- replaced by empty space (`invisible`)
- thrown away (`ignored`)

So, counters are incremented as in your example. Boxes with `fit` option are even worse since their content is typeset multiple times.

In general, it would be difficult and error-prone to change this behaviour which is part of `tcolorbox` since its beginning.

For the special case of `savelowerto`, there is a possible patch, since the lower part is saved and loaded afterwards:

```latex
\documentclass{article}
\usepackage{lipsum}
\usepackage{tcolorbox}

\makeatletter

\def\tcb@endlowerverbatimanddraw{%
  \endtcbverbatimwrite%
  \endgroup%
  \iftcb@lowerignored\else%
    \IfFileExists{\kvtcb@savelowerto}{%
      \tcb@savelowerbox\input{\kvtcb@savelowerto}\end{tcb@savebox}}{}%
  \fi%
  \tcb@draw@color@box%
  \tcb@finalize@environment%
}

\makeatother


\newcounter{mycounter}

\begin{document}
\begin{tcolorbox}[
  savelowerto=\jobname-lower.tex,
  lowerbox=ignored,
  ]
 upper $a + b = c$ \par
 \lipsum[1][1-3]
 \tcblower
 lower $x + y = z$ \par
 \lipsum[1][4-6]
 \stepcounter{mycounter}
\end{tcolorbox}

\begin{minipage}{5cm}
  \input{\jobname-lower.tex}
\end{minipage}

\bigskip
Value of \verb|mycounter|: \arabic{mycounter}
\end{document}
```

The drawback of this patch is that it has a dependency to `savelowerto`.  If  `savelowerto` is used, the counter is not increased, but otherwise it is. So, I am not sure, if this is really a good patch...

**Comment by T-F-S** [comment]
> Introducing a new choice value like `lowerbox=totally ignored` seems not solve the problem nicely, then how about a new key like `/tcb/savelowerto and ignored=<file name>` (I'm not good at names)?

Yes, this is a possibilty. Since `savelowerto and ignore` is a bit more than the combination of `savelowerto` and `lowerbox=ignored`, I looking for another wording, but, maybe, documenting is enough.

**Comment by muzimuzhi** [comment]
Other possibilities that I can think of:
- `savelowerto and totally ignore` (clearly(?) but a bit lengthy)
- `solely savelowerto` or `savelowerto solely` (the latter is closer to existing `savelowerto` but grammatically wrong(?))

**Comment by fpantigny** [comment]
A suggestion : `redirectlowerto`

**Comment by T-F-S** [comment]
> A suggestion : `redirectlowerto`

I think this could be a good name. The following code seems to work:


```latex
\documentclass{article}
\usepackage{lipsum}
\usepackage{tcolorbox}

\makeatletter

\newif\iftcb@redirectlowerto

\tcbset{
  savelowerto/.code={\tcb@redirectlowertofalse\def\kvtcb@savelowerto{#1}},
  redirectlowerto/.code={\tcb@lowerignoredtrue\tcb@lowervisiblefalse\tcb@redirectlowertotrue\def\kvtcb@savelowerto{#1}},
}

\def\tcb@endlowerverbatimanddraw{%
  \endtcbverbatimwrite%
  \endgroup%
  \iftcb@redirectlowerto\else%
    \IfFileExists{\kvtcb@savelowerto}{%
      \tcb@savelowerbox\input{\kvtcb@savelowerto}\end{tcb@savebox}}{}%
  \fi%
  \tcb@draw@color@box%
  \tcb@finalize@environment%
}

\makeatother


\newcounter{mycounter}

\begin{document}
\begin{tcolorbox}[
  %savelowerto=\jobname-lower.tex,
  %lowerbox=ignored,
  redirectlowerto=\jobname-lower.tex,
  ]
 upper $a + b = c$ \par
 \lipsum[1][1-3]
 \tcblower
 lower $x + y = z$ \par
 \lipsum[1][4-6]
 \stepcounter{mycounter}
\end{tcolorbox}

\begin{minipage}{5cm}
  \input{\jobname-lower.tex}
\end{minipage}

\bigskip
Value of \verb|mycounter|: \arabic{mycounter}
\end{document}
```

**Comment by T-F-S** [comment]
For better readability, I will do this change. Thank you.
