### ISSUE TITLE
Isolate `\tcbdocmarginnote` from `\tcbuselibrary{documentation}`

### ISSUE THREAD

**Issue by JeffFessler** [T-F-S/tcolorbox#243]
This package is wonderful and I have found`\tcbdocmarginnote` to be very useful.
But currently the only way to use it is to invoke `\tcbuselibrary{documentation}`
which seems to have other side effects like changing the way `hyperref` links are colored.
It is possible to provide a way to use `\tcbdocmarginnote` (or equivalent) without having to use the entire `documentation` library?

BTW, I tried to find the tex source code for it by searching the repo, but all I saw was places it is used, not where it is defined.
https://github.com/search?q=repo%3AT-F-S%2Ftcolorbox%20tcbdocmarginnote
Thanks!

**Comment by muzimuzhi** [comment]
`\tcbdocmarginnote` is just a styled tcolorbox wrapped in a `\marginnote`, and it's defined in [`tcbdocumentation.code.tex`](https://github.com/T-F-S/tcolorbox/blob/master/tex/latex/tcolorbox/tcbdocumentation.code.tex).

https://github.com/T-F-S/tcolorbox/blob/6d98db4263c612279cca47efde22d1ef8404e573/tex/latex/tcolorbox/tcbdocumentation.code.tex#L900-L907
