### ISSUE TITLE
Drop loading of `xparse` lib in `documentation` lib

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#254]
I think `documentation` lib only needs the `xparse` utilities already part of the LaTeX format (called the `ltcmd` module) and the main `tcolorbox` package (see #180), hence there's no need to load `xparse` lib (which will load `xparse` package) in it.

```diff
From c38ef64db2943da4847776fcdef2b661660b0988 Mon Sep 17 00:00:00 2001
From: Yukai Chou <muzimuzhi@gmail.com>
Date: Sun, 12 Nov 2023 18:42:35 +0800
Subject: [PATCH] Drop loading xparse lib in documentation lib

---
 tex/latex/tcolorbox/tcbdocumentation.code.tex | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/tex/latex/tcolorbox/tcbdocumentation.code.tex b/tex/latex/tcolorbox/tcbdocumentation.code.tex
index ecdcf95..4a4c6eb 100644
--- a/tex/latex/tcolorbox/tcbdocumentation.code.tex
+++ b/tex/latex/tcolorbox/tcbdocumentation.code.tex
@@ -19,7 +19,7 @@
 %%
 \tcb@set@library@version{6.2.0pre2}
 
-\tcbuselibrary{listings,skins,xparse,external,raster}
+\tcbuselibrary{listings,skins,external,raster}
 
 \ifdefined\printindex\else%
   \RequirePackage{makeidx}[2000/03/29]%
-- 
2.42.0

```

**Comment by T-F-S** [comment]
> I think `documentation` lib only needs the `xparse` utilities already part of the LaTeX format (called the `ltcmd` module) and the main `tcolorbox` package (see #180), hence there's no need to load `xparse` lib (which will load `xparse` package) in it.

Yes, you are right. I will remove the loading of `xparse`.

**Comment by T-F-S** [comment]
Done with https://github.com/T-F-S/tcolorbox/releases/tag/v6.2.0
