### ISSUE TITLE
`pdftexcmds` and `shellesc` packages can be replaced by expl3 functions

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#255]
The `pdftexcmds` and `shellesc` macros used by `tcolorbox` can all be simply replaced by expl3 functions and variables, thus the dependency on these two packages can be removed.

- `\pdf@shellescape` -> `\c_sys_shell_escape_int` and functions like `\sys_if_shell:TF` and `\sys_if_shell_restricted:TF`
- `\pdf@filemdfivesum` -> `\file_mdfive_hash:n`
- `\pdf@filemoddate` -> `\file_timestamp:n`
- `\pdf@strcmp` -> `\str_if_eq:eeTF`
- `\ShellEscape` -> `\sys_shell_now:e`

Currently these two packages are loaded by internal library `pro@cessing`, which is loaded by `external`, `listings`, `listingsutf8`, and `minted` libraries.
https://github.com/T-F-S/tcolorbox/blob/18aecbbacc61445c178c3e9a35cadc588b3665bf/tex/latex/tcolorbox/tcbprocessing.code.tex#L22-L23

A minimal change would be to provide `\tcb@...` wrappers around these expl3 names.

A larger change is to use expl3 names directly and rewrite relevant codes in expl3, see https://github.com/muzimuzhi/tcolorbox/pull/1 for what I've tried.

BTW, the guards for undefined `\pdf@filemdfivesum` and `\pdf@filemoddate` in xelatex can be removed, since `pdftexcmds` already defines these in xelatex, see https://github.com/muzimuzhi/tcolorbox/pull/1#issuecomment-1808465339.

https://github.com/T-F-S/tcolorbox/blob/18aecbbacc61445c178c3e9a35cadc588b3665bf/tex/latex/tcolorbox/tcbprocessing.code.tex#L25-L30

**Comment by T-F-S** [comment]
> The `pdftexcmds` and `shellesc` macros used by `tcolorbox` can all be simply replaced by expl3 functions and variables, thus the dependency on these two packages can be removed.

Replacing these macros by expl3 code makes sense. Thank you for the suggestion and also for the linked code. I will put this on my todo list, but this may take some time.

**Comment by T-F-S** [comment]
Done with https://github.com/T-F-S/tcolorbox/releases/tag/v6.2.0
