### ISSUE TITLE
Contents in a scalebox is mispositioned with dvipdfmx

### ISSUE THREAD

**Issue by mac-wac** [T-F-S/tcolorbox#26]
Hi. Thanks for the nice package.

Contents of tcolorbox seem to be mispositioned when they are in scalebox and dvipdfmx are used.

    \documentclass{article}
    \usepackage[dvipdfmx]{graphicx}
    \usepackage{tcolorbox}
    
    \begin{document}
    \begin{tcolorbox}
    \scalebox{.8}{Contents seems to be mispositioned...}
    \end{tcolorbox}
    \end{document}`

![mispositioned](https://cloud.githubusercontent.com/assets/2494662/26759864/898e4ecc-4945-11e7-83b6-4d72c214091a.png)

With pdfTeX, there seems nothing wrong. (I'd like to use dvipdfmx because I always use pTeX, a TeX engine for Japanese.)

Here shows my environments:
- latex: both pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian) and e-pTeX 3.14159265-p3.7-160201-2.6 (utf8.euc) (TeX Live 2016/Debian)
- dvipdfmx: 20160307
- graphicx: 2014/10/28 v1.0g
- tcolorbox: 3.96 (2016/11/18).

**Comment by T-F-S** [comment]
I cannot test your example, because I do not have pTeX installed on my system.

`tcolorbox` relies on `pgf` / `tikz`. I found the following on page 123 of the manual for `pgf` that might help:

```latex
\documentclass{article}
\usepackage[dvipdfmx]{graphicx}
\def\pgfsysdriver{pgfsys-dvipdfm.def}% <---- pgf manual page 123
\usepackage{tcolorbox}

\begin{document}
\begin{tcolorbox}
\scalebox{.8}{Contents seems to be mispositioned...}
\end{tcolorbox}
\end{document}
```

I cannot test this. Let me know, if this code works with pTeX. 

If it does not work, I fear I'm out of ideas ...

**Comment by mac-wac** [comment]
Thank you very much. Your idea works completely well!
