### ISSUE TITLE
Cite LaTeX `usrguide` as doc for `\NewDocumentCommand` and friends

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#263]
Since [v5.1.0](https://github.com/T-F-S/tcolorbox/releases/tag/v5.1.0), code in `xparse` library "was migrated to other parts of the `tcolorbox` package" (see #180), so users will see mentions to `\NewDocumentCommand`, `\NewDocumentEnvironments`, and their friends throughout the `tcolorbox` manual.

Before, these mentions appear only in doc section for `xparse` library, which cited the `xparse` package manual at its beginning.

As these commands are relatively young to the LaTeX kernel, I'm afraid that they are not covered by most introductory LaTeX resources. Maybe it worth citing LaTeX's `usrguide` in places where `\NewDocumentCommand` and `\NewDocumentEnvironment` are mentioned at first time (in docs for `\NewTotalTColorBox` and `\NewTColorBox`, respectively), and in `xparse` library doc.

```bib
@manual{latexproject:usrguide,
   author    = {The \LaTeX{} Project Team},
   title     = {{\LaTeX} for authors --- current version},
   url       = {https://mirrors.ctan.org/macros/latex/base/usrguide.pdf},
   date      = {2023-05-23},
}
```

PS: Came up with this idea when I was viewing changes to [`tcolorbox.doc.bib`](https://github.com/T-F-S/tcolorbox/commit/067f384e2ba85ba3fd91958eb6adb8a1bcea6c29#diff-2693e7bee3b4af7a56013796ec7def80f1dc80d6a0b24d4213ba3ec2fca701ad) in commit 067f384 (6.2.0, 2024-01-10).

**Comment by T-F-S** [comment]
> As these commands are relatively young to the LaTeX kernel, I'm afraid that they are not covered by most introductory LaTeX resources. Maybe it worth citing LaTeX's `usrguide` in places where `\NewDocumentCommand` and `\NewDocumentEnvironment` are mentioned at first time (in docs for `\NewTotalTColorBox` and `\NewTColorBox`, respectively), and in `xparse` library doc.

Yes, I think such a citation is useful. Thank you - I will add this to the documentation.

**Comment by T-F-S** [comment]
Done with https://github.com/T-F-S/tcolorbox/releases/tag/v6.3.0
