### ISSUE TITLE
"Undefined control sequence" when loading tcolorbox-6.2.0

### ISSUE THREAD

**Issue by dbuscher** [T-F-S/tcolorbox#267]
With the MWE below I get an "Undefined control sequence" error when loading the 6.2.0 release whereas if I replace it with 6.1.0 it compiles without error.

MWE (test2.tex):
\documentclass{article}
\def\tcbpkgprefix{tcolorbox-6.2.0/tex/latex/tcolorbox/}
\usepackage{\tcbpkgprefix tcolorbox}
\begin{document}
hello
\end{document}

pdflatex output:

This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./test2.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-02-22>
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/base/size10.clo))
(./tcolorbox-6.2.0/tex/latex/tcolorbox/tcolorbox.sty

LaTeX Warning: You have requested package `tcolorbox-6.2.0/tex/latex/tcolorbox/
tcolorbox',
               but the package provides `tcolorbox'.

(/usr/local/texlive/2023basic/texmf-dist/tex/latex/pgf/basiclayer/pgf.sty
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/pgf/utilities/pgfrcs.sty
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/utilities/pgfutil-comm
on.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/utilities/pgfutil-late
x.def)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/utilities/pgfrcs.code.
tex (/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/pgf.revision.tex))
) (/usr/local/texlive/2023basic/texmf-dist/tex/latex/pgf/basiclayer/pgfcore.sty
 (/usr/local/texlive/2023basic/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/pgf/systemlayer/pgfsys.sty
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/systemlayer/pgfsys.cod
e.tex
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code
.tex
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/utilities/pgfkeyslibra
ryfiltered.code.tex))
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/systemlayer/pgf.cfg)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-pdf
tex.def
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-com
mon-pdf.def)))
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/systemlayer/pgfsyssoft
path.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/systemlayer/pgfsysprot
ocol.code.tex))
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/graphics/mathcolor.ltx))
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcore.cod
e.tex
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/math/pgfmathutil.code.
tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/math/pgfmathparser.cod
e.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
basic.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
trigonometric.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
random.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
comparison.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
base.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
round.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
misc.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.
integerarithmetics.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/math/pgfmathcalc.code.
tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/math/pgfmathfloat.code
.tex))
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/math/pgfint.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepoin
ts.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepath
construct.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepath
usage.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorescop
es.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoregrap
hicstate.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretran
sformations.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorequic
k.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreobje
cts.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepath
processing.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorearro
ws.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreshad
e.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreimag
e.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreexte
rnal.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorelaye
rs.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretran
sparency.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepatt
erns.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/basiclayer/pgfcorerdf.
code.tex)))
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/modules/pgfmoduleshape
s.code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/generic/pgf/modules/pgfmoduleplot.
code.tex)
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-ve
rsion-0-65.sty)
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-ve
rsion-1-18.sty))
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/tools/verbatim.sty)
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/environ/environ.sty
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/trimspaces/trimspaces.sty))
(/usr/local/texlive/2023basic/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
! Undefined control sequence.
\__tcobox_set_backslash_removed:Nn ...1\tl_set:Ne 
                                                  #1{\exp_last_unbraced:NV \...
l.2522 \DeclareTotalTCBox{\tcboxverb}
                                     { O{} v }{verbatim,#1}{#2}
?

**Comment by muzimuzhi** [comment]
> LaTeX2e <2022-11-01> patch level 1
> L3 programming layer <2023-02-22>
> ...
> ! Undefined control sequence.
> __tcobox_set_backslash_removed:Nn ...1\tl_set:Ne
> #1{\exp_last_unbraced:NV ...
> l.2522 \DeclareTotalTCBox{\tcboxverb}
> { O{} v }{verbatim,#1}{#2}
> ?

`\tl_set:Ne` needs l3kernel (aka, the L3 programming layer) 2023-06-05 (added in commit e34ece41 (Extend pre-defined variants, 2023-05-24)), while you only have 2023-02-22 installed. Note l3kernel uses dates (YYYY-MM-DD) as version.

Try this:
```tex
\ExplSyntaxOn
\cs_generate_variant:Nn \tl_set:Nn { Ne }
\ExplSyntaxOff
\documentclass{article}
\def\tcbpkgprefix{tcolorbox-6.2.0/tex/latex/tcolorbox/}
\usepackage{\tcbpkgprefix tcolorbox}
\begin{document}
hello
\end{document}
```

In case there're other variants that's only available in newer versions of l3kernel, I would recommend upgrading both LaTeX2e and l3kernel to the latest versions, if there're no particular reason to stick to your current combinations (LaTeX2e 2022-11-01 PL 1 + l3kernel 2023-02-22).

**Comment by dbuscher** [comment]
Thanks, your new example works for me. 

It may be difficult for me to upgrade Latex2e and the l3kernel as I am using Homebrew basictex on MacOS. My impression is that this only gets upgraded once a year for the new texlive version. Is it possible to use tlmgr to change the basic latex engines between texlive releases?

**Comment by muzimuzhi** [comment]
> Is it possible to use tlmgr to change the basic latex engines between texlive releases?

Definitely yes, from an other basictex user.

```bash
# check all updates
tlmgr update --list
# update latex2e kernel and its dependencies
sudo tlmgr update --self latex l3kernel l3backend
```

**Comment by dbuscher** [comment]
Works! I later had to do 
```
sudo tlmgr update -all
```
to get more complex examples to work, as all the other packages such as amsmath need to be updated to work with the new engine.

**Comment by T-F-S** [comment]
I updated the needed LaTeX version for 6.2.0 to 2021-11-15. The idea was to upgrade, but slowly, so that users typically do not need to update their LaTeX kernel before the do for other reasons.
Obviously, this was too reluctant.

For the next version, the needed LaTeX version will become 2023-11-01, so users get clearer feedback during compilation than `Undefined control sequence`:

```LaTeX
\NeedsTeXFormat{LaTeX2e}[2023-11-01]
```

**Comment by dbuscher** [comment]
Thanks for adding this warning about the needed LaTeX version, this will save other users time in the future. Having received this warning, those who cannot upgrade their LaTeX engine may still be left with a problem, though, as it is not straightforward to install an earlier version of the package. Perhaps the overlap of those who can only easily install the most recent version of a package and those who cannot upgrade their LaTeX engine is small?

**Comment by muzimuzhi** [comment]
I managed to run `tcolorbox` v6.2.0 plus `tikzfill` v1.0.1 with LaTeX2e 2022-11-01 in a TeX Live 2022 docker image, see https://github.com/muzimuzhi/hello-github-actions/pull/27.

Luckily, `\tl_set:Ne` is the only missing variant.

```tex
\RequirePackage[enable-debug]{expl3}
\ExplSyntaxOn
\debug_on:n { check-declarations, check-expressions, deprecation }
\cs_generate_variant:Nn \tl_set:Nn { Ne }
\ExplSyntaxOff

\PassOptionsToPackage{draft}{minted} # comment this line if "pygmentize" is available
\documentclass{article}
\usepackage[all]{tcolorbox}
\listfiles

\begin{document}
content
\end{document}
```

Although LaTeX2e kernel provides some sort of rollback through `latexrelease` package, the l3kernel/expl3 part has no way back. Thus LaTeX 2023-11-01 provided new command `\IfExplAtLeastTF{<date>}{<true>}{<false>}`, similar to the existing `\IfFormatAtLeastTF`.

**Comment by T-F-S** [comment]
Needed LaTeX version updated to 2023-11-01 in https://github.com/T-F-S/tcolorbox/releases/tag/v6.3.0
