### ISSUE TITLE
Typo in manual

### ISSUE THREAD

**Issue by tweh** [T-F-S/tcolorbox#27]
In sec. 21.4, p. 422 it reads

![tcolorbox pdf seite 422 von 480 2017-06-19 16-07-23](https://user-images.githubusercontent.com/3011538/27289202-63b821a8-5509-11e7-98da-4045ef500d9c.png)

But it’s the `xparse` library that is required for these macros …

**Comment by T-F-S** [comment]
Actually, the `listings` library is correct here. Chapter 21 describes the `xparse` library, but you also need `listings` for sec. 21.4.

Nevertheless, I will clarify this inside the documentation:

**Besides `xparse`, the following commands also need the `listings` library to be included.**

**Comment by tweh** [comment]
Sounds good :-) because a document doesn't compile when only `listings` is loaded but `xparse` not and `\NewTCBListing` is used …
