### ISSUE TITLE
decreased space before list with parbox=false following a section heading

### ISSUE THREAD

**Issue by mbertucci47** [T-F-S/tcolorbox#270]
Sorry for adding to the list of issues with `parbox=false`, but I think with the fix for #262 a new issue has appeared. If a tcolorbox with `parbox=false` comes immediately after a section heading, then the space before a list that's preceded by text is decreased. Here's an example showing the issue:
```tex
\documentclass{article}
\usepackage{tcolorbox}

\begin{document}

\section{A section}

% too little space
\begin{tcolorbox}[parbox=false]
Some text
\begin{enumerate}
	\item First item 
    \item Second item 
\end{enumerate}
\end{tcolorbox}

% good
\begin{tcolorbox}[parbox=false]
Some text
\begin{enumerate}
	\item First item 
    \item Second item 
\end{enumerate}
\end{tcolorbox}

\subsection{A subsection}

% too little space
\begin{tcolorbox}[parbox=false]
Some text
\begin{enumerate}
	\item First item 
    \item Second item 
\end{enumerate}
\end{tcolorbox}

% good
\begin{tcolorbox}[parbox=false]
Some text
\begin{enumerate}
	\item First item 
    \item Second item 
\end{enumerate}
\end{tcolorbox}

% starting with a list is fine
\section{Another section}

\begin{tcolorbox}[parbox=false]
\begin{enumerate}
	\item First item 
    \item Second item 
\end{enumerate}
\end{tcolorbox}

\begin{tcolorbox}[parbox=false]
\begin{enumerate}
	\item First item 
    \item Second item 
\end{enumerate}
\end{tcolorbox}

\end{document}
```
![document-1](https://github.com/T-F-S/tcolorbox/assets/61854785/ee0b3450-6cc3-4c5d-aa70-82e103740975)

There's no issue with boxes that start with a list.

**Comment by muzimuzhi** [comment]
Using overleaf (use `\csname ver@tcolorbox.sty\endcsname` to typeset version of `tcolorbox`), 
- texlive 2023 (tcolorbox v6.0.4), reproducible
- texlive 2022 (tcolorbox v5.1.1), reproducible
- texlive 2021 (tcolorbox v4.51), not reproducible (the spacing above first list is still  relatively narrower)
- texlive 2020 (tcolorbox v4.30), not reproducible (ibid)

**Comment by muzimuzhi** [comment]
I don't know why but prepending `\let\if@nobreak\iffalse` (which is the first assignment in `\@arrayparboxrestore`) to `\tcb@parbox@false@settings` seems to work.

Still need to find the "why part".

<details><summary>Example v2</summary>
<p>

```tex
\documentclass{article}
\usepackage[skins]{tcolorbox}

\makeatletter
\preto\tcb@parbox@false@settings{\let\if@nobreak\iffalse}
\makeatother

\newcommand\test[1][]{%
  \begin{tcolorbox}[#1, draft]
    Some text
    \begin{enumerate}
    	\item First item 
      \item Second item
    \end{enumerate}
  \end{tcolorbox}
}

\begin{document}
LaTeX2e \fmtversion\par
tcolorbox \csname ver@tcolorbox.sty\endcsname

\section{parbox=false}
\test[parbox=false]

\test[parbox=false]

\section{parbox=true}
\test[parbox=true]

\test[parbox=true]
\end{document}
```

</p>
</details> 

![image](https://github.com/T-F-S/tcolorbox/assets/6376638/c5741cb1-7183-40b3-9a48-2fe59f8e93ad)

**Comment by T-F-S** [comment]
> I don't know why but prepending `\let\if@nobreak\iffalse` (which is the first assignment in `\@arrayparboxrestore`) to `\tcb@parbox@false@settings` seems to work.
> 
> Still need to find the "why part".

I also wonder why the `nobreak` setting disturbs at this point.

Nevertheless, adding `\let\if@nobreak\iffalse` or `\@nobreakfalse` to `\tcb@parbox@false@settings` should do no harm and makes sense. If `parbox=true` is used, `\if@nobreak` equals `\iffalse` at begin of the tcolorbox interior of the MWE, but `\iftrue` for `parbox=false`.

So, I will add `\@nobreakfalse` to `\tcb@parbox@false@settings`.

**Comment by T-F-S** [comment]
Fixed with https://github.com/T-F-S/tcolorbox/releases/tag/v6.3.0
