### ISSUE TITLE
New environment like `valuelist` (from `ltxdockit` package)

### ISSUE THREAD

**Issue by matteofg** [T-F-S/tcolorbox#275]
I am aware that, in the author's intentions, `documentation library` “is assumed to be used in conjunction with the class ltxdoc or alike“ (_The tcolorbox package_, p. 492).
However, in the simplest cases, using the library alone is more than sufficient.

Imho a `valuelist`-like environment (`ltxdockit` package) is missing to describe the various _values_ of a _key_ option.

<details>
<summary>Belowe a mwe</summary>

```tex
\documentclass{article}
\usepackage{ltxdockit}
\usepackage{lipsum}

\begin{document}

\begin{optionlist}
\optitem[alpha]{foo}{\opt{alpha}, \opt{beta}, \opt{gamma}}
\lipsum[1][1]
\begin{valuelist}
\item[alpha] \lipsum[2][1-4]
\item[beta] \lipsum[3][1-3]
\item[gamma] \lipsum[4][1-2]
\end{valuelist}
\end{optionlist}

\end{document}
```
</details>
<img width="665" alt="Screenshot 2024-03-28 at 17 20 25" src="https://github.com/T-F-S/tcolorbox/assets/111273603/4080c60d-9c51-458f-b6ee-1b179f08d530">

**Comment by T-F-S** [comment]
Currently, there is no such environment. A value list is made manually, for example (from the documentation):

```latex
  Feasible values for \meta{part} are:
  \begin{itemize}
  \item\docValue{broken}: all broken box parts,
  \item\docValue{unbroken}: unbroken boxes only,
  \item\docValue{first}: first parts of a break sequence,
  \item\docValue{middle}: middle parts of a break sequence,
  \item\docValue{last}: last parts of a break sequence,
  \item\docValue{unbroken and first}: unbroken boxes and first parts of a break sequence,
  \item\docValue{middle and last}: middle and last parts of a break sequence.
  \item\docValue{first and middle}: first and middle parts of a break sequence.
  \end{itemize}
```
![grafik](https://github.com/T-F-S/tcolorbox/assets/7982989/ab2f4c9d-088a-4aec-bcef-ed8a0789d874)

With a new environment `tcbvaluelist`, we could have the same output with code like
```latex
  Feasible values for \meta{part} are:
  \begin{tcbvaluelist}
  \item[broken] all broken box parts,
  \item[unbroken] unbroken boxes only,
  \item[first] first parts of a break sequence,
  \item[middle] middle parts of a break sequence,
  \item[last] last parts of a break sequence,
  \item[unbroken and first] unbroken boxes and first parts of a break sequence,
  \item[middle and last] middle and last parts of a break sequence.
  \item[first and middle] first and middle parts of a break sequence.
  \end{tcbvaluelist}
```

There is no problem in providing such an environment, but I fear, users would demand for customization. And I do not want to re-invent all sorts of `itemize` customizations just to have a value list... Therefore, I hesitate to add such an environment. Nevertheless, I keep this for further thinking.

**Comment by T-F-S** [comment]
> OK, thanks for the explanations.
> For me the issue may as well be closed.

OK, I close it to tidy up the issue list. Anyhow, thanks for providing ideas for improvement.
