### ISSUE TITLE
More meaningful error message in case of `\Declare(d)TColorBox`(es) with same name and both with `auto counter`

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#276]
The following MCE:
```latex
\documentclass{article}
\usepackage{tcolorbox}
\DeclareTColorBox[auto counter]{pabox}{}{}
\DeclareTColorBox[auto counter]{pabox}{}{}
\begin{document}
\end{document}
```
fails to compile with the following cryptic message:

> ! LaTeX Error: Command \c@tcb@cnt@pabox already defined.
               Or name \end... illegal, see p.192 of the manual.

Maybe it is worth to provide a more meaningful message in such a case.

**Comment by muzimuzhi** [comment]
The error was raised by `\newcounter{<conter name>}` on an existing `<counter name>`. Not sure if it's feasible for LaTeX2e to make that general message more specific for counters.

Possible patch on `tcolorbox` side
```tex
\documentclass{article}
\usepackage{tcolorbox}

\makeatletter
\def\tcb@proc@counter@auto#1{%
  %% begin patch
  \ifcsdef{c@tcb@cnt@#1}
    {\tcb@error{Auto counter for environment '#1' already defined}{}}
    {}%
  %% end patch
  \newcounter{tcb@cnt@#1}%
  \csxdef{tcb@cnt@#1}{tcb@cnt@#1}%
  \tcb@proc@counter@autoanduse{#1}%
}
\makeatother

\DeclareTColorBox[auto counter]{pabox}{}{}
\DeclareTColorBox[auto counter]{pabox}{}{}
\begin{document}
\end{document}
```

Now compile it will throw two errors
```
! Package tcolorbox Error: Auto counter for environment 'pabox' already defined
.

! LaTeX Error: Command \c@tcb@cnt@pabox already defined.
               Or name \end... illegal, see p.192 of the manual.
```

**Comment by T-F-S** [comment]
I think this is a useful patch and I will add it to the next version. Thank you.

**Comment by T-F-S** [comment]
Done with https://github.com/T-F-S/tcolorbox/releases/tag/v6.3.0
