### ISSUE TITLE
Optional argument with \newtcblisting

### ISSUE THREAD

**Issue by tweh** [T-F-S/tcolorbox#28]
There seems to be a parsing error when defining a listing with an optional argument.

```latex
\documentclass{article}

\usepackage{tcolorbox}
   \tcbuselibrary{minted}
   \tcbuselibrary{skins}
   \tcbuselibrary{xparse}

\newtcblisting{code}[1][]{
   #1,
}


\begin{document}
\begin{code}
\section[Demo]{Long demo}
\end{code}
\begin{code}[]
\section[Demo]{Long demo}
\end{code}
\end{document}
```

![tcb_bug pdf seite 1 von 1 2017-06-19 16-10-44](https://user-images.githubusercontent.com/3011538/27289336-de285b38-5509-11e7-8e88-8b5e6a084ade.png)

Seems like, when the code contains brackets, they somehow got absorbed in a strange way. This can be prevented by providing empty brackets after the environment begin, or by using `\DeclareTCBListing{code}{ O{} }{#1}` instead.

**Comment by T-F-S** [comment]
Yes, this is known and documented on page 299:

![caveat](https://user-images.githubusercontent.com/7982989/27323840-5185a0c4-55a3-11e7-9c9e-639e48a4ea46.png)

But, anyway, thank you for the hint.

**Comment by tweh** [comment]
Sorry … I just skimmed the manual and overhead that O:-) Maybe you could just drop the possibility to generate an optional argument with `\newtcblisting` completly to avoid problems/confusion …

**Comment by T-F-S** [comment]
The problem only occurs for environments with an optional argument WITHOUT any mandatory argument. If there is at least one mandatory argument, everything should/will work fine.

**Comment by tweh** [comment]
Ah … I see. Then of course everything should stay as is :-)
