### ISSUE TITLE
breakable option and tcbdocmarginnote / tcolorbox inside of marginnote

### ISSUE THREAD

**Issue by mkm-gh** [T-F-S/tcolorbox#281]
When using the breakable option in a margin note (tcbdocmarginnote or tcolorbox inside of marginnote) and the box is „pushed“ to a new page, the layout is broken. Please see the minimal example below.

This may be related to the known issues of the `marginnote` package.

```
\documentclass{article}

\usepackage{lipsum}

\usepackage{marginnote}

\usepackage[most]{tcolorbox}
%\usepackage[most,documentation]{tcolorbox}

\begin{document}

\lipsum[1-5]

%\clearpage % This dirty fix resolves the issue

\section{A}
Text
\marginnote{\begin{tcolorbox}[breakable] % breakable causes the problem
A
\end{tcolorbox}}
Text

% The following is also broken

%\section{A}
%Text
%\tcbdocmarginnote[breakable]{ % breakable causes the problem
%A
%}
%Text

\end{document}
```

**Comment by muzimuzhi** [comment]
According to package manual of `marginnote`, sec. 2 Issues Using `marginnote`:

> No page break can occur within a margin note created using the `\marginnote` command.

So using breakable `tcolorbox` in `\marginnote` is meaningless. The broken layout may be caused by wrong detection of remaining page height triggered by `breakable` option.
