### ISSUE TITLE
Tagging support in tcolorbox: suppress tagging of "drawing"

### ISSUE THREAD

**Issue by u-fischer** [T-F-S/tcolorbox#283]
We just got an issue about a tagging problem involving tcolorbox. As tcolorbox is an important package used in various places it would be nice if it could start to add support for tagging.  This can not be done in one go, at first because tcolorbox is quite complex, but also because most code in LaTeX is still only in latex-lab and so rather experimental. 

But one thing is imho now possible if a current format is used: We added there commands to suspend tagging in some places, and it would imho help a lot if tcolorbox would use that to suspend tagging when drawing skins:

~~~~
\ExplSyntaxOn\makeatletter
\NewSocket{tagsupport/tcb/drawing/begin}{0}
\NewSocket{tagsupport/tcb/drawing/end}{0}
\NewSocketPlug{tagsupport/tcb/drawing/begin}{suspend}
 {\tag_mc_end_push:\tag_mc_begin:n{artifact}}
\NewSocketPlug{tagsupport/tcb/drawing/end}{resume}
 {\tag_mc_end:\tag_mc_begin_pop:n{}}
\AssignSocketPlug{tagsupport/tcb/drawing/begin}{suspend} 
\AssignSocketPlug{tagsupport/tcb/drawing/end}{resume}


\def\tcb@drawing@env@begin{%
  \csname tcb@before@\tcb@split@state\endcsname%
  \UseTaggingSocket{tcb/drawing/begin}\SuspendTagging{tcb/drawing}%
  \begin{\kvtcb@graphenv}%
  \tcb@bbdraw%
  \tcb@apply@graph@patches%
}

\def\tcb@drawing@env@end{%
  \end{\kvtcb@graphenv}%
 \ResumeTagging{tcb/drawing}\UseTaggingSocket{tcb/drawing/end}%
  \csname tcb@after@\tcb@split@state\endcsname%
}                         
~~~~

The exact placement of the additional code in `\tcb@drawing@env@begin` and `\tcb@drawing@env@end` should consider that with pdflatex tagging inserts literals and so can affect spacing. I do not know the tcolorbox code well enough to know if that matters here.

A full example is at https://github.com/latex3/tagging-project/issues/88#issuecomment-2196556521

**Comment by T-F-S** [comment]
I understand that the tagging project aims to conform to some PDF standards. Unfortunately, I see no difference between well-formed and other PDF documents with my readers (SumatraPDF and Acrobat Reader). Which tools or readers would display the generated tags?

Inserting literals before or after drawing would be potentially critical. Could the tagging suppression be moved inside the graphical environment, typically `tikzpicture`?

```latex
\ExplSyntaxOn\makeatletter
\NewSocket{tagsupport/tcb/drawing/begin}{0}
\NewSocket{tagsupport/tcb/drawing/end}{0}
\NewSocketPlug{tagsupport/tcb/drawing/begin}{suspend}
 {\tag_mc_end_push:\tag_mc_begin:n{artifact}}
\NewSocketPlug{tagsupport/tcb/drawing/end}{resume}
 {\tag_mc_end:\tag_mc_begin_pop:n{}}
\AssignSocketPlug{tagsupport/tcb/drawing/begin}{suspend}
\AssignSocketPlug{tagsupport/tcb/drawing/end}{resume}


\def\tcb@drawing@env@begin{%
  \csname tcb@before@\tcb@split@state\endcsname%
  \begin{\kvtcb@graphenv}%
  \UseTaggingSocket{tcb/drawing/begin}\SuspendTagging{tcb/drawing}%
  \tcb@bbdraw%
  \tcb@apply@graph@patches%
}

\def\tcb@drawing@env@end{%
  \ResumeTagging{tcb/drawing}\UseTaggingSocket{tcb/drawing/end}%
  \end{\kvtcb@graphenv}%
  \csname tcb@after@\tcb@split@state\endcsname%
}
\makeatother\ExplSyntaxOff
```

As said, I fly completely blind here: The example from https://github.com/latex3/tagging-project/issues/88 looks the same to me with and without the modifications...

**Comment by T-F-S** [comment]
> Which tools or readers would display the generated tags?

Googling gives that Adobe Reader does not support tagging. One seems to need Adobe Acrobat Pro to benefit from tagging...

**Comment by u-fischer** [comment]
Adobe reader does support tagging, but doesn't show the tags. Adobe Acrobat is an option but naturally costs money. Free alternatives are pdf xchange, pdfix, and also (for windows) the newest PAC PAC 2024.2.1 beta (a checker, 
https://pac.pdf-accessibility.org/de/herunterladen).

> Inserting literals before or after drawing would be potentially critical. Could the tagging suppression be moved inside the graphical environment, typically tikzpicture?

One would have to test that. The main question is if it will clash with potential tagging of tikzpictures in general.  If there is no good place in vmode before and after the drawing (e.g. where color specials are anyway), the best would be just after a \leavevmode before the actual tikzpicture. 

I can naturally check examples if you have some!

**Comment by T-F-S** [comment]
Thank for hinting me to the testing tools. I installed pdfix and PAC. With PAC, there seems to be no difference, if the suppressing is inside or outside of `tikzpicture`. The modified example is

```latex
\DocumentMetadata{
  lang        = de,
  pdfversion  = 2.0,
  pdfstandard = ua-2,
  pdfstandard = a-4f,
  testphase   =
   {phase-III,
    title,
    table
    firstaid},
  uncompress,
}

\tagpdfsetup{tabsorder=structure}

\documentclass[]{article}

\usepackage[]{hyperref}

\usepackage[dvipsnames,svgnames]{xcolor}

\definecolor{giBlue}{RGB}{14,32,80}
\definecolor{giYellow}{RGB}{255,230,0}
\definecolor{giLightYellow}{RGB}{255,242,204}
\definecolor{giGray}{RGB}{74,74,74}

\usepackage[many]{tcolorbox}

\ExplSyntaxOn\makeatletter
\NewSocket{tagsupport/tcb/drawing/begin}{0}
\NewSocket{tagsupport/tcb/drawing/end}{0}
\NewSocketPlug{tagsupport/tcb/drawing/begin}{suspend}
 {\tag_mc_end_push:\tag_mc_begin:n{artifact}}
\NewSocketPlug{tagsupport/tcb/drawing/end}{resume}
 {\tag_mc_end:\tag_mc_begin_pop:n{}}
\AssignSocketPlug{tagsupport/tcb/drawing/begin}{suspend}
\AssignSocketPlug{tagsupport/tcb/drawing/end}{resume}


\def\tcb@drawing@env@begin{%
  \csname tcb@before@\tcb@split@state\endcsname%
  \begin{\kvtcb@graphenv}%
  \UseTaggingSocket{tcb/drawing/begin}\SuspendTagging{tcb/drawing}%
  \tcb@bbdraw%
  \tcb@apply@graph@patches%
}

\def\tcb@drawing@env@end{%
  \ResumeTagging{tcb/drawing}\UseTaggingSocket{tcb/drawing/end}%
  \end{\kvtcb@graphenv}%
  \csname tcb@after@\tcb@split@state\endcsname%
}
\makeatother\ExplSyntaxOff

\newcommand{\prozessInhaltsBox}[3][4mm]{%
    \par\medskip\vspace{1pt}\vspace{#1}\noindent
    \begin{tcolorbox}[%
                               width=\textwidth/2-4mm,
                               colback=white,
                               colframe=giBlue!0!giYellow,
                               arc=0mm,
				title={Titel 1},
                               fonttitle=\color{black},
				enhanced jigsaw,
				grow sidewards by=2mm,
				borderline={4mm}{-4mm}{giGray!5!white},
				sharp corners=all,
				borderline={0.5pt}{0pt}{giYellow},
				nobeforeafter,
				equal height group=grp1,
			]
        \begin{itemize}% removed optional argument to be able to test without tagging!
            #2
        \end{itemize}
		\end{tcolorbox}%
        \hspace{8mm}%
		\begin{tcolorbox}[%
                              width=\textwidth/2-4mm,
                              colback=white,
                              colframe=giBlue!0!giYellow,
                              arc=0mm,
			    title={Titel 2},
                                fonttitle=\color{black},
				enhanced jigsaw,
				grow sidewards by=2mm,
				borderline={4mm}{-4mm}{giGray!5!white},
				sharp corners=all,
				borderline={0.5pt}{0pt}{giYellow},
				nobeforeafter,
				equal height group=grp1,
      ]
        \begin{itemize}
            #3
        \end{itemize}
    \end{tcolorbox}
    \par
}

\begin{document}


\prozessInhaltsBox{
    \item[MI]{Items}
}{
    \item[ID]{Auch mal längere Items}
}

\end{document}
```

The test gives:

![grafik](https://github.com/T-F-S/tcolorbox/assets/7982989/9d509f5d-9a28-42ff-8f09-3ca9dfb6ddb6)

It is the same as for suppressing outside `tikzpicture`.

Are there any considerations to suppress tagging inside a `tikzpicture` as a pdf package feature?

**Comment by T-F-S** [comment]
I made another test using your original suggestion with breakable boxes. Unfortunately, it seems to be not compatible, producing errors like:

> Package tagpdf Warning: there is no mc to end at 17
> 
> ! Package tagpdf Error: there is no open structure on the stack

The example code is:

```latex
\DocumentMetadata{
  lang        = de,
  pdfversion  = 2.0,
  pdfstandard = ua-2,
  pdfstandard = a-4f,
  testphase   =
  {
    phase-III,
    title,
    table
    firstaid
  },
  uncompress,
}

\tagpdfsetup{tabsorder=structure}

\documentclass[]{article}

\usepackage{lipsum}
\usepackage[many]{tcolorbox}

\ExplSyntaxOn\makeatletter
\NewSocket{tagsupport/tcb/drawing/begin}{0}
\NewSocket{tagsupport/tcb/drawing/end}{0}
\NewSocketPlug{tagsupport/tcb/drawing/begin}{suspend}
 {\tag_mc_end_push:\tag_mc_begin:n{artifact}}
\NewSocketPlug{tagsupport/tcb/drawing/end}{resume}
 {\tag_mc_end:\tag_mc_begin_pop:n{}}
\AssignSocketPlug{tagsupport/tcb/drawing/begin}{suspend}
\AssignSocketPlug{tagsupport/tcb/drawing/end}{resume}


\def\tcb@drawing@env@begin{%
  \csname tcb@before@\tcb@split@state\endcsname%
  \UseTaggingSocket{tcb/drawing/begin}\SuspendTagging{tcb/drawing}%
  \begin{\kvtcb@graphenv}%
  \tcb@bbdraw%
  \tcb@apply@graph@patches%
}

\def\tcb@drawing@env@end{%
  \end{\kvtcb@graphenv}%
  \ResumeTagging{tcb/drawing}\UseTaggingSocket{tcb/drawing/end}%
  \csname tcb@after@\tcb@split@state\endcsname%
}
\makeatother\ExplSyntaxOff


\begin{document}

\begin{tcolorbox}[enhanced,breakable]
\lipsum[1-12]
\end{tcolorbox}

\end{document}
``` 

But, I just copied the `\DocumentMetadata` from another example without understanding the meaning. Maybe, this is part of the problem?

**Comment by T-F-S** [comment]
Any ideas how to proceed?

As the examples above show, suppressing the drawing outside `tikzpicture` gives uncompilable code. I issued an example at https://github.com/latex3/tagpdf/issues/104 which shows the problem even without using tcolorbox.

Should I add the suppressing code inside `tikzpicture`? At least, the current examples compile, but I have no clue, what the code does and if it makes the document better or worse.

**Comment by u-fischer** [comment]
As I commented in the tagpdf issue, the main problem is to get the paragraphs right. The code uses the para/begin and para/end hooks to automatically tag paragraphs (and so surround them by the html equivalent of `<P>` and `</P>`).  The easiest place to suspend/resume is between paragraphs as normally everything is closed there anyway. Inside paragraphs one really has to think about the correct nesting ;-).

**Comment by T-F-S** [comment]
> As I commented in the tagpdf issue, the main problem is to get the paragraphs right. The code uses the para/begin and para/end hooks to automatically tag paragraphs (and so surround them by the html equivalent of `<P>` and `</P>`). The easiest place to suspend/resume is between paragraphs as normally everything is closed there anyway. Inside paragraphs one really has to think about the correct nesting ;-).

Currently, between broken parts of a tcolorbox, there is `\par\pagebreak` or `\par\vfill\eject`. In test code, I added additional `\leavevmode` before the next drawing starts, but the errors remain.

Again: Would it help to move the suppressing code **inside** the `tikzpicture`? Because, this compiles...

**Comment by u-fischer** [comment]
> Again: Would it help to move the suppressing code **inside** the `tikzpicture`? Because, this compiles...

I would need a small PDF to check if the markup in the stream is right. 

Are you using a normal tikzpicture environment? Could one pass a key like e.g. `artifact` to it?

**Comment by T-F-S** [comment]
The example code is:

```latex
\DocumentMetadata{
  lang        = de,
  pdfversion  = 2.0,
  pdfstandard = ua-2,
  pdfstandard = a-4f,
  testphase   =
  {
    phase-III,
  },
  uncompress,
}

\tagpdfsetup{tabsorder=structure}

\documentclass[]{article}

\usepackage{lipsum}
\usepackage[many]{tcolorbox}

\ExplSyntaxOn\makeatletter
\NewSocket{tagsupport/tcb/drawing/begin}{0}
\NewSocket{tagsupport/tcb/drawing/end}{0}
\NewSocketPlug{tagsupport/tcb/drawing/begin}{suspend}
 {\tag_mc_end_push:\tag_mc_begin:n{artifact}}
\NewSocketPlug{tagsupport/tcb/drawing/end}{resume}
 {\tag_mc_end:\tag_mc_begin_pop:n{}}
\AssignSocketPlug{tagsupport/tcb/drawing/begin}{suspend}
\AssignSocketPlug{tagsupport/tcb/drawing/end}{resume}


\def\tcb@drawing@env@begin{%
  \csname tcb@before@\tcb@split@state\endcsname%
  \begin{\kvtcb@graphenv}%
  \UseTaggingSocket{tcb/drawing/begin}\SuspendTagging{tcb/drawing}%
  \tcb@bbdraw%
  \tcb@apply@graph@patches%
}

\def\tcb@drawing@env@end{%
  \ResumeTagging{tcb/drawing}\UseTaggingSocket{tcb/drawing/end}%
  \end{\kvtcb@graphenv}%
  \csname tcb@after@\tcb@split@state\endcsname%
}
\makeatother\ExplSyntaxOff


\begin{document}

\begin{tcolorbox}[enhanced,breakable]
\lipsum[1-12]
\end{tcolorbox}

\end{document}
```

It is just switching the nesting of `\kvtcb@graphenv` and `\SuspendTagging`. `\kvtcb@graphenv` is `pgfpicture` *or* `tikzpicture` depending on the skin. The example code above uses `tikzpicture`. If you remove the key `enhanced` from the tcolorbox, the code will use `pgfpicture`.

**Comment by u-fischer** [comment]
No it doesn't work. At least not with pdflatex (lualatex seems fine). If you look into the PDF (because of the uncompress key it is mostly ascii) then you can see this in the stream:

~~~~
/Artifact BMC
0 g 0 G
0 g 0 G
EMC
/text <</MCID 0 >> BDC
1 0 0 1 133.768 124.428 cm
q 
0 G 
0 g 
0.3985 w 
q                  
   <--------------------------- here closing EMC is missing
/Artifact BMC
q 
q 
~~~~

and later on a part of the text is still marked up as artifact.

Somewhere the tagging code looses track about the open and closed MC-chunks, but I don't know yet where - there is so much going on at the begin and end of the picture that it is difficult to trace - probably somewhere the literal is in a stored box and then moved. 

I would suggest to ignore pdflatex for now and to add support only for lualatex. There your last version with the code inside the picture looks fine, and at least for boxes used inside paragraphs like in the original question, it is also needed.

**Comment by T-F-S** [comment]
> I would suggest to ignore pdflatex for now and to add support only for lualatex. There your last version with the code inside the picture looks fine, and at least for boxes used inside paragraphs like in the original question, it is also needed.

I will add the code to the next version of tcolorbox as a starting point for tagging support. Further, I will test, if I can drop `pgfpicture` and have `tikzpicture` everywhere, which may give a cleaner code for future adaptions.

**Comment by T-F-S** [comment]
Done with https://github.com/T-F-S/tcolorbox/releases/tag/v6.3.0
Hopefully, the changes bring the wanted effect. I close this for now.
