### ISSUE TITLE
Adaption to TikZ picture option keys like `/tcb/tikz`

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#285]
Starting from v6.3.0 all skins use `tikzpicture` as internal environment, thus the options currently documented in sec. 10.7 "TikZ Picture Option Keys", for example `/tcb/tikz` are now supported by all skins as well.
https://github.com/T-F-S/tcolorbox/blob/f7f39a4af09b6cce028c0e8e83d6c40f56d899d1/doc/latex/tcolorbox/tcolorbox.doc.skins.tex#L2287-L2289

Accordingly their implementation can be moved from `skins` library to the main `tcolorbox.sty` file, and their documentation can be moved to the main option list, under sec. 4 "Option Keys".

```tex
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{skins} % provides /tcb/tikz

\begin{document}
% "standard" skin supports /tcb/tikz now
\begin{tcolorbox}[title=Title, tikz={opacity=0.5,transparency group}]
  content
\end{tcolorbox}
\end{document}
```

![image](https://github.com/user-attachments/assets/b06ed472-aaf5-4dfe-ae8a-d003ea319cdd)

**Comment by T-F-S** [comment]
I am not endorsing TikZ code for the `standard` skin, even if this works now at several places. Most prominentely, `geometry nodes` are not set with the `standard` skin and many following things expect nodes like `frame` or `interior` to be present.

So, for `standard`, I want to keep the focus on just using `pgf` code and switching to `enhanced` for all fancier features. Nevertheless, on the spot you marked, I will remove the two lines from the documentation, but at other places I want to still keep warnings to not use the fancier features with `standard`.

**Comment by T-F-S** [comment]
Done with Done with https://github.com/T-F-S/tcolorbox/releases/tag/v6.4.0
