### ISSUE TITLE
Leftover doc adaptions for the `pgfpicture` to `tikzpicture` transition

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#286]
For example `/tcb/frame code={<graphical code>}` now always accepts tikz drawing code.

```
$ rg --no-heading '\|pgf\| (code|command)' doc
doc/latex/tcolorbox/tcolorbox.doc.coreoptions.tex:2761:If you use the core package only, the \meta{graphical code} has to be |pgf| code
doc/latex/tcolorbox/tcolorbox.doc.skincatalog.tex:115:  are set to type |standard|. The drawing is based on |pgf| commands and
doc/latex/tcolorbox/tcolorbox.doc.technical.tex:208:The used \meta{graphical code} can be any |pgf| code. For all skins
```

**Comment by T-F-S** [comment]
Leftovers are intentionally, see https://github.com/T-F-S/tcolorbox/issues/285#issuecomment-2228030079

**Comment by muzimuzhi** [comment]
> Most prominentely, `geometry nodes` are not set with the `standard` skin and many following things expect nodes like `frame` or `interior` to be present.
> _<sub>https://github.com/T-F-S/tcolorbox/issues/285#issuecomment-2228030079</sub>_

Good point. I overlooked the usual use cases of such `<graphical code>`s.
