### ISSUE TITLE
Improve tcolorbox placement

### ISSUE THREAD

**Issue by nignasi** [T-F-S/tcolorbox#29]
this is not a problem but a question or suggestion. I wanted to answer 

https://tex.stackexchange.com/questions/375698/creating-this-poster-layout-using-minpages/375865#375865

using `tbcraster` but I couldn't. So the question is: is it possible with `tcbrasters` obtain a complex placement of tcolorboxes like that?

Finally I could solve the problem inserting the tcolorboxes inside `TiKZ` nodes. And this is my suggestion.

I know every tcolorbox can be `remembered` but there is no way (I don't know or remember it) of positioning them with respect of another one. I can not use a `right = of A-tcolorbox` or `above= of A-tcolorbox`.  I know tcolorboxes are not `nodes` and that they are usually defined on its own an not inside `tikzpictures` but, may be, you could consider improving this aspect. It could be useful for posters or any other special documents like advertisments, magazines, ...

**Comment by T-F-S** [comment]
A `tcbraster` is designed to act like normal 'flowing text', even if the result looks like a raster or table. Therefore, page breaking in a raster flow is no problem.

On the other hand, creating a free pattern for a page - like in the example - can easily be too complex for such a 'flow'. So, the answer to your question is that I do not see a `tcbraster` solution here. As you did, I would also use a `TikZ` environment for placements.

In the past, I experimented a lot to make an option for `tcolorboxes` like `use as tikz node` for integration into a `tikzpicture`. Unfortunately, I did'nt have success ... I do not have much hope that this may change.

Maybe, a more or less smart shortcut macro to combine a `TikZ` node with an embedded `tcolorbox` could be helpful to set up posters more conveniently? I will think about that.

**Comment by nignasi** [comment]
Thank you for your comments. Now I better understand limitations on `tcbraster`.

And thank you for considering possible improvements for posters. If it could help you I would like to suggest to [`baposter`](http://www.brian-amberg.de/uni/poster/) format. With it is easier to define complex boxes dispositions. I've made a little example in sharelatex: 

https://www.sharelatex.com/project/594a2cbde341f31a47fbb784

As you can see, it defines a multicolumn structure where boxes are placed on. Once a box has been created, following boxes can make reference to it for placement but also for size definition. Although baposter introduces this flexibility for placement, it's limited in boxes formatting. `tcolorbox` allows to define many more styles.

**Comment by T-F-S** [comment]
Thank you for your `baposter` example. It is really helpful for me, since I didn't knew this package before.

**Comment by T-F-S** [comment]
With `tcolorbox` 4.10, there is a brand new library `poster` which comes with [tutorial](https://github.com/T-F-S/tcolorbox/blob/master/doc/latex/tcolorbox/tcolorbox-tutorial-poster.pdf).

This library follows the same basic ideas as `baposter`, but, of course, does everything in a `tcolorbox` way.  You may especially be interested in the `sequence` placement for breakable box parts...

**Comment by nignasi** [comment]
Impressive! Thank you.
