### ISSUE TITLE
[FR] [raster library] use vfill to spread raster vertically to the whole page

### ISSUE THREAD

**Issue by atticus-sullivan** [T-F-S/tcolorbox#291]
Hi,

it would be cool to be able to vertically spread the boxes typeset with the `raster` library over the whole page.
Is this a reasonable request and is this achievable with the current design of `tcolorbox`?
Or am I missing something and this is already possible somehow?

---

Context/Motivation:
I'm trying to port a poster template to tcolorbox. Reading the docs I see there are two common ways to do posters.
1. use the `poster` library. As I understand it, this segments the page into a predefined amount of rows and columns. When you then add boxes to the poster you can specify the coordinate (in rows/columns) where to put that box.<br>The downside for me is I want the poster boxes to be read left-to-right and the different rows should be able to have different heights.
2. use the `raster` library. This supports rows with individual heights out of the box. But when the boxes do not fill the complete page, I'd like to spread them vertically over the page (was formerly done by inserting `\vfill` between the rows). I do not find a way to do this with the `raster` library as it does not allow for code other than defining tcolor boxes in the raster and setting `raster row skip=\fill` also does not bring the desired layout.

I already saw there is `raster height` but this has two major disadvantages
1. does not work properly when the `tcolorbox`es have a title (wrong height is used)
2. now we're back again where all rows get the same height (just like with `poster`)

Some images to illustrate current state and (kinda) goal (don't wonder about the resolution, the poster is A0 and I zoomed out so that it fits on the screen). The outer borders are drawn with `showframe`.

my current state:
![image](https://github.com/user-attachments/assets/c89fc320-1329-4083-bb09-9adc890139d3)

the original template (the property that the box has a larger height than the text is not needed/unwanted):
![image](https://github.com/user-attachments/assets/f6abaf05-4eaa-4e27-a451-7a55741bbb84)

**Comment by T-F-S** [comment]
You could create each row with one `raster` and put `\vill` between the rows to spread.

The following example uses `tcbitemize` which is just a shortcut and can be replaced by `tcbraster` with `tcolorbox`es inside:

![grafik](https://github.com/user-attachments/assets/1e7280a5-98e3-4194-a272-ebf86ed180cc)

```latex
\documentclass{article}
\usepackage[a4paper,margin=10mm]{geometry}
\usepackage[raster,skins]{tcolorbox}

\begin{document}

\tcbset{
  raster columns=3,
  raster equal height,
  mybox/.style={
    enhanced,
    sharp corners,
    colback=white,
    colframe=blue!50!black,
    colbacktitle=blue!50!black,
    boxed title style={sharp corners,tile},
    attach boxed title to top left,
  },
}

% Row
\begin{tcbitemize}[mybox]
\tcbitem[
    attach boxed title to top left,
    title=Left Box Title
  ]
  Inner title
  \begin{itemize}
  \item one
  \item two
  \item three
  \end{itemize}
\tcbitem[
    attach boxed title to top center,
    title=Middle Box Title
  ]
  Inner title
  \begin{itemize}
  \item one
  \item two
  \item three
  \end{itemize}
  \tcbitem[
    attach boxed title to top right,
    title=Right Box Title
  ]
  Inner title
  \begin{itemize}
  \item one
  \item two
  \item three
  \end{itemize}
\end{tcbitemize}

\vfill

% Row
\begin{tcbitemize}[mybox]
\tcbitem[
    attach boxed title to top left,
    title=Left Box Title
  ]
  Inner title
  \begin{itemize}
  \item one
  \item two
  \item three
  \item four
  \item five
  \item six
  \end{itemize}
\tcbitem[
    attach boxed title to top center,
    title=Middle Box Title
  ]
  Inner title
  \begin{itemize}
  \item one
  \item two
  \item three
  \end{itemize}
  \tcbitem[
    attach boxed title to top right,
    title=Right Box Title
  ]
  Inner title
  \begin{itemize}
  \item one
  \item two
  \item three
  \end{itemize}
\end{tcbitemize}

\vfill

% Row
\begin{tcbitemize}[mybox]
\tcbitem[
    attach boxed title to top left,
    title=Left Box Title
  ]
  Inner title
  \begin{itemize}
  \item one
  \item two
  \item three
  \end{itemize}
\tcbitem[
    attach boxed title to top center,
    title=Middle Box Title
  ]
  Inner title
  \begin{itemize}
  \item one
  \item two
  \item three
  \end{itemize}
  \tcbitem[
    attach boxed title to top right,
    title=Right Box Title
  ]
  Inner title
  \begin{itemize}
  \item one
  \item two
  \item three
  \end{itemize}
\end{tcbitemize}

\vfill

% Row
\begin{tcbitemize}[mybox]
\tcbitem[
    attach boxed title to top left,
    title=Left Box Title
  ]
  Inner title
  \begin{itemize}
  \item one
  \item two
  \item three
  \end{itemize}
\tcbitem[
    attach boxed title to top center,
    title=Middle Box Title
  ]
  Inner title
  \begin{itemize}
  \item one
  \item two
  \item three
  \item four
  \item five
  \item six
  \end{itemize}
  \tcbitem[
    attach boxed title to top right,
    title=Right Box Title
  ]
  Inner title
  \begin{itemize}
  \item one
  \item two
  \item three
  \end{itemize}
\end{tcbitemize}

\end{document}
```

**Comment by atticus-sullivan** [comment]
First of all, thanks for the fast reply.

That makes totally sense. This way looking at the code the placement of the line break also is more obvious. (Ok maybe a post on tex.stackexchange would have been more suitable than opening an issue, so sorry to bother you) 

Not quite sure if it still would be nice to be able to write this with one single raster, but your solution totally works for me.
