### ISSUE TITLE
better error messages for keys defined in libraries

### ISSUE THREAD

**Issue by mbertucci47** [T-F-S/tcolorbox#292]
I often try to use keys in a tcolorbox library I haven't loaded and have to search the documentation to find which library is necessary to use that key. I'd guess this is a common source of frustration for new users of tcolorbox. One can of course load the `many`, `most`, or `all` libraries, but if it makes sense to have separate libraries at all, I think it makes sense for the keys to give an informative error about which library needs to be loaded to use it.

I'm assuming the number of keys defined in libraries is at most a few hundred. The following example shows defining 400 extra keys to produce a tailored error takes about 0.01 seconds.
```tex
\documentclass{article}
\usepackage{tcolorbox}
\usepackage{l3benchmark}

\makeatletter
\ExplSyntaxOn
\benchmark:n
  {
    \int_step_inline:nn { 400 }
      {
        \tcbset{
          tcbfoo #1/.ecode=
            \noexpand\tcb@error{The~key~'\pgfkeyscurrentpath'~requires~the~'hooks'~library}
            }
      }
  }
\ExplSyntaxOff
\makeatother

\begin{document}

% compare this error
\tcbset{extras pre={}}

% with this error
\tcbset{tcbfoo5}

\end{document}
```
If this is something you think is worth adding, I am happy to make a PR.

**Comment by muzimuzhi** [comment]
That seems the job of a lint/linter in general-purpose programming languages, but as there's no such tool for TeX yet...

**Comment by T-F-S** [comment]
The idea is interesting, but I hesitate to go into this direction. The maintaining of the key catalogue for new or deprecated or moved keys is not a thing I would love to do.

And all the effort would not help for the most common use case: misspelling of keys, e.g. `\tcbset{extra pre={}}` would generate a general error, even if `\tcbset{extras pre={}}` gives a nicer error message with a large key catalogue... So, as a user, I would look up the documentation where I find: *'Oh, I misspelled it'*.

For a brand new user trying out examples, my advice would be to load `most` or `all` libraries. Later, if the use case is clear, this can be boiled down to the really needed libraries to speed up things.

**Comment by mbertucci47** [comment]
Yes, maintenance does seem to be the biggest problem. I will close the issue.

If you don't mind my asking, is there a reason some of the libraries are not incorporated into the package by default? Some, like hooks, breakable, fitting, and probably a few more, seem to have little overhead in terms of speed, and offer quite general functionality (as opposed to, say, poster or minted).

**Comment by T-F-S** [comment]
> If you don't mind my asking, is there a reason some of the libraries are not incorporated into the package by default? Some, like hooks, breakable, fitting, and probably a few more, seem to have little overhead in terms of speed, and offer quite general functionality (as opposed to, say, poster or minted).

Well, the general idea is that the base package should be lean (not so lean at all for tcolorbox) and additional functionality - which is not needed, if you *'just want draw some colored boxes'* - is put into loadable libraries. This is intended to spead up compilation and also to improve maintainability.

Now, one can argue what functionality is *basic* and what not. Speaking for my person, e.g. I use `skins` for most projects, but `hooks` very seldom, `breakable` say fifty-fifty, etc. Other people may have other preferences. So, it depends what you may consider *basic* or *additional*.
