### ISSUE TITLE
Update `zref-clever` support so that `tcolorbox`'s `label type` can also work with zlabels set from the `label` hook

### ISSUE THREAD

**Issue by gusbrs** [T-F-S/tcolorbox#295]
Since some time the kernel has introduced a new `label` hook with arguments, and `zref-clever` benefited from it by providing a `labelhook` option, which essentially sets a `\zlabel` with the same name whenever the standard `\label` is called. This is not only a convenience (people can use the traditional `\label`), but also critical in certain places in which only `\label` is actually supported (e.g. `amsmath`'s display math environments). So this new hook and the corresponding option meant less trouble in the "compatibility" area for the package, hence it is enabled by default, and its use is recommended to users.

I'm currently updating the user manual to take a stronger stance in this direction, and I found out I could not update the `tcolorbox` example because of the way the `label type` option is implemented (see https://github.com/T-F-S/tcolorbox/issues/206 and https://github.com/T-F-S/tcolorbox/issues/230). The problem is twofold:

- When `label is label`, if `label type` is set, `\__tcobox_zcsetup_reftype:n` is not called, hence the `\zlabel` called from the `label` hook won't get the setting.
- When `label is label`, if `label type` is set, `tcolorbox` assumes `cleveref` is present, and unconditionally sets a `\label` with optional argument and, in the absence of `cleveref` this wreaks havoc to the labels, as expected.

True, `tcolorbox` manual is clear that the use of `label type` with `label is label` "can be used only in conjunction with the `cleveref` package". But I'd argue the package could fail more gracefully in its absence.

As far as I can tell, all we'd need is:

- Some check for the presence of `cleveref`:
```tex
\bool_new:N \g__tcobox_cleveref_loaded_bool
\AddToHook{package/cleveref/after}
  { \bool_gset_true:N \g__tcobox_cleveref_loaded_bool }
```

- Redefine `\__tcobox_label_label:n` to make use of this bool and also call `\__tcobox_zcsetup_reftype:n`
```tex
\cs_new:Npn \__tcobox_label_label:n #1
  {
    \quark_if_nil:NTF \l__tcobox_kv_labeltype_tl
      {
        \label{#1}
      }
      {
        \group_begin:
        \exp_args:NV \__tcobox_zcsetup_reftype:n \l__tcobox_kv_labeltype_tl
        \bool_if:NTF \g__tcobox_cleveref_loaded_bool
          { \exp_last_unbraced:NNV \label[\l__tcobox_kv_labeltype_tl]{#1} }
          { \label{#1} }
        \group_end:
      }
  }
```

Using the example from `zref-clever`'s manual as MWE, we have:

```tex
\documentclass{article}
\usepackage{zref-clever}
\usepackage{zref-titleref}
\usepackage{tcolorbox}
\tcbuselibrary{theorems}

% We'd like for zref-clever + labelhook to work (also) without it.
% \tcbset{label is zlabel}

\ExplSyntaxOn
\bool_new:N \g__tcobox_cleveref_loaded_bool
\AddToHook{package/cleveref/after}
  { \bool_gset_true:N \g__tcobox_cleveref_loaded_bool }
% \cs_new:Npn \__tcobox_label_label:n #1
\cs_set:Npn \__tcobox_label_label:n #1
  {
    \quark_if_nil:NTF \l__tcobox_kv_labeltype_tl
      {
        \label{#1}
      }
      {
        \group_begin:
        \exp_args:NV \__tcobox_zcsetup_reftype:n \l__tcobox_kv_labeltype_tl
        \bool_if:NTF \g__tcobox_cleveref_loaded_bool
          { \exp_last_unbraced:NNV \label[\l__tcobox_kv_labeltype_tl]{#1} }
          { \label{#1} }
        \group_end:
      }
  }
\ExplSyntaxOff

% Set the default again because we redefined it...
\tcbset{label is label}

\usepackage{hyperref}
\newtcolorbox[auto counter,number within=section]{pabox}[2][]{%
  label type=example,
  title=Example~\thetcbcounter: #2,#1}
\newtcolorbox[use counter from=pabox,number within=section]{pabox2}[2][]{%
  label type=solution,
  title=Solution~\thetcbcounter: #2,#1}
\newtcbtheorem[number within=section]{mytheo}{My Theorem}{%
  label type=mytheorem}{th}
\zcRefTypeSetup{mytheorem}{
  Name-sg=Mytheorem,
  name-sg=mytheorem,
  Name-pl=Mytheorems,
  name-pl=mytheorems,
}
\begin{document}
\section{Section 1}
\label{sec:section-1}
\begin{pabox}[label={box:1}]{Title text}
  This is tcolorbox \zcref{box:1} on \zcpageref{box:1}.
\end{pabox}
\begin{pabox2}[label={box:2}]{Title text}
  This is tcolorbox \zcref{box:2} on \zcpageref{box:2}.
\end{pabox2}
\begin{mytheo}{This is my title}{theo}
  This is \zcref{th:theo} on \zcpageref{th:theo} and it is titled
  ``\zcref[noname,ref=title]{th:theo}''.
\end{mytheo}
\end{document}
```

This would let `label type` fail silently in the absence of the packages which make use of it. And would work with either (or both) of them, included with `zref-clever`'s `labelhook` option.

WDYT?

**Comment by gusbrs** [comment]
Hi @T-F-S , thanks for considering this.

> A check for the presence of `cleveref` would be a good thing. But, I am not sure, if
> 
> ```
> \bool_new:N \g__tcobox_cleveref_loaded_bool
> \AddToHook{package/cleveref/after}
>   { \bool_gset_true:N \g__tcobox_cleveref_loaded_bool }
> ```

I think the pieces for this are the following. `ltfilehook-doc` says about the package hooks:

> All class or package hooks involving the name of the class or package are implemented as one-time hooks, whereas all other such hooks are normal hooks.

`lthooks-doc` says about one-time hooks:

> With one-time hooks it this is handled slightly differently: After \UseOneTimeHook has been called, any further attempts to add code to the hook via \AddToHook will simply execute the ⟨code ⟩ immediately. This has some consequences one needs to be aware of:
> - If ⟨code ⟩ is added to a normal hook after the hook was executed and it is never executed again for one or the other reason, then this new ⟨code ⟩ will never be executed.
> - In contrast if that happens with a one-time hook the ⟨code ⟩ is executed immediately.

In other words, if `tcolorbox` is loaded before `cleveref` the code is added to the hook, and executed when (and only if) `cleveref` is loaded. If `cleveref` has been loaded before `tcolorbox` the code is executed immediately. But since the hook is set in `tcolorbox` it naturally cannot be executed before `tcolorbox` itself. Either case, the existence of the boolean is ensured.

I see you edited the grouping question, I suppose you figured it out. In any case, the reason is the same as discussed in https://github.com/T-F-S/tcolorbox/issues/230. The need is for the sake of `zref-clever`, since otherwise `reftype` would leak and affect all other zlabels in the environment. But it should be harmless, since the kernel itself groups the contents of `\label` anyway (because of the `label` hook, I presume, see `ltnews37` "Extension of the \label command").

**Comment by T-F-S** [comment]
Thank you very much for explaining the hook mechanism for package in detail! This was very helpful to.

> I see you edited the grouping question, I suppose you figured it out. In any case, the reason is the same as discussed in #230. The need is for the sake of `zref-clever`, since otherwise `reftype` would leak and affect all other zlabels in the environment. But it should be harmless, since the kernel itself groups the contents of `\label` anyway (because of the `label` hook, I presume, see `ltnews37` "Extension of the \label command").

Yes, I remembered the reason for grouping afterwards and therefore edited my post.

So, I will add your proposed code to the next version of `tcolorbox`. Having a `\zlabel` automatically with `\label` is, I think, a very good new feature of your package!

Thank your for your contribution!

**Comment by gusbrs** [comment]
> So, I will add your proposed code to the next version of `tcolorbox`.

Thank you very much!

> Having a `\zlabel` automatically with `\label` is, I think, a very good new feature of your package!

That `label` hook was indeed a gift from the kernel. I suppose the main reason was the patch `nameref` used to do to `\label`, but it also releases some tension from some traditional load order issues. Well, `zref-clever` is thus "getting a ride". The package was designed to be "civil", or at least tries very hard to. And, nowadays, I think it is fair to say it introduces very little friction (if any) with other people's code (as far as I know, you can even use it alongside `cleveref`). But the kernel hook really makes this task much easier. And also makes me expect "full coverage" (or almost full, "as good as `nameref`", say), which previously I could not presume. :-)

> Thank your for your contribution!

Thank *you* for always welcoming such suggestions!

**Comment by T-F-S** [comment]
Implemented with https://github.com/T-F-S/tcolorbox/releases/tag/v6.4.1

**Comment by gusbrs** [comment]
> Implemented with https://github.com/T-F-S/tcolorbox/releases/tag/v6.4.1

Wow, that was fast! With a release on top. :smile: 

Once again, thank you very much!
