### ISSUE TITLE
broken listing decreases interline space

### ISSUE THREAD

**Issue by mbertucci47** [T-F-S/tcolorbox#298]
If a tcb listing breaks at the right place, it can decrease the space between text in the code. I encountered this in the documentation of my package, which hopefully explains the setup. I tried for an hour to replicate the issue with a more minimal setup but I could not, so either the issue is specific to my using `\tcbusetemplisting` or I'm missing something. Here's an example.
```tex
\documentclass{article}

\usepackage{tcolorbox}
\tcbuselibrary{minted,breakable}
\usepackage{kantlipsum}

\tcbset{
  listing engine=minted,
  minted language=latex,
  withpreamble/.style = {
    before upper = {%
      {\ttfamily\itshape \% preamble}%
      \vspace{-8pt}%
      \tcbusetemplisting
      \noindent{\ttfamily\itshape \% document}%
      \vspace{-8pt}%
      }
    }
  }

\NewTCBListing{codeex}{ O{} }
  {
    boxrule=0pt,
    breakable,
    #1
  }

\begin{document}

\begin{tcbwritetemp}
Some preamble code
\end{tcbwritetemp}

\begin{codeex}[withpreamble]
Some code to print
\end{codeex}

\kant[1-2]
\kant[3][1-5]

\begin{tcbwritetemp}
Some preamble code
\end{tcbwritetemp}

\begin{codeex}[withpreamble]
Some code to print
\end{codeex}

\end{document}
```
![lll-1](https://github.com/user-attachments/assets/f86adda7-dd7f-4d6c-b6ae-2c853596b161)

As you can see the space between `% preamble` and `% document` and the proceeding text is decreased significantly for the broken box.

**Comment by muzimuzhi** [comment]
`\tcbusetemplisting` is the culprit.

When `/tcb/listing engine=minted`, `\tcbusetemplisting` will call an [`\inputminted`](https://github.com/T-F-S/tcolorbox/blob/b59111a7429eccf196e716edec170f52fe560232/tex/latex/tcolorbox/tcbminted.code.tex#L34-L56), whose output is wrapped in a `\list`, thus typical upper and lower [list skips](https://latexref.xyz/list.html) consisting of `\topsep`, `\parskip`, and optionally `\partopsep` are inserted.

As `\topsep` has a shrinking part, when it shrinks you get inconsistent vertical spacings.

One workaround is to locally change `\topsep` for `\tcbusetemplisting`:
```tex
% \vspace{-8pt}%
{\setminted{listparameters={\topsep=0pt}}\tcbusetemplisting}
```

Full example
```tex
\documentclass{article}

\usepackage{tcolorbox}
\tcbuselibrary{minted,breakable}
\usepackage{kantlipsum}

\tcbset{
  listing engine=minted,
  minted language=latex,
  withpreamble/.style = {
    before upper = {%
      {\ttfamily\itshape \% preamble}%
      % \vspace{-8pt}%
      {\setminted{listparameters={\topsep=0pt}}\tcbusetemplisting}
      \noindent{\ttfamily\itshape \% document}%
      \vspace{-8pt}%
      }
    }
  }

\NewTCBListing{codeex}{ O{} }
  {
    boxrule=0pt,
    breakable,
    #1
  }

\begin{document}

\begin{tcbwritetemp}
Some preamble code
\end{tcbwritetemp}

\begin{codeex}[withpreamble]
Some code to print
\end{codeex}

\kant[1-2]
\kant[3][1-5]

\begin{tcbwritetemp}
Some preamble code
\end{tcbwritetemp}

\enlargethispage{\baselineskip}

\begin{codeex}[withpreamble]
Some code to print
\end{codeex}

\end{document}
```

| Header | Header |
|--------|--------|
| <img width="425" alt="image" src="https://github.com/user-attachments/assets/96b7bbf2-cac7-4d03-81f1-d05d12dcf02f"> | <img width="414" alt="image" src="https://github.com/user-attachments/assets/8e098f25-42ec-4079-9c6d-79aa377b9984"> |

**Comment by muzimuzhi** [comment]
I couldn't resist highlighting `% preamble` and `% document` lines in LaTeX too.

Below is an attempt which highlights then typesets all four components (preamble comment, preamble code, document comment, document code) one by one. The best solution is to highlight all the four components in one run, which needs hack into `tcblisting` env.

<details><summary>Highlight <code>% preamble</code> and <code>% document</code> too</summary>
<p>

```tex
\documentclass{article}

\usepackage{tcolorbox}
\tcbuselibrary{minted,breakable}
\usepackage{kantlipsum}

\makeatletter
\newbox\doc@preamble
\newbox\doc@document

\begin{tcbwritetemp}
% preamble
\end{tcbwritetemp}
\setbox\doc@preamble=\hbox{\setminted{envname=VerbEnv}\tcbusetemplisting}

\begin{tcbwritetemp}
% document
\end{tcbwritetemp}
\setbox\doc@document=\hbox{\setminted{envname=VerbEnv}\tcbusetemplisting}

\tcbset{
  listing engine=minted,
  minted language=latex,
  withpreamble/.style = {
    before upper = {%
      % affects \tcbsettemplisting and the original upper
      \setminted{listparameters={\topsep=0pt \partopsep=0pt}}%
      \usebox\doc@preamble\par
      \tcbusetemplisting
      \usebox\doc@document\par
      }
    }
  }
\makeatother

\NewTCBListing{codeex}{ O{} }
  {
    boxrule=0pt,
    breakable,
    #1
  }

\begin{document}

\begin{tcbwritetemp}
Some preamble code
\end{tcbwritetemp}

\begin{codeex}[withpreamble]
Some code to print
\end{codeex}

\kant[1-2]
\kant[3][1-5]

\begin{tcbwritetemp}
Some preamble code
\end{tcbwritetemp}

\begin{codeex}[withpreamble]
Some code to print
\end{codeex}

\end{document}
```

</p>
</details> 

| Header | Header |
|--------|--------|
| <img width="679" alt="image" src="https://github.com/user-attachments/assets/1ef089e0-28fd-4e63-aa80-da5e90ec7ce1"> | <img width="664" alt="image" src="https://github.com/user-attachments/assets/ff47096c-d387-47bb-b2eb-1572c0480d1f"> |

**Comment by mbertucci47** [comment]
@muzimuzhi As always, thanks for your in-depth investigation. So I guess this is not a bug, just how minted does things, right?

**Comment by mbertucci47** [comment]
Also, thanks for the suggestion!

I think this can be closed.

**Comment by muzimuzhi** [comment]
> So I guess this is not a bug, just how minted does things, right?

Yes, which is ultimately inherited from the `fancyvrb` package. (`minted` loads `fvextra` which then loads `fancyvrb`.)

Strictly speaking, what `fancyvrb` uses is not the `\list` command, but an adapted version: `\list` skips are reused but no-item check is dropped.
