### ISSUE TITLE
Problem with tcblisting with an optional argument

### ISSUE THREAD

**Issue by nignasi** [T-F-S/tcolorbox#3]
When a tecblisting is declared with only an optional argument, if this argument is not present and the first word in listing starts with \, the first word is not shown in listing. 

Better explained with examples at: http://tex.stackexchange.com/questions/247643/problem-with-tcblisting-first-listed-latex-command-is-missing

Ignasi

**Comment by T-F-S** [comment]
Hi Ignasi,

I would recommend to switch to the 'xparse' version to avoid the problem.
See my answer at
http://tex.stackexchange.com/questions/247643/problem-with-tcblisting-first-listed-latex-command-is-missing/248738#248738

Best regards,
Thomas
