### ISSUE TITLE
Proposal of `ignore percent sign` key (aiming for more integration w/ DocStrip)

### ISSUE THREAD

**Issue by yudai-nkt** [T-F-S/tcolorbox#30]
__TL;DR__: I implmented a new key for myself, and think it will be of use for others as well.

---

I use `documentation` library with DocStrip. They work well together, but there is a problem in the interaction between them. Since document is _commented out_ in DocStrip source, the `dispExample` environment and its siblings verbatimly output `%` in the documentation.

Consider the following example `MWE.dtx`:

```latex
% \iffalse meta-comment
%<*internal>
\def\nameofplainTeX{plain}
\ifx\fmtname\nameofplainTeX\else
  \expandafter\begingroup
\fi
%</internal>
%<*install>
\input docstrip.tex
\keepsilent
\askforoverwritefalse
\usedir{tex/latex/\jobname}
\generate{
  \file{\jobname.sty}{\from{\jobname.dtx}{package}}
}
%</install>
%<install>\endbatchfile
%<*internal>
\usedir{source/latex/\jobname}
\generate{
  \file{\jobname.ins}{\from{\jobname.dtx}{install}}
}
\ifx\fmtname\nameofplainTeX
  \expandafter\endbatchfile
\else
  \expandafter\endgroup
\fi
%</internal>
%<*driver>
\documentclass{article}
\usepackage{doc}
\usepackage[all]{tcolorbox}
\usepackage{\jobname}
\begin{document}
  \DocInput{\jobname.dtx}
\end{document}
%</driver>
% \fi
%
% \section{User guide}
% \begin{docCommand}{mwe}{}
%   is a shorthand for ``minimum working example''.
% \end{docCommand}
% \begin{dispExample}
%   You need to inculude MWE (\mwe) in your question.
% \end{dispExample}
% \section{Implementation}
%    \begin{macrocode}
%<*package>
%    \end{macrocode}
% Basic information of the package.
%    \begin{macrocode}
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{MWE}[2017/06/29 v1.0.0 MWE for my proposal]
%    \end{macrocode}
% MWE is an acronym for ``minimum working example''.
%    \begin{macrocode}
\newcommand*{\mwe}{minimum working example}
%    \end{macrocode}
%    \begin{macrocode}
%</package>
%    \end{macrocode}
```

Processing `MWE.dtx` with `pdflatex -shell-escape` produces the package documentation along with other artifacts, and the documentation looks like this.

![mwe](https://user-images.githubusercontent.com/13291527/27672452-0e8a9a4c-5cd6-11e7-9d6a-896c1a9b97ee.png)

This behavior is not what most package authors want, so I made a new key `ignore percent sign`:

```latex
\tcbset{
  ignore percent sign/.code={\let\tcbverbatimwrite=\tcbdocverbatimwrite},
}
\def\tcbdocverbatimwrite#1{%
  \@bsphack
  \immediate\openout\tcb@out #1
  \tcb@verbatim@begin@hook
  \let\do\@makeother\dospecials
  \catcode`\^^e=9\catcode`\^^M\active \catcode`\^^I=12
  \def\verbatim@processline{%
    \immediate\write\tcb@out
      {\the\verbatim@line}}%
  \verbatim@start}%
```

By changing the category code of `%` to `9` (this is what the `doc` package does by [`\MakePercentIgnore`][doc]), writing `%`s into external temporary files is suppressed.

This is the output of revised MWE:

```latex
% \iffalse meta-comment
%<*internal>
\def\nameofplainTeX{plain}
\ifx\fmtname\nameofplainTeX\else
  \expandafter\begingroup
\fi
%</internal>
%<*install>
\input docstrip.tex
\keepsilent
\askforoverwritefalse
\usedir{tex/latex/\jobname}
\generate{
  \file{\jobname.sty}{\from{\jobname.dtx}{package}}
}
%</install>
%<install>\endbatchfile
%<*internal>
\usedir{source/latex/\jobname}
\generate{
  \file{\jobname.ins}{\from{\jobname.dtx}{install}}
}
\ifx\fmtname\nameofplainTeX
  \expandafter\endbatchfile
\else
  \expandafter\endgroup
\fi
%</internal>
%<*driver>
\documentclass{article}
\usepackage{doc}
\usepackage[all]{tcolorbox}
\usepackage{\jobname}
\makeatletter
\tcbset{
  ignore percent sign/.code={\let\tcbverbatimwrite=\tcbdocverbatimwrite},
}
\def\tcbdocverbatimwrite#1{%
  \@bsphack
  \immediate\openout\tcb@out #1
  \tcb@verbatim@begin@hook
  \let\do\@makeother\dospecials
  \catcode`\^^e=9\catcode`\^^M\active \catcode`\^^I=12
  \def\verbatim@processline{%
    \immediate\write\tcb@out
      {\the\verbatim@line}}%
  \verbatim@start}%
\makeatother
\begin{document}
  \DocInput{\jobname.dtx}
\end{document}
%</driver>
% \fi
%
% \section{User guide}
% \begin{docCommand}{mwe}{}
%   is a shorthand for ``minimum working example''.
% \end{docCommand}
% \begin{dispExample}
%   You need to inculude MWE (\mwe) in your question.
% \end{dispExample}
% \begin{dispExample*}{ignore percent sign}
%   MWE (\mwe) helps others help you.
% \end{dispExample*}
% \section{Implementation}
%    \begin{macrocode}
%<*package>
%    \end{macrocode}
% Basic information of the package.
%    \begin{macrocode}
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{MWE}[2017/06/29 v1.0.0 MWE for my proposal]
%    \end{macrocode}
% MWE is an acronym for ``minimum working example''.
%    \begin{macrocode}
\newcommand*{\mwe}{minimum working example}
%    \end{macrocode}
%    \begin{macrocode}
%</package>
%    \end{macrocode}
```

![patch](https://user-images.githubusercontent.com/13291527/27672464-1ac0622e-5cd6-11e7-87f6-dd1195488913.png)

There is leading whitespaces remaining but this is not a problem here as `autogobble` option of the `minted` package or the `lstautogobble` package will take care of this. So I think my patch is enough for a prototype.

I'm not fully familiar with the structure of this package, so there might be a better implementation. Also there should be a better name for the key or internal macro. That's why I opened this issue rather than sending a pull request.

[doc]: http://mirrors.ctan.org/macros/latex/base/doc.pdf#subsection.3.15

**Comment by T-F-S** [comment]
Thank you for providing this proposal. I do not use DocStrip myself, but I will test your code in the near future to see, if this option can be added without problems. On first glance, I think this (or something adapted) should work.

**Comment by T-F-S** [comment]
With `tcolorbox` version 4.10, there is a new option `verbatim ignore percent` which should have the same effect than your proposed `ignore percent sign` (with a slightly different implementation).

Thank you again for your very precise and elaborate input.
