### ISSUE TITLE
How to obtain a box with invisible equation and working equation reference

### ISSUE THREAD

**Issue by tnschmid** [T-F-S/tcolorbox#303]
I'm creating lecture notes for a course and I want to create a teacher and a student version based on a global boolean. The boolean controls the visibility of equations (and maybe other content) inside a tcolorbox. Currently I'm setting `upperbox=visible` (teacher version) or `upperbox=invisible` (student version).

This approach leads to equation labels not working properly, the equation counter is increment but the label is not found. (see image "Problematic student version"). Ideally only the equation should be invisible and the equation number should be still displayed ("Ideal outcome").

 Working teacher version: 
![image](https://github.com/user-attachments/assets/bd993f4e-473d-45e9-827d-61edcdeb2678)

Problematic student version:
![image](https://github.com/user-attachments/assets/ef6b0b8e-9f7e-4951-ab9f-dd441910319a)

Ideal outcome:
![image](https://github.com/user-attachments/assets/b551d073-075c-4b8d-97ee-e74a300dc7f2)

Is this possible with the current tcolorbox package or what are possible workarounds to achieve the desired outcome (working equation reference and number inside the box)?

**Comment by T-F-S** [comment]
With `upperbox=invisible`, the whole content of the box is dropped including the label. There is no tcolorbox package solution to avoid this.

My possible workaround would be a textual one, i.e. instead of "The equation inside the box is (5)" I would refer "The equation inside box 0.1 is used for bla bla" ...

Another way (with limitations) is to put the equation in a separate box which can be hidden or displayed:

```latex
\documentclass{article}
\usepackage{amsmath}
\usepackage[skins,theorems]{tcolorbox}

\begin{document}

\begin{tcolorbox}[ams equation upper,colback=yellow!10!white,colframe=red!50!black]
\tcboxmath[blankest,invisible]{a^2 + b^2 = c^2} \label{myequation}
\end{tcolorbox}

Equation~\eqref{myequation}

\end{document}
```
![grafik](https://github.com/user-attachments/assets/549198ed-899f-4c60-a57b-a13de22eec0b)

**Comment by tnschmid** [comment]
I believe the approach using the second hidden box works well for my needs—thank you! 
Could you briefly explain the limitations of this method?

**Comment by T-F-S** [comment]
> Could you briefly explain the limitations of this method?

It would not work for `align` environments since `&` could not be put in such a box on one line and another `&` in a box on the second line.

**Comment by tnschmid** [comment]
Thank you! Closing.
