### ISSUE TITLE
Wrong command name of \tcbsetmanagerlayers in documentation

### ISSUE THREAD

**Issue by BlackForester** [T-F-S/tcolorbox#32]
The documentation of tcolorbox v.4.11 describes the macro \tcbsetmanagedlayer, whereas the code has 
\tcbsetmanagedlayers, so this is either a typo or a command name change?

This is asked on TeX.SE as well: https://tex.stackexchange.com/q/401053/31729

With kindest regards

Christian Hupfer

**Comment by T-F-S** [comment]
Thank you for pointing me to that. Currently, I don't have much time for TeX.SE and I missed this question.

The macro name is and will be `\tcbsetmanagedlayers`. The missing `s` is a typo of the documentation. I will correct the documentation for the next version.

I hope to have more time for TeX.SE after Christmas.

**Comment by T-F-S** [comment]
Solved with version 4.12.
