### ISSUE TITLE
Backbround shading issue with two colours when using \tcblower and \tcbsubtitle

### ISSUE THREAD

**Issue by AndrewMathas** [T-F-S/tcolorbox#36]
I'm not sure if this is a bug or user error, but as reported at https://tex.stackexchange.com/questions/414537/tcolorbox-background-color-of-subtitle when `\tcblower` and `\tcbsubtitle` are both used the background colour from the lower section starts one line early above the subtitle:

```
\documentclass[a4paper]{article}
\usepackage{tcolorbox,enumitem}
\tcbuselibrary{skins,xparse}

\begin{document}

\begin{tcolorbox}[skin=bicolor,title=Main Title,
    colframe=red!75!black,colback=blue!10!white,colbacklower=green!10,
   width=0.5\linewidth,height=0.5\linewidth]
    The upper part. \par ~~~\par ~~~\par ~~~\par ~~~\par 

\tcblower
\tcbsubtitle[before skip=\baselineskip]%
      {My subtitle}
    The lower part.
  \end{tcolorbox}

\end{document}
```
A hack to fix the problem is to add `\vskip0pt` after `\tcblower` and use `before skip=-\baselineskip`.

**Comment by T-F-S** [comment]
It is not a bug, but just the effect of some standard distance values.

I added an answer with further explanations and a way to avoid the effect at
https://tex.stackexchange.com/questions/414537/tcolorbox-background-color-of-subtitle/414928#414928

**Comment by AndrewMathas** [comment]
Thanks for the explanation - and for tcolorbox which is great!
