### ISSUE TITLE
doc improvement for shadow color in "drop shadow" 

### ISSUE THREAD

**Issue by annoporci** [T-F-S/tcolorbox#37]
This is a suggestion for doc improvement, rather than an issue as such.

The color of "drop shadow" comes out in a default gray color and it took me a while to figure out that its color can be controlled with e.g. ``drop shadow = blue``. 

Before figuring it out, I had tried the following:  ``colframe``, ``colback``, ``colbacklower``, ``colupper``, ``collower``, ``coltext``, ``coltitle``, ``colbacktitle`` which appear in the index (on page 479) next to **Colors**. Because ``drop shadow`` does not have the ``col`` prefix and is not listed near the color items, it was not immediately obvious to me that it could be used to control color. I suggest something like adding drop shadow and its cousins right below **Colors** in the index.

**Comment by T-F-S** [comment]
Currently, I am not sure about a category for such things like `drop shadow`, but I will think about it.

**Comment by T-F-S** [comment]
The shadow color is documented and explained with many examples on page 182ff of the package documentation (page from from `4.13`). Directly at `/tcb/drop shadow` (page 182) there is the color option with implementation example. For the index, I do not see a new color category for shadow. `drop shadow` itself is found in the index at page 481 and 486.
