### ISSUE TITLE
Alignment of `title after break`

### ISSUE THREAD

**Issue by u-fischer** [T-F-S/tcolorbox#41]
There seem to be no keys comparable to the `halign title` for the first box to adjust the alignment of follow up titles  in a breakable sequence: 

```
\documentclass{article}

\usepackage[most]{tcolorbox}
\usepackage{lipsum}
\begin{document} 

\begin{tcolorbox}[breakable,title=Test,title after break=continued,center title] %continued is not centered
\lipsum
\end{tcolorbox}
\end{document}
```

**Comment by T-F-S** [comment]
Currently, the follow up titles inherit the color and font of the main title, but not the adjustment.
You are right, it seems logical that also the adjustment should be given to the follow up titles.
I think I will change that.

**Comment by T-F-S** [comment]
Integrated in version 4.14 (2018-07-26)
