### ISSUE TITLE
tocdepth and tcblistof

### ISSUE THREAD

**Issue by proteusGIT** [T-F-S/tcolorbox#42]
Hi,

I just debugged my code for quite some time and I think that tcolorbox could be improved.
To omit sections for the appendix in my toc I added \setcounter{tocdepth}{0} when the appendix started.
However, this resulted in empty lists of definitions, theorems, etc.
I did not realize this when it happend.

Please either set \setcounter{tocdepth}{1} for those lists in tcolorbox or display a warning if it is 0.

Thanks!

**Comment by T-F-S** [comment]
Warning implemented with version 4.14 (2018-07-26)
