### ISSUE TITLE
\NewTCBListing partially gobbles its content under certain conditions

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#43]
As pointed out by the following MWE, a `\NewTCBListing` defined with an optional argument, gobbles the beginning of its content when used without its optional argument.

```latex
\documentclass{article}
\usepackage{tcolorbox}
\usepackage{xparse}
\usepackage{listings}

\tcbuselibrary{listings,xparse}

\NewTCBListing{mybox}{ O{} }{listing only,#1}

\begin{document}
\begin{mybox}[colframe=red]
\documentclass{article}
\end{mybox}

\begin{mybox}[]
\documentclass{article}
\end{mybox}

\begin{mybox}
\documentclass{article}
\end{mybox}
\end{document}
```
![document0](https://user-images.githubusercontent.com/1032633/40724940-8503f624-6422-11e8-8f59-4c82412a0d6d.png)

**Comment by T-F-S** [comment]
I compiled your example with a two month old MiKTeX and I did not get the problem with `\NewTCBListing`. Here, `xparse (2018/02/21)` was used.

Afterwards, I updated my distribution, but `tcolorbox` did not change. I get the described problem now using `xparse (2018/05/12)`.

So, something changed from one `xparse` version to the next. `xparse` is a high-level interface - there might be changes on lower levels.

Unfortunately, I have no idea what has changed and what `tcolorbox` could do to circumvent the problem...

Your second code with `\newtcblisting` is OK to fail - that was one reason why I made the xparse variants...

**Comment by T-F-S** [comment]
I added an question under https://tex.stackexchange.com/questions/434928/xparse-gobbles-characters-using-an-optional-argument to look for help with the `xparse` problem.

**Comment by dbitouze** [comment]
OK, wait and see :)

**Comment by jfbu** [comment]
When I try

```latex
\begin{mybox}\relax
\documentclass{article}
\end{mybox}
```

in @dbitouze's example I get an empty line in output both in TL2017 and TL2018 (updated a few days ago).

![capture d ecran 2018-06-04 a 17 31 03](https://user-images.githubusercontent.com/2589111/40926664-17200b12-681d-11e8-9be4-0b2ea15dfcbd.png)

Is this expected?

**Comment by T-F-S** [comment]
I'm currently working for a new `tcolorbox` release in the near future.

Since the situation currently is unchanged, I adapt the `tcolorbox` documentation to the new `xparse` behaviour and recommend using the `!` modifier.

I will keep this issue open until it is clear, if the old behaviour comes back for environments or if users should be advised to change their documents...

**Comment by T-F-S** [comment]
> I will keep this issue open until it is clear, if the old behaviour comes back for environments or if users should be advised to change their box definitions...

It is now more than 4 years later and it is clear that one has to use the `!` modifier. Therefore, I close the issue.
