### ISSUE TITLE
scaled fonts for tcbposter

### ISSUE THREAD

**Issue by nignasi** [T-F-S/tcolorbox#46]
This is not an issue but a suggestion. 

To my knowledge almost all `poster` production packages (a0poster, baposter, tikzposter, ...) include some mechanisms to automatically adjust font size to poster dimensions. If a a4paper is used, fonts use 10pt-12pt but if its a0paper, the "normalfont" is quite larger. 

With `tcbposter` this mechanisms are not provided. May be you have never considered `tcolorbox` a package for poster production but `tcbposter` library is a very nice tool for it. So, could you consider adding this tool, or at least some comments about this aspect in `tcolorbox` documentation?

Thank you,

Ignasi

**Comment by T-F-S** [comment]
Actually, I already implemented that feature and forgot myself...

See Section 19.6 "Font Scaling" where the `fontsize` option is documented.
