### ISSUE TITLE
url in reference 18 to 20 is invalid

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#48]
Each item of reference of package doc provides a url. The url provided by reference 18 to 20, http://www.unibw.de/bw/sturm, is now invalid.

I'm not sure if https://www.unibw.de/bw/professuren/thomas-sturm is the updated url.

**Comment by T-F-S** [comment]
Yes, you are right with your observation.

It is a pity that the old shortcut URL became obsolete according to some organisational changes. I used it at many places. Obviously, I missed to replace every occurrence...

Thank you. I will correct this for the next version.

**Comment by T-F-S** [comment]
Solved with version 4.15 (2018-12-07)

**Comment by muzimuzhi** [comment]
Thanks
