### ISSUE TITLE
Problem centering a raster

### ISSUE THREAD

**Issue by nignasi** [T-F-S/tcolorbox#52]
When `center` option is applied to a tcbraster with fixed width, the option is inherited by every inner box. This destroys the result. Same happens with `tcbitemize`. Is this a known behaviour?

```
\documentclass{article}
\usepackage[most]{tcolorbox}

\begin{document}

\begin{tcbraster}[raster width=5cm]
\begin{tcolorbox} a \end{tcolorbox}
\begin{tcolorbox} a \end{tcolorbox}
\end{tcbraster}

\begin{tcbraster}[raster width=5cm, center]
\begin{tcolorbox} a \end{tcolorbox}
\begin{tcolorbox} a \end{tcolorbox}
\end{tcbraster}

\begin{tcbitemize}[raster width=5cm]
\tcbitem a
\tcbitem b
\end{tcbitemize}

\begin{tcbitemize}[raster width=5cm, center]
\tcbitem a
\tcbitem b
\end{tcbitemize}

\end{document}
```

**Comment by T-F-S** [comment]
Two contradicting options are given to the boxes:
- `raster width=5cm`  commands them to have a width of under 2.5cm
- `center` commands them to spread to the width of the line (for the bounding box)

The following code shows the bounding boxes:

```latex
\documentclass{article}
\usepackage[most]{tcolorbox}

\tcbsetforeverylayer{enhanced, show bounding box}

\begin{document}

\begin{tcbraster}[raster width=5cm]
\begin{tcolorbox} a1 \end{tcolorbox}
\begin{tcolorbox} a2 \end{tcolorbox}
\end{tcbraster}

\begin{tcbraster}[raster width=5cm, center]
\begin{tcolorbox} a3 \end{tcolorbox}
\begin{tcolorbox} a4 \end{tcolorbox}
\end{tcbraster}

\begin{tcbitemize}[raster width=5cm]
\tcbitem a1
\tcbitem b2
\end{tcbitemize}

\begin{tcbitemize}[raster width=5cm, center]
\tcbitem a3
\tcbitem b4
\end{tcbitemize}

\begin{tcolorbox}
Example box for comparison.
\end{tcolorbox}

\end{document}
```

![test_308_raster](https://user-images.githubusercontent.com/7982989/49152855-5a9e0100-f314-11e8-99df-db9335530547.png)
 
So, the width is set correctly and the bounding box is set correctly. But, now the raster has a width of twice the line width. You see the bounding box of the hidden boxes on the right hand side.

The short answer is: this is not a bug, but usage of contradicting options.

**Comment by nignasi** [comment]
Then the question is how can we center a tcbraster which doesn't occupy the whole line width?

**Comment by T-F-S** [comment]
The easiest way is to insert proper left and right skip values.

For your example width of `5cm`, we need `(\linewidth-5cm)/2` on each side of the raster. Currently, these terms have to be guarded by a `\dimexpr`, but I am thinking about some modifications to avoid this.

The following code should do the trick:

```latex
\documentclass{article}
\usepackage[most]{tcolorbox}

\begin{document}

\begin{tcbraster}[
  raster left skip=\the\dimexpr(\linewidth-5cm)/2\relax,
  raster right skip=\the\dimexpr(\linewidth-5cm)/2\relax
]
\begin{tcolorbox} a1 \end{tcolorbox}
\begin{tcolorbox} a2 \end{tcolorbox}
\end{tcbraster}

\begin{tcbitemize}[
  raster left skip=\the\dimexpr(\linewidth-5cm)/2\relax,
  raster right skip=\the\dimexpr(\linewidth-5cm)/2\relax
]
\tcbitem a3
\tcbitem a4
\end{tcbitemize}

\end{document}

```

**Comment by T-F-S** [comment]
Added to with version 4.15 (2018-12-07)
