### ISSUE TITLE
Typo in manual

### ISSUE THREAD

**Issue by tmelorc** [T-F-S/tcolorbox#53]
As the  image shows, there is a typo on Manual for version 4.14 (2018/07/26). 

Twice `next` word.

![selecao_113](https://user-images.githubusercontent.com/15181573/49235400-30664500-f3e1-11e8-84fc-bfcc9c496829.jpg)

**Comment by T-F-S** [comment]
Thank you for reporting the typo. I will correct it.

**Comment by T-F-S** [comment]
Corrected with version 4.15 (2018-12-07)

**Comment by tmelorc** [comment]
Nice, thanks for attention.
