### ISSUE TITLE
Height control: apply 'add to height=<length>' to 'equal height group=<id>'

### ISSUE THREAD

**Issue by Hotschke** [T-F-S/tcolorbox#6]
I am using tcolorbox to create a poster. I use the feature `equal height group=<id>` to get aligned boxes.
I have encountered a situation where I would like to use the feature `add to height` to add to the height of a group a specific value to modify the size of a certain box.

Currently (v3.73) if `equal height group` is specified `add to height` is ignored.

Is it possible to make `add to height` work together with `equal height group`?

I have figured out a workaround, but possibly it is not difficult to apply the field `add to height`.

My MWE is:

```latex

\documentclass[final]{beamer}
\usepackage[orientation=portrait,size=a0,scale=1.4,debug]{beamerposter}
\usepackage{calc}
\usepackage{tcolorbox}

\setbeamersize{text margin left=1cm, text margin right=1cm}
\setbeamertemplate{background}[grid][step=1cm]

\newlength\MyColSep
\setlength\MyColSep{1cm}

% WORKAROUND:
\makeatletter
\ifcsundef{tcb@ehg@height@A}{\csdef{tcb@ehg@height@A}{4cm}}{}
\ifcsundef{tcb@ehg@height@B}{\csdef{tcb@ehg@height@B}{4cm}}{}
\makeatother

\tcbset{
  lefttitle=1cm,
  toptitle=0.8cm,
  bottomtitle=0.8cm,
  top=1ex,
  fonttitle=\large,
  bottom=1ex,
  before skip=1.0cm,
  after skip=1.0cm,
}

\begin{document}
\begin{frame}
\begin{columns}[onlytextwidth]
  \begin{column}{\textwidth/3-\MyColSep/2}
    \begin{tcolorbox}[title=Group A, equal height group=A]
      \centering
      {\tiny tiny}\par
      {\scriptsize scriptsize}\par
      {\footnotesize footnotesize}\par
      {\normalsize normalsize}\par
    \end{tcolorbox}
    % \begin{tcolorbox}[title=Group B minus 1cm, equal height group=B, add to height=-1cm]
    % WORKAROUND:
    \begin{tcolorbox}[title=Group B minus 1cm, height=\csuse{tcb@ehg@height@B}-1cm]
      \centering
      {\tiny tiny}\par
      {\scriptsize scriptsize}\par
      {\footnotesize footnotesize}\par
      {\normalsize normalsize}\par
      {\large large}\par
      {\Large Large}\par
      {\LARGE LARGE}\par
    \end{tcolorbox}
  \end{column}
  \begin{column}{\textwidth/3*2-\MyColSep/2}
    \begin{columns}[onlytextwidth]
      \begin{column}{\textwidth/2-\MyColSep/2}
        \begin{tcolorbox}[title=Group B, equal height group=B]
          \centering
          {\tiny tiny}\par
          {\scriptsize scriptsize}\par
          {\footnotesize footnotesize}\par
          {\normalsize normalsize}\par
          {\large large}\par
          {\Large Large}\par
          {\LARGE LARGE}\par
          {\Huge Huge}\par
        \end{tcolorbox}
      \end{column}
      \begin{column}{\textwidth/2-\MyColSep/2}
        \begin{tcolorbox}[title=Group B, equal height group=B]
          \centering
          {\tiny tiny}\par
          {\scriptsize scriptsize}\par
          {\footnotesize footnotesize}\par
          {\normalsize normalsize}\par
        \end{tcolorbox}
      \end{column}
    \end{columns}
    % \begin{tcolorbox}[title=Group A minus 1cm, equal height group=A, add to height=-1cm]
    % WORKAROUND:
    \begin{tcolorbox}[title=Group A minus 1cm, height=\csuse{tcb@ehg@height@A}-1cm]
      \centering
      {\tiny tiny}\par
      {\scriptsize scriptsize}\par
      {\footnotesize footnotesize}\par
    \end{tcolorbox}
  \end{column}
\end{columns}
\end{frame}
\end{document}
```

**Comment by T-F-S** [comment]
The `add to height` option can only be used in combination with a fixed height box, but the a `equal height group` is not fixed in that sense. If it could be applied, there would remain the question if it applies to the group height or not.

But, following your application example and workaround, I could image something very similar to your workaround as a new feature. This could be some `inherit height from group` or `use height from group` to copy the group height as fixed height. Then, `add to height` could be applied.

**Comment by Hotschke** [comment]
I had imagined following:
The option `add to height` should apply only to a specific box not the group and can of course only be applied in the second latex run (if equal height group is used), otherwise the group height is still unknown. But the second run is necessary anyway.

Of course your proposal is also good.

**Comment by T-F-S** [comment]
I will think about other possibilities to change the current height algorithm to apply `add to height` directly in this case. But I cannot promise that it will be changed, because many other parts depend on the current implemention and I have to act carefully here to not break other things.

**Comment by Hotschke** [comment]
If applying `add to height` directly would easily break too many things and adding the option `inherit height from group` is safe to do,  it would make more sense adding the option. Introducing bugs into working code is not what people want.

BTW, I am quite happy with tcolorbox for posters: the last times I've created posters, I was fiddling around to align the bottom of adjacent boxes; I had added  vspaces at the end of the block environment from beamer which I had to adjust everytime I was changing somewhere else; this was really annoying.
I am still  struggling getting consistent intercolumn spacing managed globally; but I leave this for the next time I create a poster.

**Comment by T-F-S** [comment]
tcolorbox `3.80 (2015/11/27)`  has a new option `use height from group` which allows to set a box to the height of a group. Then, this height can be modified by `add to height`. Also, the new macro `\tcbheightfromgroup` may be helpful.

**Comment by Hotschke** [comment]
Thank you very much for incorporating this so fast. I also like the new possibility of `tcbheightfromgroup`. I have already encountered a new situation where I actually would like to use them. However, I am struggling using them. Do you see what I am doing wrong?

```latex
documentclass[final,t]{beamer}
\usepackage[orientation=portrait,size=a0,scale=1.4,debug]{beamerposter}
\usepackage{mwe}
\setbeamersize{text margin left=1cm, text margin right=1cm}
\usepackage{tcolorbox}

% WORKAROUND:
\makeatletter
\ifcsundef{tcb@ehg@height@A}{\csdef{tcb@ehg@height@A}{0pt}}{}
\ifcsundef{tcb@ehg@height@B}{\csdef{tcb@ehg@height@B}{0pt}}{}
\ifcsundef{tcb@ehg@height@C}{\csdef{tcb@ehg@height@C}{0pt}}{}
\makeatother

% THIS DOES NOT WORK YET:
\tcbheightfromgroup{\groupA}{A}
\tcbheightfromgroup{\groupB}{B}
\tcbheightfromgroup{\groupC}{C}

\tcbset{
  lefttitle=1cm,
  toptitle=0.8cm,
  bottomtitle=0.8cm,
  top=1ex,
  fonttitle=\large,
  bottom=1ex,
  before skip=1.0cm,
  after skip=1.0cm,
}

\begin{document}
\begin{frame}
\begin{columns}[onlytextwidth]
  \begin{column}{\linewidth/2}
    \begin{tcolorbox}[
        title={Golden},
        equal height group=A,
        ]
      \includegraphics[width=\linewidth]{example-image-golden}
    \end{tcolorbox}
    \begin{tcolorbox}[
        title={16x9},
        equal height group=B,
        ]
      \includegraphics[width=\linewidth]{example-image-16x9}
    \end{tcolorbox}
  \end{column}
  \begin{column}{0.4925\linewidth}
    \begin{tcolorbox}[
      title={Adjustable},
     % WORKAROUND:
      height=\csuse{tcb@ehg@height@A}+\csuse{tcb@ehg@height@B}-\csuse{tcb@ehg@height@C},
      % USE NEW DEFINED MACROS:
      % height=\groupA+\groupB-\groupC,
    ]
    hello
    \vfill
    world, \groupA
    \end{tcolorbox}
    \begin{tcolorbox}[
        title={16x10},
        equal height group=C,
      ]
      \includegraphics[width=\linewidth]{example-image-16x10}
    \end{tcolorbox}
  \end{column}
\end{columns}
\end{frame}
\end{document}
```

**Comment by T-F-S** [comment]
You have to move 

    \tcbheightfromgroup{\groupA}{A}
    \tcbheightfromgroup{\groupB}{B}
    \tcbheightfromgroup{\groupC}{C}

from the preamble into the main text (after `\begin{document}`). The height information is saved into the auxiliary file which is read after the preamble.

**Comment by Hotschke** [comment]
I didn't know this. Perfect: the macros work now. Thanks. I close this issue.
