### ISSUE TITLE
Feature request in documentation library

### ISSUE THREAD

**Issue by joulev** [T-F-S/tcolorbox#65]
I am writing a very minimal summary of the Ti*k*Z manual for my friends &ndash; the Ti*k*Z manual itself is just too long for them to read :). I'm using `documentation` library and am quite happy with it.

However, it seems that I can only document and make reference for a macro, an environment, or a key, but not a Ti*k*Z operation like

![image](https://user-images.githubusercontent.com/44609036/56261020-a86ca780-6103-11e9-89b1-b33a862eb5ad.png)

<sup>(page 151 of `pgfmanual.pdf` version 3.1.2)</sup>

I think this feature should be added in the next version of `tcolorbox`.

**Comment by T-F-S** [comment]
Well, these are very special TikZ things which might not be needed for other things like documenting TikZ (?).

But, on the other hand, it would be nice to have such a feature. I add it to my TODO list, but I cannot promise to add it before trying some implementation tests.

**Comment by joulev** [comment]
Yes, such operations seem to be in Ti*k*Z only. However, in some other packages, which I don't know of, there may be similar things that can't be documented using available `documentation` options. Anyway, I think a "general" command should be needed, which allows "before code" and "after code" (`docCommand` only accepts "after code") and works like this
```latex
\begin{docElement}{--}                     % Code without backslash
                  {\cs{path}\verb| ... |}  % Before code
                  {\verb| ...;|}           % After code
    <content>
\end{docElement}
```
where one can customize what is in the "heading".

In my "minimal Ti*k*Z", I've applied a workaround, but it is (of course) very messy, also labelling and indexing is very hard.

**Comment by T-F-S** [comment]
Added to version 4.21 (2019-09-19)

**Comment by joulev** [comment]
I updated my TeX distribution today. Thanks; it works very well so far.
