### ISSUE TITLE
Problem with `hide` (Beamer support)

### ISSUE THREAD

**Issue by nignasi** [T-F-S/tcolorbox#66]
Following code shows four boxes on last slide. This is correct, but fourth box and slide are only shown if `alert` option is included on last box. I think `hide=<-3>` means hide this box in three first slides and show it from fourth slide. But the fourth slide is not created unless `alert=<4>` is included. Is this a bug?

```
\documentclass{beamer}
\usepackage[most]{tcolorbox}

\begin{document}
\tcbset{beamer alerted/.style={}}
\begin{frame}
\begin{tcbitemize}[raster columns=3, enhanced]
   \tcbitem
            bla 1
   \tcbitem[hide=<-1>]
            bla 2
   \tcbitem[hide=<-2>]
            bla 3
   \tcbitem[hide=<-3>, alert=<4>]
            bla 4
\end{tcbitemize}
\end{frame}
\end{document}
```

**Comment by T-F-S** [comment]
I would not call it an error, because `hide=<-3>` means to hide the box in the first three slides and show it on following slides, **if** they exist. If there are only three slides, the box is never shown.

You already proposed a way to get the behaviour your want. Another possibilty to insert a fourth slide would be to add an `only=<4>{}` which does nothing but to force a fourth slide:

```latex
\documentclass{beamer}
\usepackage[most]{tcolorbox}

\begin{document}
\begin{frame}
\begin{tcbitemize}[raster columns=3, enhanced]
   \tcbitem
            bla 1
   \tcbitem[hide=<-1>]
            bla 2
   \tcbitem[hide=<-2>]
            bla 3
   \tcbitem[hide=<-3>,only=<4>{}]
            bla 4
\end{tcbitemize}
\end{frame}
\end{document}
```

**Comment by nignasi** [comment]
I thought that being `\tcbitem[hide=<-3>] bla4` the fourth item, it would result into a fourth slide which had been hidden on previous three slides.
According your answer, except when `alert` or `only` are included, this contents won't create the new slide. Is this correct?

**Comment by T-F-S** [comment]
Yes, this is correct. Actually `hide=<-3>` is equal to `\only<-3>{\tcbset{beamer hidden}}` which does not create the fourth slide.
