### ISSUE TITLE
Feature request: add new option "minted options app" and others

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#73]
Currently, the option `minted option` in minted library has a long initial value (from tcb doc, sec. 16.5), 
```latex
tabsize=2, fontsize=\small, breaklines, autogobble
```

1. When user need to pass more options to minted, I find having a new option `minted options app` is more convenient than just use `minted option` and paste its initial value. 
2. This new option can be implemented as simply as
    ```latex
    \tcbset{
      minted options app/.style={
        minted options/.append={#1}
      }
    }
    ```

3. New option `listing options app` can be defined similarly. I am not sure whether the corresponding `pre` options is practically useful.
4. These new options may live in tcb library `hooks`.

**Comment by T-F-S** [comment]
I consider this a good idea and I will add such options for the next version.

**Comment by muzimuzhi** [comment]
Sorry, the suggested implementation is wrong. This following code works, as I have tested.

```latex
\tcbset{
  minted options app/.code={\appto\kvtcb@minted@options{,#1}},
  listing options app/.code={\appto\kvtcb@listingoptions{,#1}}
}
```
This treatment is used very often in option definitions of tcb `hooks` library. The `,` in `,#1` is used to separate the last kv-pair already in `\kvtcb@minted@options` and the first kv-pair in `#1`.

The paired `pre` part can be defined similarly.
```latex
\tcbset{
  minted options pre/.code={\preto\kvtcb@minted@options{#1,}},
  listing options pre/.code={\preto\kvtcb@listingoptions{#1,}}
}
```
------
**Why `.append` does not work**

From doc of `pgfkeys`, the keys `.append`, `.append code` and `.append style` are used to append value, code and style stored in key, respectively. But `minted options` is defined by `.store in`.
https://github.com/T-F-S/tcolorbox/blob/1361ddea1cd421a726cb33f62ddd1879a656f63f/tex/latex/tcolorbox/tcbminted.code.tex#L56
In this way the key just calls a `\def` command (see [implementation of `.store in`](https://github.com/pgf-tikz/pgf/blob/f5d0ffd6e4a553d40855370c692fea6e33a0026d/tex/generic/pgf/utilities/pgfkeys.code.tex#L822)), but stores nothing about the accepted value (e.g. the `linenos` in `minted options={linenos}`). Thus an occurrence of `\kvtcb@minted@options` in definition of `minted options app` is avoid-less.

I have used the `.code={\preto...}` implementation for sometime and it works ok. Recently I encountered the key `.append` and I am too excited to take a careful test before use it to "simplify" the old implementation (since I think it is more elegant to define app-or-pre options without the use of internal macros like `\kvtcb@minted@options`). Sorry again.

**Comment by T-F-S** [comment]
Yes, I am aware of that and my implementation looks quite identical to your update.
Sorry, I forgot to wrote that I took your feature request as an idea, but implemented it differently:

```latex
\tcbset{
  minted options app/.code={\appto\kvtcb@minted@options{,#1}},
  minted options pre/.code={\preto\kvtcb@minted@options{#1,}},
  listing options app/.code={\appto\kvtcb@listingoptions{,#1}},
  listing options pre/.code={\preto\kvtcb@listingoptions{#1,}},
}

```

**Comment by muzimuzhi** [comment]
Also I think the braces around `\appto\xxx{,#1}` is not necessary, but adds more safe and consistency if the value of `.code` contains `,` directly (not enclosed in a group).

**Comment by T-F-S** [comment]
Added to version 4.21 (2019-09-19)
