### ISSUE TITLE
why toprule don't effective????

### ISSUE THREAD

**Issue by uesugikhun** [T-F-S/tcolorbox#74]
When I change toprule, it changes to /tcb/ titlerule on 11 pages of the guidance document. If I change the titlerule, it doesn't change anything.
![image](https://user-images.githubusercontent.com/24800747/61575557-8f5b0480-aaff-11e9-868d-ec0efae1c2f6.png)

**Comment by muzimuzhi** [comment]
Can you provide a minimal working example? (see [help on Meta-TeX-SX](https://tex.meta.stackexchange.com/q/228/79060))

I have tested with tcolorbox v4.20, and the following example works fine.

```latex
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{skins}
\begin{document}

\tcbset{skin=draft, colbacktitle=red!50, toprule=5pt, titlerule=10pt}
\begin{tcolorbox}[title=ABC]
content
\end{tcolorbox}

\end{document}
```

![image](https://user-images.githubusercontent.com/6376638/61593554-717ec400-ac13-11e9-8a23-c8c4520bb9e7.png)
