### ISSUE TITLE
auto counter vs. beamer \pause

### ISSUE THREAD

**Issue by tallmarmot** [T-F-S/tcolorbox#80]
I am wondering if you could redefine `\tcb@proc@counter@auto` to become something like

```
\def\tcb@proc@counter@auto#1{%
  \newcounter{tcb@cnt@#1}%
  \csxdef{tcb@cnt@#1}{tcb@cnt@#1}%
  \tcb@proc@counter@autoanduse{#1}%
  \ifcsname resetcounteronoverlays\endcsname%<-added
  \resetcounteronoverlays{tcb@cnt@#1}%<-added
  \fi%<-added
}
```

See https://tex.stackexchange.com/a/510350/194703 for the context. The purpose is to avoid increasing the counter unnecessarily when using beamer with pauses. 

Servus,
M.

**Comment by T-F-S** [comment]
Thank you for the input. Yes, I think that I could do something like that.
Currently, I'm quite busy, but I put it on my 'todo' list :-)

**Comment by T-F-S** [comment]
New initialization option `reset counter on overlays` for version 4.22 (2019-11-15)
