### ISSUE TITLE
format the counter of tcbitemize

### ISSUE THREAD

**Issue by antfp** [T-F-S/tcolorbox#81]
Is there any way to format (Roman or Alph) the counter behind \thetcbrasternum inside a tcbitemize? Something like 

\documentclass[oneside,11pt,]{article}
\usepackage{tcolorbox}
\tcbuselibrary{many}
\begin{document}
\begin{tcbitemize}[raster columns=2, raster equal height=rows, 
coltitle=black, attach title to upper, title={\Alph{tcbrasternum}\enspace}]
\tcbitem AA
\tcbitem BB
\tcbitem CC
\end{tcbitemize}
\end{document}

**Comment by joulev** [comment]
LaTeX itself has some ways to do so.

```latex
\documentclass[oneside,11pt]{article}
\usepackage{tcolorbox}
\tcbuselibrary{many}
\newcommand*\Whatever{\symbol{\numexpr64+\thetcbrasternum}} % A,B,C
\newcommand*\whatever{\symbol{\numexpr64+\thetcbrasternum}} % a,b,c
\begin{document}
\begin{tcbitemize}[raster columns=2, raster equal height=rows,
coltitle=black, attach title to upper, title={\Whatever\enspace}]
  \tcbitem AA
  \tcbitem BB
  \tcbitem CC
\end{tcbitemize}
\end{document}
```

**Comment by antfp** [comment]
Ok. Thank you. It would be so nice that tcolorbox provided a **tcbenumerate** environment...

**Comment by joulev** [comment]
You are welcome. Actually I am wondering why the environment is called `tcbitemize` instead of `tcbenumerate`, because the items in `tcbitemize` are numbered.

**Comment by T-F-S** [comment]
Behind `\thetcbrasternum`, there is no LaTeX counter which could be formatted. But it is easy to add an auxiliary counter which can be formatted as wished.

In the following example, I called this counter `myrasternum`:

    \newcounter{myrasternum}

A good place for inserting the current `\thetcbrasternum` is inside some `phantom` code:

    phantom={\setcounter{myrasternum}{\thetcbrasternum}}

Now, the LaTeX counter `myrasternum` may be used in LaTeX fashion:

```latex
\documentclass[oneside,11pt]{article}
\usepackage{tcolorbox}
\tcbuselibrary{many}

\newcounter{myrasternum}

\begin{document}

\begin{tcbitemize}[raster columns=2, raster equal height=rows,
  coltitle=black, attach title to upper,
  phantom={\setcounter{myrasternum}{\thetcbrasternum}},
  title={\Alph{myrasternum}\enspace}]
  \tcbitem AA
  \tcbitem BB
  \tcbitem CC
\end{tcbitemize}

\begin{tcbitemize}[raster columns=2, raster equal height=rows,
  coltitle=black, attach title to upper,
  phantom={\setcounter{myrasternum}{\thetcbrasternum}},
  title={\alph{myrasternum}\enspace}]
  \tcbitem AA
  \tcbitem BB
  \tcbitem CC
\end{tcbitemize}

\begin{tcbitemize}[raster columns=2, raster equal height=rows,
  coltitle=black, attach title to upper,
  phantom={\setcounter{myrasternum}{\thetcbrasternum}},
  title={\Roman{myrasternum}\enspace}]
  \tcbitem AA
  \tcbitem BB
  \tcbitem CC
\end{tcbitemize}

\begin{tcbitemize}[raster columns=2, raster equal height=rows,
  coltitle=black, attach title to upper,
  phantom={\setcounter{myrasternum}{\thetcbrasternum}},
  title={\roman{myrasternum}\enspace}]
  \tcbitem AA
  \tcbitem BB
  \tcbitem CC
\end{tcbitemize}

\end{document}
```

**Comment by LuisCastilloL** [comment]
Hello, I have a question. How can reference a tcbitem? I want something like this

\documentclass[oneside,11pt]{article}
\usepackage{tcolorbox}
\tcbuselibrary{many}
\usepackage{enumerate}

\newcounter{myrasternum}

\begin{document}

\begin{tcbitemize}[raster columns=2, raster equal height=rows,
  coltitle=black, attach title to upper,
  phantom={\setcounter{myrasternum}{\thetcbrasternum}},
  title={\Alph{myrasternum}\enspace}]
  \tcbitem AA
  \tcbitem\label{second} BB
  \tcbitem CC
\end{tcbitemize}

See the content of the box \ref{second}

\end{document}

**Comment by T-F-S** [comment]
Using

`\tcbitem[label=second] BB`

should do the trick.

**Comment by LuisCastilloL** [comment]
In this case, the reference is undefined

**Comment by muzimuzhi** [comment]
@LuisCastilloL Hmm, you have to update the `\@currentlabel` by (manually calling) `\refstepcounter`.
```tex
\documentclass[oneside,11pt]{article}
\usepackage{tcolorbox}
\tcbuselibrary{raster}
\usepackage{enumerate}

\newcounter{myrasternum}
\renewcommand{\themyrasternum}{\Alph{myrasternum}}

\begin{document}
\begin{tcbitemize}[raster columns=2, raster equal height=rows,
  coltitle=black, attach title to upper,
  phantom={\setcounter{myrasternum}{\numexpr\thetcbrasternum-1}\refstepcounter{myrasternum}},
  title={\themyrasternum\enspace}]
  \tcbitem AA
  \tcbitem[label=second] BB
  \tcbitem CC
\end{tcbitemize}

See the content of the box \ref{second}
\end{document}
```
Also a `tcbrasternum` example (I tried to modify `tcbraster` env to support auto calling `\refstepcounter{tcbrasternum}` for each `\tcbitem` but didn't made it.):
```tex
\begin{tcbitemize}[raster columns=2, raster equal height=rows,
  coltitle=black, attach title to upper,
  code={\renewcommand{\thetcbrasternum}{\Alph{tcbrasternum}}},
  phantom={\addtocounter{tcbrasternum}{-1}\refstepcounter{tcbrasternum}},
  title={\thetcbrasternum\enspace}]
  \tcbitem AA
  \tcbitem[label=second] BB
  \tcbitem CC
\end{tcbitemize}
```

**Comment by T-F-S** [comment]
> 
> 
> In this case, the reference is undefined

@LuisCastilloL  I was too fast with my too short answer, but @muzimuzhi added the needed ingredient `\refstepcounter`. I would go for the first variant in @muzimuzhi answer.

**Comment by T-F-S** [comment]
Since version `4.50 (2021-05-21)`, `\thetcbrasternum` changed to output the content of a counter, see [issue #119](https://github.com/T-F-S/tcolorbox/issues/119).

For the next version `4.52` (or higher), I added some code allowing that a box in a `raster` or `tcbitemize` can also be labeled to reference the `tcbrasternum`. With the next version (and the uploaded preview), the following will work:

```latex
\documentclass[oneside,11pt]{article}
\usepackage{\tcbpkgprefix tcolorbox}
\tcbuselibrary{raster}
\usepackage{enumerate}

\begin{document}
\begin{tcbitemize}[raster columns=2, raster equal height=rows,
  coltitle=black, attach title to upper,
  code={\renewcommand{\thetcbrasternum}{\Alph{tcbrasternum}}},
  title={\thetcbrasternum\enspace}
  ]
  \tcbitem AA
  \tcbitem[label=second] BB
  \tcbitem CC
\end{tcbitemize}

See the content of the box \ref{second}.

\end{document}
```

**Comment by LuisCastilloL** [comment]
I need that tcbitemize wor like itemize for the labeling and cross-references. 

In the @muzimuzhi answer, if I have a two environments tcbitemize and I refer an item of the second environment `hyperref` sends to the first environment

\documentclass[oneside,11pt]{article}
\usepackage{tcolorbox}
\tcbuselibrary{raster}
\usepackage{enumerate}
\usepackage{hyperref}

\newcounter{myrasternum}
\renewcommand{\themyrasternum}{\Alph{myrasternum}}

\begin{document}
\begin{tcbitemize}[raster columns=2, raster equal height=rows,
  coltitle=black, attach title to upper,
  phantom={\setcounter{myrasternum}{\numexpr\thetcbrasternum-1}\refstepcounter{myrasternum}},
  title={\themyrasternum\enspace}]
  \tcbitem AA
  \tcbitem[label=second] BB
  \tcbitem CC
\end{tcbitemize}

See the content of the box \ref{first}

\newpage

\begin{tcbitemize}[raster columns=2, raster equal height=rows,
  coltitle=black, attach title to upper,
  phantom={\setcounter{myrasternum}{\numexpr\thetcbrasternum-1}\refstepcounter{myrasternum}},
  title={\themyrasternum\enspace}]
  \tcbitem[label=first] AA
  \tcbitem BB
  \tcbitem CC
\end{tcbitemize}

See the content of the box \ref{second}

\end{document}

@T-F-S In the next version `4.52` is possible to add more functions from `enumerate` to the `tcbitemize`? That would be wonderful :)

**Comment by muzimuzhi** [comment]
> In the @muzimuzhi answer, if I have a two environments tcbitemize and I refer an item of the second environment `hyperref` sends to the first environment

Adding `\counterwithin*{myrasternum}{tcbraster}` after `\renewcommand{\themyrasternum}{...}` will do the job. The key is to make `myrasternum` uniquely numbered. Above it's made (invisibly) numbed inside `tcbraster`, a counter stepped for each `tcbraster`/`tcbitemize` environment.

> @T-F-S In the next version `4.52` is possible to add more functions from `enumerate` to the `tcbitemize`? That would be wonderful :)

Which `enumerate` functions do you expect? Imho `tcbitemize` has noting to do with list environments. It just borrowed the "name".

**Comment by LuisCastilloL** [comment]
The format of the counter and crossreferences. Actually, I use `tcbitemize`  for lists inside of proofs, this environment is very useful because the format has more options, but I have the problem from the previous post with the crossreferences.

Originally I need a list with `tcolorbox` support,  in the package documentations there is an example similar, in the package documentation, there is an application of `\tcolorboxenvironment`  in this the `itemize` environment is boxed inside a `tcolorbox`. I defined a similar environment for enumerate, it works for the usual enumeration but if I change the format of counter directly in this new environment doesn't work properly.

```
\documentclass[oneside,11pt]{article}
\usepackage{tcolorbox}
\tcbuselibrary{skins}
\newenvironment{myenumerate}{%
\begin{enumerate}}{\end{enumerate}}
\tcolorboxenvironment{myenumerate}{blanker,
before skip=6pt,after skip=6pt,
borderline west={3mm}{0pt}{red}}
\begin{document}
Some text.
\begin{myenumerate}[a)]
\item Alpha
\item Beta
\item Gamma
\end{myenumerate}
More text.
\end{document}
```

**Comment by muzimuzhi** [comment]
You need either `\usepackage{enumerate}` or `\usepackage[shortlabels]{enumitem}`. (getting a bit off-topic, is it?)
