### ISSUE TITLE
Undefined references in tcolorbox-(tutorial|example)-poster files

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#83]
Both `tcolorbox-tutorial-poster` and `tcolorbox-example-poster` files suffer from undefined references : [**??**] (just a matter of a missing extra compilation).

**Comment by T-F-S** [comment]
Thank you for reporting. I will update my script for generating these documents.

**Comment by T-F-S** [comment]
Resolved for version 4.22 (2019-11-15)
