### ISSUE TITLE
Aligning \sidepar with box title

### ISSUE THREAD

**Issue by mikkelee** [T-F-S/tcolorbox#84]
I'm trying to make a sidepar align with the title of a pair of boxes, but it aligns with the bottom of the box by default.

I have tried putting it inside the boxes, but then it overlaps the edges.

How do I move it up?

```latex
\documentclass{memoir}
\usepackage{tcolorbox}
\usepackage[showframe]{geometry}

\begin{document}

\noindent%
\sidepar{Sidepar}%
\begin{tcolorbox}[nobeforeafter, width=\linewidth/2, box align=top]
Box 1
\tcblower
First line.\\
Second line.
\end{tcolorbox}
\begin{tcolorbox}[nobeforeafter, width=\linewidth/2, box align=top]
Box 2
\tcblower
First line.\\
Second line.
\end{tcolorbox}

\end{document}
```

![Screen Shot 2019-10-31 at 05 13 59](https://user-images.githubusercontent.com/644671/67918698-b664b000-fb9d-11e9-8179-75ed39afb0d0.png)

**Comment by nignasi** [comment]
If you declare a `title` (not an upper box), you can use the `title` node to overlay a sidepar text
![Captura](https://user-images.githubusercontent.com/2562430/67938194-51c24900-fbcf-11e9-80c1-1480a54c8053.PNG)


```
\documentclass{memoir}
\usepackage[most]{tcolorbox}
\usepackage[showframe]{geometry}

\begin{document}

\noindent%
\begin{tcolorbox}[enhanced, 
	nobeforeafter, 
	width=\linewidth/2, 
	box align=top, 
	title=Box 1,
	overlay={\node[anchor=east] at ([xshift=-\marginparsep]title.west) {Sidepar};}]
First line.\\
Second line.
\end{tcolorbox}
\begin{tcolorbox}[nobeforeafter, width=\linewidth/2, box align=top, title=Box 2]
First line.\\
Second line.
\end{tcolorbox}
\end{document}
```

**Comment by mikkelee** [comment]
Aha, thanks! :)
