### ISSUE TITLE
"raster before skip" does not accept all glues any more

### ISSUE THREAD

**Issue by oscarlevin** [T-F-S/tcolorbox#85]
It used to be (compiling with TeX Live 2018) that you could use the option `raster before skip={3em plus 1em}`.  Now (TeX Live 2019) this throws the error "! Missing number, treated as zero".  

The `before skip` option still works fine.  Also, defining a \newlength and setting it to `{3em plus 1em}` does not throw the error.

    Some more text.
    \newlength{\testlength}
    \setlength{\testlength}{3em plus 1em}
    \begin{tcbitemize}[raster before skip=\testlength] % Works
      \tcbitem One
      \tcbitem Two
    \end{tcbitemize}
    Even more text. 
    \begin{tcbitemize}[raster before skip={3em plus 1em}]  % Error
      \tcbitem One
      \tcbitem Two
    \end{tcbitemize}

**Comment by T-F-S** [comment]
I can confirm this error. It was introduced while correcting / enhancing other things.

I think it can be removed for the next version, but I have to do some more tests.

**Comment by T-F-S** [comment]
Resolved for version 4.22 (2019-11-15)
