### ISSUE TITLE
Breakable boxes within breakable boxes

### ISSUE THREAD

**Issue by osbornemj** [T-F-S/tcolorbox#86]
If I create a `tcbtheorem` with the option `breakable` it breaks across pages.  But if I nest within that `tcbtheorem` another `tcbtheorem` with the option `breakable`, the inner box is not broken across pages.  The code for an MWE (well, it's more or less minimal) is pasted below.

I'm not sure that the `breakable` option is advertised to work when nested, so this is probably not a bug but a feature request: is it possible to make a box within a box breakable?

\documentclass[12pt]{article}
\RequirePackage[many]{tcolorbox}

\newtcbtheorem[number within=section]{example}{Example}{
  breakable,
  enhanced,
  before upper={\noindent\parindent15pt},
  colback=blue!5,
  colframe=blue!35!black,
  fonttitle=\bfseries}{m}

\newtcbtheorem{exampleClaim}{Claim}{
  breakable,
  enhanced,
  colback=green!5,
  colframe=green!45!blue!80!black,
  fonttitle=\bfseries}{cl}

\newtcbtheorem{exampleProof}{Proof}{
  breakable,
  enhanced,
  before upper={\noindent\parindent15pt},
  before={\par\pagebreak[0]\medskip\parindent=0pt},
  after={\par\medskip},
  colback=black!5,
  colframe=black!65!white,
  fonttitle=\bfseries}{pr}

\begin{document}
\section{Examples}
\begin{example}{Price-setting duopoly (Bertrand)}{bertrand}
As in the previous example, two producers of a good compete in a market.  But now we assume that each of them chooses a price (rather  than a quantity). Consumers purchase the good from the producer whose price is lower; if the prices are the same, the consumers are split equally between the producers.  Specifically, if the price \(p^i\) of producer~\(i\) is lower than the price of \(j\), the amount of the good demanded from \(i\) is  \(\max\{0,1-p^i\}\) and the amount demanded from \(j\) is zero; if the prices are the same, equal to \(p\), the amount demanded from each firm is \(\frac{1}{2}\max\{0,1-p\}\).
Each firm produces the amount demanded from it and in doing so incurs the  cost \(c\in [0,1)\) per unit.

\begin{exampleClaim*}{}
The only Nash equilibrium of a price-setting duopoly is \((c,c)\).
\end{exampleClaim*}
\begin{exampleProof*}{}
The action pair \((c,c)\) is a Nash equilibrium: if a producer increases her price her profit remains   \(0\), and if she reduces her price her profit becomes negative.

We now argue that \((c,c)\) is the only Nash equilibrium.  Suppose that  \((p^1,p^2)\) is a Nash equilibrium. 

We have  \(\min\{p^1,p^2\}\ge c\), since otherwise a producer who charges \(\min\{p^1,p^2\}\)  makes a loss, which she can avoid by raising her price to \(c\). 

Also, \(p^1=p^2\), because if \(p^i<p^j\) then (\textit{i)}~if \(c=p^i\) then \(i\) can increase her payoff (from 0) by raising her price a little, (\textit{ii})~if  \(c<p^i<1\) then \(j\) can increase her payoff by reducing her price to \(p^i\), and (\textit{iii})~if \(1\le p^i\) then \(i\) can increase her payoff (from \(0\)) by reducing her price  below 1.  

Finally, if \(c<p^1=p^2<1\) then each player's payoff is positive and either player can reduce her price slightly and almost double that payoff; if \( p^1=p^2\ge 1\) then each player's payoff is 0 and either player can obtain a positive payoff by offering a price between \(c\) and~\(1\).
\end{exampleProof*} 
\end{example}

\end{document}

**Comment by T-F-S** [comment]
I would love to have breakable boxes inside breakable boxes for a long time.

Alas, there is no way to achieve this feature for TeXnical reasons. Therefore, I fear, I cannot put that on my todo list...

**Comment by osbornemj** [comment]
Thanks for your response --- I was afraid that might be the case.  (I will either have to think of some way to manually achieve the same result or will have to reformat the claims-within-examples.)
