### ISSUE TITLE
Is there any way to add bbox of all text in tex but not affecting layout?

### ISSUE THREAD

**Issue by Ramlinbird** [T-F-S/tcolorbox#87]
Hi, I want to add bounding box to all texts in the tex, but don't change anything else (for example the indentation, margin ...). In other words, I want to plotting bbox on the original pdf. How can I implement this? Thanks a lot.

**Comment by T-F-S** [comment]
I fear that cannot be done with `tcolorbox`.

Maybe, you should ask at https://tex.stackexchange.com/, if there are other ways to show the bounding boxes of a TeX text.

**Comment by Ramlinbird** [comment]
> I fear that cannot be done with `tcolorbox`.
> 
> Maybe, you should ask at https://tex.stackexchange.com/, if there are other ways to show the bounding boxes of a TeX text.

Thanks a lot for your fast replying!
