### ISSUE TITLE
Tcolorbox parbox=false option breaks by height fill option

### ISSUE THREAD

**Issue by sergiokapone** [T-F-S/tcolorbox#88]
Possible bug: tcolorbox parbox=false option breaks by height fill option
[https://tex.stackexchange.com/questions/521634/tcolorbox-parbox-false-option-breaks-by-height-fill-option](https://tex.stackexchange.com/questions/521634/tcolorbox-parbox-false-option-breaks-by-height-fill-option)

**Comment by T-F-S** [comment]
I think, this can be repaired, see
https://tex.stackexchange.com/questions/521634/tcolorbox-parbox-false-option-breaks-by-height-fill-option/522776#522776

**Comment by T-F-S** [comment]
Resolved for version 4.30 (2020-04-28)
