### ISSUE TITLE
[Library 'documentation'] Document similar commands

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#89]
Sometimes, we have to document similar commands that have the same optional and mandatory arguments, and same (or similar) behavior.

I know that, in such a case, the `pgf` way is to document each of them, sometimes (but not always!) with a hint about the similarity of the following commands and this makes the documentation comprehensive and consistent.

But, in case of numerous such similar commands, the trap is that one doesn't exhaustively read each of them and, possibly, miss one of the commands which exceptionally behave (slightly) differently. Another inconvenience is that it makes the documentation voluminous and not nice to read.

Hence my feature requests: Provide a way for the `documentation` library to

1. clearly document similar commands.
1. highlight some variants in the behavior of the some of these similar commands.

If it is not possible, what could be nice is something which looks like the following but:

- without any indentation for `\Foo` and `\FOO` lines,
- with smaller vertical space between `\foo`, `\Foo` and `\FOO` lines.

```latex
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{documentation}
\begin{document}
\begin{docCommand}{foo}{\oarg{bar}\marg{baz}}
\begin{docCommand}{Foo}{\oarg{bar}\marg{baz}}
\end{docCommand}
\begin{docCommand}{FOO}{\oarg{bar}\marg{baz}}
\end{docCommand}
  These commands share the same behavior:
  \begin{itemize}
  \item their \meta{baz} mandatory argument is used to specify what is the baz
    they are based upon
  \item their \meta{bar} optional argument can be used to specify what is the bar
    they are based upon
  \end{itemize}
\end{docCommand}
\end{document}
```
![test](https://user-images.githubusercontent.com/1032633/71533359-806f4e00-28f8-11ea-98b6-f66c25390838.png)

A nice syntax for this could be to a comma separated list value for the similar commands:
```latex
\begin{docCommand}{foo,Foo,FOO}{\oarg{bar}\marg{baz}}
  These commands share the same behavior:
  [...]
\end{docCommand}
```

**Comment by muzimuzhi** [comment]
I have implemented a similar general form of `docCommand` environment. The new environment has name `docCommands` and its syntax is
```tex
\begin{docCommands}[<options>]
{
  {<name1>}
    {<parameter1>}
    {<description1>},
  {<name2>}
    {<parameter2>}
    {<description2>},
  {<name3>}
    {<parameter3>}
    {<description3>}
}
  <command description>
\end{docCommands}
```
![image](https://user-images.githubusercontent.com/6376638/71556732-f994af80-2a76-11ea-834c-c75adda24aaa.png)

 - full code: [https://github.com/muzimuzhi/latex-examples/blob/master/utilities/tcb-documentation.tex](tcb-documentation.tex)
 - use demo: [https://github.com/muzimuzhi/latex-examples/blob/master/test/tcb-documentation-test.tex](tcb-documentation-test.tex) and [https://github.com/muzimuzhi/latex-examples/blob/master/test/tcb-documentation-test.pdf](tcb-documentation-test.pdf)
 - blog that explains the code in detail: https://zhuanlan.zhihu.com/p/80849532 (in Chinese)

**Comment by T-F-S** [comment]
@muzimuzhi Your example looks very good and seems to be exactly what @dbitouze asked for :-)

**Comment by dbitouze** [comment]
@muzimuzhi Very nice indeed!

But I have a dream :) Would it be possible for the `docCommands` environment to factorize common ⟨parameters⟩ and common ⟨descriptions⟩, such as in the following scheme (maybe not suitable):
```latex
\begin{docCommands}[⟨options⟩][⟨common-parameters⟩][⟨common-description⟩]
{
  {⟨name1⟩},                                % inherits ⟨common-parameters⟩ and ⟨common-description⟩
  {⟨name2⟩}[⟨parameter2⟩],                  % inherits ⟨common-description⟩ only: ⟨parameter2⟩ != ⟨common-parameters⟩
  {⟨name3⟩}[][⟨description3⟩],              % inherits ⟨common-parameters⟩ only: (⟨description3⟩ != ⟨common-description⟩
  {⟨name4⟩}[⟨parameter4⟩][⟨description4⟩]   % ⟨parameter4⟩ != ⟨common-parameters⟩ and ⟨description4⟩ != ⟨common-description⟩
}
  ⟨command description⟩
\end{docCommands}
```

**Comment by muzimuzhi** [comment]
@T-F-S 
 - `{docCommands}` uses the same scheme as `{docCommand}` except an extra `\strut` inside `{tcb@doc@head}` env, otherwise there might be thin uncolored lines between multiple `{tcb@doc@head}`s.
 - I have used some `expl3` functions because its `l3sep` (sub-)package provides helpful functions to handle double-ended queue. This is not a must.
 - If both are supported, `{docXXX}` environments can be implemented as special forms of corresponding `{docXXXs}`.

@dbitouze 
Technically, it is possible. Practically, I personally do not encourage this syntax since it adds more complex to semantic than convenience to typing. 

Moreover, should `{⟨name3⟩}[][⟨description3⟩]` be designed for inheriting `common-parameters` only, or using empty parameter and new description? Maybe a key-value design (`name=..., para=..., desc=...`) is more acceptable: if key is missing, inherit; otherwise, use new (might-be-empty) value. But this does not save any typing, as I am afraid.

**Comment by dbitouze** [comment]
@muzimuzhi 

>Moreover, should {⟨name3⟩}[][⟨description3⟩] be designed for inheriting common-parameters only, or using empty parameter and new description?

Good point!

>Maybe a key-value design (name=..., para=..., desc=...) is more acceptable: if key is missing, inherit; otherwise, use new (might-be-empty) value.

Would be nice!

> But this does not save any typing, as I am afraid.

It could be helpful from a maintenance point of view.

**Comment by muzimuzhi** [comment]
- Firstly, I forgot that, compared to `{docCommand}` env, the current `{docCommands}` env has already added a per-command-description.
    ```tex
    \begin{docCommand}[<options>]{<name>}{<parameters>}
      <command description>
    \end{docCommand}
    
    \begin{docCommands}[<options>]
    {
      % here add <description-n>
      {<name1>}{<parameter1>}{<description1>},
      {<name2>}{<parameter2>}{<description2>},
      {<name3>}{<parameter3>}{<description3>}
    }
      <commands description>
    \end{docCommands}
    ```
 - Then, considering the key-value interface `name=..., para=..., desp=...`, maybe a fully kv syntax brings more consistence:
    ```tex
    \begin{docCommands-keyval}[<options>]
      {name=<common name>, para=<common para>, desp=<common description>}
      [
        {              para=<para2>, desp=<desc2>}, % use <common name>
        {name=<name3>, desp=<desc3>},               % use <common para>
        ...
      ]
      <more commands description>
    \end{docCommands-keyval}
    ```
    This syntax can handle both single- and multiple-command situations.

@dbitouze 
In
> It could be helpful from a maintenance point of view.

did you mean that the kv syntax could be helpful from a package-and-documentation maintainer's point of view?

I am not sure if the above redesign helps. I am willing to provide an implementation if that helps you.

**Comment by muzimuzhi** [comment]
Just as I remembered, if command name inheriting is allowed, then the auto-index scheme should also be changed. Say, if the index is per-command-name, then one command (whether it has one or more lines of documented usages) should have at most one index.

**Comment by dbitouze** [comment]
@muzimuzhi 

>did you mean that the kv syntax could be helpful from a package-and-documentation maintainer's point of view?

Yes, e.g. in the case where e.g. the common description of similar commands from a same group is modified (I pretty sure you're aware of [the badness of duplicate code](https://en.wikipedia.org/wiki/Duplicate_code) :)

**Comment by muzimuzhi** [comment]
Based on codes for `{docCommands}` env, I have implemented `{docCommands-keyvals}` env (see syntax description https://github.com/T-F-S/tcolorbox/issues/89#issuecomment-570899273) in commit https://github.com/muzimuzhi/latex-examples/commit/c77104bad634bacdc9a99cea51968d13b3b8883c . Both codes and tests are updated. (Actually I have started before receiving your response, :) )

![image](https://user-images.githubusercontent.com/6376638/71782434-c624c880-3014-11ea-8bc3-4ca2093f5e88.png)

Inside one env, multiply defined labels and/or indexes are carefully avoided. That means, in the above figure, only two labels, namely `com:theorem` and `com:theorem*`, are defined.

**Comment by muzimuzhi** [comment]
More considerations may be required. In the code for `{docCommands}` and `{docCommands-keyvals}`, I have made option "doc description" from per-env to per-doc-head, since newly defined environments allow multiple doc heads in one env. This raises a general question: apart from option "doc description", do we need more per-env options to be per-doc-head options? If so, there would need a per-doc-head key subclass. 

Assume there exists a such key subclass, and a new key handler "doc variants" is defined. Then, to keep consistence with the current syntax of `{docCommand}`-family environments, these two forms might be condidates:
```tex
% current
\begin{docCommand}[<options>]{<name>}{<parameters>}
  <command description>
\end{docCommand}

% candidate 1, append a new optional arg
\begin{docCommand}[<options>]{<name>}{<parameters>}[<variant forms>]
  % call \tcbset{doc variants=<variant forms>}
  <command description>
\end{docCommand}

% candidate 2, accept new option "doc variants" in <options>
\begin{docCommand}[<options>, doc variants=<variant forms>]{<name>}{<parameters>}
  <command description>
\end{docCommand}
```
where
```abnf
<variant forms> ::= <key value> [, <key value>]*
<key value>     ::= "per-doc-head keys" 
                  | "doc name=..." | "doc parameters=..."
```

**Comment by T-F-S** [comment]
The `docCommands-keyvals` example is quite interesting, because it seems to be the most clean application just to use keys and values.

The suggestion with `doc variants` as extension for the exisiting macros is also appealing, because it avoids parallel maintenance of the current macros plus some new keyval-only macros.

With more time, I have to do some more own testing and explore implementations without `expl3` (I am not experienced enough in `expl3`).

**Comment by muzimuzhi** [comment]
> With more time, I have to do some more own testing and explore implementations without expl3 (I am not experienced enough in expl3).

Inside `{docCommands}`-like envs, there are demands to test the length of a comma separated list, pop both left and right from a list, and test whether a list is empty. `l3seq` sub-package of `expl3` provides convenient functions to handle these demands. Therefore I used functions (and also variables) from `expl3`.

Any package (or groups of macros) which can provide similar utilities would be sufficient. But, It seems that `etoolbox` does not provide such utilities.

**Comment by T-F-S** [comment]
Added to version 4.30 (2020-04-28). Among other things, there are new environments `docCommands`, `docEnvironments`, `docKeys`, `docPathOperations` which allow parallel documentation of similar macros; also see https://github.com/T-F-S/tcolorbox/blob/master/doc/latex/tcolorbox/CHANGES.

The changes to the library are made in `expl3` and are inspired by @muzimuzhi code suggestions. The implementation itself is different and changed substantial parts of the library. Therefore, old patches are not likely to work with version 4.30.

Also, there are two aspects which require attention:

  * Note that the new code reserves a small additional amount of vertical space
    for documented macros which may result in changed page breaks.
  * Note that documentation heads are now embedded inside a 'raster'
    which requires other customizations for vertical space (if needed)

On technical side, the old document environments are now special cases of the new multi-variant environments.

**Comment by dbitouze** [comment]
@T-F-S Many thanks for this. And sorry @muzimuzhi for my silence after your last contributions (was too busy).

**Comment by muzimuzhi** [comment]
@T-F-S Cool! 
@dbitouze It's ok. It is the advantage of online discussion that we can pick up/down it at any time, as long as it is not off-topic.
