### ISSUE TITLE
Need for new option "doc index=<text>"?

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#91]
In v4.21, with the newly added environments `{docPathOperation(*)}`, new option `doc label` is introduced. Similarly, do we need another new option `doc index=<text>`, which overwrites the index name from `<name>` to `<text>`?

**Comment by T-F-S** [comment]
This makes sense. I will add such an option.

**Comment by T-F-S** [comment]
Added to version 4.30 (2020-04-28).
