### ISSUE TITLE
Avoid loading lib "listingsutf8" for xetex and luatex

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#92]
This issue is a follow-up of #56 and #58, in which the incompatible relation of tcb library `listingsutf8` and engines `xelatex` and `lualatex` are discussed and explicitly documented.

But, since the tcb library style `most` and `all` both loads `listingsutf8` library, the above incompatibility seems that users of xelatex and lualatex is never recommended to use `\tcbuselibrary{most|all}`. This is a pity, and actually `tcolorbox` can do more. 

There are utilities that provides engine-detector macros. Tcb can use them to write some engine-specific codes. 
 - One option is package [`iftex`](https://ctan.org/pkg/iftex). Here is a self-explained latex2e-style example:
    ```tex
    \ifpdftex
      % unchanged
      \tcb@add@library@style{most}{many,listingsutf8,external,magazine,vignette,poster}
      \tcb@add@library@style{all}{many,minted,listingsutf8,external,magazine,vignette,poster,documentation}
    \else
      % do not load `listingsutf8`
      \tcb@add@library@style{most}{many,external,magazine,vignette,poster}
      \tcb@add@library@style{all}{many,minted,external,magazine,vignette,poster,documentation}
    \fi
    ```
 - Another option is pacakge `expl3`, with this latex3-style example:
    ```tex
    \ExplSyntaxOn
    \sys_if_engine_pdftex:TF
      {
        % unchanged
        \tcb@add@library@style{most}{many,listingsutf8,external,magazine,vignette,poster}
        \tcb@add@library@style{all}{many,minted,listingsutf8,external,magazine,vignette,poster,documentation}
      }
      {
        % do not load `listingsutf8`
        \tcb@add@library@style{most}{many,external,magazine,vignette,poster}
        \tcb@add@library@style{all}{many,minted,external,magazine,vignette,poster,documentation}
      }
    \ExplSyntaxOff
    ```

Since `expl3` will be packed into latex2e format (see [here](https://github.com/latex3/latex2e/blob/3ea69f79a54aa05a96d0be6ffe76459d612410d6/base/doc/ltnews31.tex#L172-L173)), loading `expl3` package will not add dependencies of `tcolorbox` after the next release of latex2e, which would be Feb 2020 (see [here](https://github.com/latex3/latex2e/blob/3ea69f79a54aa05a96d0be6ffe76459d612410d6/base/doc/ltnews31.tex#L115-L116)). Therefore I personally recommend the `expl3` option.

**Comment by muzimuzhi** [comment]
Moreover, `tcolorbox` can use those engine-detector utilities to totally avoid loading tcb lib `listingsutf8` for xetex and luatex:
 - if pdftex is used, load;
 - if xe- or lua-tex is used, do not load and leave messages in log.

**Comment by T-F-S** [comment]
I am open to this suggested enhancement, but two questions are open to me:

- The suggested code means that `listingsutf8` is loaded for `pdftex` only. The package documentation for the underlying `listingsutf8` also requires `pdftex` which sounds good. I just wonder, if one of the more exotic engines listed in `iftex.pdf` could be `listingsutf8` compatible and would be also excluded.

- The suggested code does not load `listings` for `most` in the `false` case. Did you just forget it in your code or is there a deeper reason for it?

**Comment by muzimuzhi** [comment]
> I just wonder, if one of the more exotic engines listed in iftex.pdf could be listingsutf8 compatible and would be also excluded.

`listingsutf8` only works with pdftex and luatex, since its implementation relies on primitives added by pdftex only. luatex can provide these primitives as macros using Lua code, and this is what package `pdftexcmds` done (`listingsutf8` uses `pdftexcmds`). No other engines work with `listingsutf8`.
 * list of pdftex primitives required by `listingsutf8`: `\pdfunescapehex`, `\pdffiledump`, and `\pdffilesize`, see the source code [here](https://github.com/ho-tex/listingsutf8/blob/7a0e1adc2c3d7a071df5667e837753be43ce4fa1/listingsutf8.dtx#L354-L356)

So, the conditions should be adjusted to "if engine is pdftex or luatex, then load `listingsutf8`, otherwise skip this tcb library".

> Did you just forget it in your code or is there a deeper reason for it?

I forget it.

**Comment by muzimuzhi** [comment]
> Moreover, `tcolorbox` can use those engine-detector utilities to totally avoid loading tcb lib `listingsutf8` for xetex and luatex:
> 
> * if pdftex is used, load;
> * if xe- or lua-tex is used, do not load and leave messages in log.

Here is an example showing this idea, which avoids changing the definition of tcb library styles.
```tex
\documentclass{article}
\usepackage{tcolorbox}
\usepackage{iftex}

\makeatletter
% Define new library #1. 
% Load file #2 if run with pdftex, otherwise load library #3.
\def\tcb@add@pdftex@library#1#2#3{%
  \tcbset{library/#1/.code={%
    \ifpdftex
      \tcb@load@library{#1}{#2}%
    \else
      \tcb@warning{Library `#1' is compatible with pdftex 
                   \MessageBreak only. Load library `#3` instead.}%
      \tcbuselibrary{#3}%
    \fi
  }%
  % uncomment the following line if inside tcolorbox.sty 
  % \DeclareOption{#1}{\appto\tcb@optionlist{,#1}}%
}}

\tcb@add@pdftex@library{listingsutf8}
  {tcblistingsutf8.code.tex}
  {listings}
\makeatother

\tcbuselibrary{listingsutf8}
% \tcbuselibrary{most}

\begin{document}
\begin{tcblisting}{}
$\int x$
\end{tcblisting}
\end{document}
```

**Comment by T-F-S** [comment]
Thank you for your input and the explanations.

I will implement a safeguard against loading `listingsutf8` for the next version. The safeguard will be directly inside the library. If xe- or lua-tex is used, a info message is written to the log. I think, a warning is too much, because `\tcbuselibrary{most}` would always produce warnings and a xetex user could not do anything to avoid the warnings.

The new code is:

```latex
\tcb@set@library@version{4.23pre1}

\tcbuselibrary{listings}

\RequirePackage{iftex}
\ifpdftex
  \let\tcb@temp\relax%
\else
  \tcb@info{Library `listingsutf8' is compatible with pdftex only.
            Library `listings` is loaded instead.}%
  \let\tcb@temp\endinput
\fi
\tcb@temp

\RequirePackage{listingsutf8}[2011/11/10]

\tcbset{
  listing utf8/.style={listing inputencoding=utf8/#1},
}

\tcbset{%
  reset@listingsutf8/.style={listing utf8=latin1},
  initialize@reset=reset@listingsutf8,
}

```

**Comment by muzimuzhi** [comment]
This is even cleaner. Thanks.

**Comment by T-F-S** [comment]
Added to version 4.30 (2020-04-28).
