### ISSUE TITLE
Is option "color frame" useless?

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#94]
Tcb option "color frame"
 - stores its value in the same command as option "color hyperlinks",
 - seems never used in code, and
 - is not documented as well.

https://github.com/T-F-S/tcolorbox/blob/b1090e27188b8ccc84c510bb83687333979e62bc/tex/latex/tcolorbox/tcbdocumentation.code.tex#L137-L138
Is this option useless, hence can be removed from source code?

**Comment by T-F-S** [comment]
Yes, I think you are right. Seems to be remains from testing in the past. I will remove it.

**Comment by T-F-S** [comment]
Removed from version 4.30 (2020-04-28).
