### ISSUE TITLE
Make \refAux consistent with hyperref boolean \ifHy@colorlinks

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tcolorbox#95]
* When hyperref boolean `\ifHy@colorlinks` is true, output of `\refCom` (and other `\refXXX{<tcb label>}` \commands) is colored; otherwise, output is uncolored. 
* But, whether `\ifHy@colorlinks` is true or false, output of `\refAux` and `\refAuxcs` is always colored.
* Value of `\ifHy@colorlinks` are effected by hyperref optons `colorlinks=true/false` and `hidelinks`.

https://github.com/T-F-S/tcolorbox/blob/b1090e27188b8ccc84c510bb83687333979e62bc/tex/latex/tcolorbox/tcbdocumentation.code.tex#L444-L445

The following example shows a refined definition of `\refAux` and `\refAuxcs` which takes value of `\ifHy@colorlinks` into consideration:
```tex
\documentclass{article}
\usepackage[documentation]{tcolorbox}
\hypersetup{colorlinks=false}

\makeatletter
% \AtBeginDocument is required since \hypersetup might be used
% after loading of tcb lib documentation.
\AtBeginDocument{%
  \ifHy@colorlinks
    \def\refAux#1{\textcolor{\kvtcb@colhyper}{\tcb@scantokens{#1}}}%
    \def\refAuxcs#1{\textcolor{\kvtcb@colhyper}{\tcb@cs{#1}}}%
  \else
    \def\refAux#1{\tcb@scantokens{#1}}%
    \def\refAuxcs#1{\tcb@cs{#1}}%
  \fi
}
\makeatother

\begin{document}
\begin{docCommand}{cmd}{\marg{code}}
content
\end{docCommand}

% each of three is uncolored (black)
\refCom{cmd}, \refAuxcs{cmdX}, \refAux{docCommand}
\end{document}
```

**Comment by muzimuzhi** [comment]
Taking `\ifHy@ocgcolorlinks` into consideration adds more consistency, but I am afraid the corresponding option `ocgcolorlinks` (links colored when viewed but uncolored when printed, see `texdoc hyperref`, sec. 5.11) is more rarely used.

**Comment by T-F-S** [comment]
I will change the implementation following your suggestion. I hope that no user trusted in such colors to be unchanged while tempering with `colorlinks` (but I don't think so).

Thank you for your input.

**Comment by T-F-S** [comment]
Changed for version 4.30 (2020-04-28).
