### ISSUE TITLE
Purpose of the \tcbfitdim option

### ISSUE THREAD

**Issue by atticus-sullivan** [T-F-S/tcolorbox#96]
I don't get the purpose of the \tcbfitdim option out of the documentation, I think that option needs further explanation (or I'm just too stupid to understand).
(My specific case is this line, I don't understand completely `box={before upper={\parskip 0.15\tcbfitdim plus 0pt minus 0pt}}`

**Comment by muzimuzhi** [comment]
From source code, `\tcbfitdim` stores the length parsed to option `fit basedim`, which represents the starting font size used by adjustment algorithm (see documentation of option `/tcb/fit basedim`).
https://github.com/T-F-S/tcolorbox/blob/b1090e27188b8ccc84c510bb83687333979e62bc/tex/latex/tcolorbox/tcbfitting.code.tex#L32

In your example, 
```tex
\tcbset{
  fit basedim=5pt,
  before upper={\parskip 0.15\tcbfitdim plus 0pt minus 0pt}
}
```
is equivalent to
```tex
\tcbset{
  fit basedim=5pt,
  before upper={\pardkip 0.75 plus 0pt minus 0pt}
}
```

**Comment by atticus-sullivan** [comment]
Hm ok, thanks for the explanation (as mentioned in my opinion this should be explained in the user manual (didn't found anything when I was searching))

My specific problem unfortunately is not solved by this but I think Github isn't the place for this, so please see [https://tex.stackexchange.com/questions/532959/pgf-tikz-with-genealogytree-and-the-before-upper-setting-for-boxes](https://tex.stackexchange.com/questions/532959/pgf-tikz-with-genealogytree-and-the-before-upper-setting-for-boxes)

**Comment by muzimuzhi** [comment]
> as mentioned in my opinion this should be explained in the user manual

I agree. Waiting for the response from repo owner.

**Comment by muzimuzhi** [comment]
> My specific problem unfortunately is not solved by this but I think Github isn't the place for this, so please see https://tex.stackexchange.com/questions/532959/pgf-tikz-with-genealogytree-and-the-before-upper-setting-for-boxes

And I have gave an answer there. Hope that helps.

**Comment by T-F-S** [comment]
@muzimuzhi explained in elaborate detail the purpose and effect of `\tcbfitdim` on stackexchange - I cannot do better.

The `genealogytree` documentation describes the `fit` processing on pages 129 to 132 with examples. It relies on the `fitting` library of `tcolorbox` which is documented there starting from page 422 including the meaning of `\tcbfitdim` (also found in the index of the `tcolorbox` documentation). That is just for reference - @muzimuzhi has given a fine answer on stackexchange.

**Comment by muzimuzhi** [comment]
It seems `tcolorbox` only documents `\tcbfitdim` by saying

> The font dimension `\tcbfitdim` can also be used to ...

Users may be more familiar with "font size" than "font dimension". (And confused with "font size" and "font baseline skip" as well.) Hence, more words about what exactly is stored in `\tcbfitdim` would help.

**Comment by T-F-S** [comment]
`\tcbfitdim` got its own description entry in version 4.30 (2020-04-28).
