### ISSUE TITLE
Conflict with changes package

### ISSUE THREAD

**Issue by yguilhem** [T-F-S/tcolorbox#97]
As pointed by the following MWE, if `tcolorbox` is loaded (before or after) the `changes` package, we get some conflicts. Maybe a warning should be added to the documentation because the `\comment` command seems to be only an internal one for `tcolorbox`.
```
\documentclass{minimal}

% If tcolorbox is loaded after -> \comment command is already defined when
%                                 loading changes package and leads to an error
%\usepackage{tcolorbox}

% Everything is OK if changes package is loaded alone
\usepackage{changes}

% If tcolorbox is loaded after -> \comment command is redefined without errors
%                                 but the comment is lost.
%\usepackage{tcolorbox}

\begin{document}
Here is a MWE \comment{Short comment}.
\end{document}
```

**Comment by muzimuzhi** [comment]
`tcolorbox` loads `verbatim` package and the latter one defines `comment` environment (`\comment` and `\endcomment`). Hence actually this is a conflict of `verbatim` and `changes` packages.

Workaround 1: Use another command name for `\comment` from `changes` pacakge.
```tex
\documentclass{article}
\usepackage{changes}

\let\changesComment\comment
\usepackage{tcolorbox}

\begin{document}
content\changesComment{Sure} content
\end{document}
```

Workaround 2: Use another environment name for `comment` from `verbatim` package. This way, you can still use `\comment` with syntax from `changes`.
```tex
\documentclass{article}
\usepackage{tcolorbox}
\makeatletter
% backup "comment" env
\let\vrb@comment    \comment
\let\comment        \@undefined
\let\vrb@endcomment \endcomment

% use backup in tcolorbox internals
\def\tcb@@end@v@@d{%
  \vrb@endcomment%
  \tcb@layer@dec%
}

\def\tcb@@capture@v@@d{%
  \let\endtcolorbox\tcb@@end@v@@d%
  \vrb@comment%
}
\makeatother

\usepackage{changes}

\begin{document}
content\comment{Sure} content
\end{document}
```

![image](https://user-images.githubusercontent.com/6376638/77685601-a29b6980-6fd6-11ea-8b19-bb51566c7b6b.png)

**Comment by T-F-S** [comment]
As @muzimuzhi commented, this is not a `tcolorbox` problem, but a conflict between the packages `verbatim` and `changes` - maybe, the authors should be informed.

But, it hurts not much to implement most of 'Workaround 2' for `tcolorbox` and I am going to do it for the next version. What I will not do is
```latex
\let\comment  \@undefined
```
because it would disable the `comment` environment from the standard package `verbatim` for all users of `tcolorbox`. The undefining has to be done by the user:

```latex
\documentclass{article}

\usepackage{tcolorbox}

%---------- patch
\makeatletter
% save 'comment' from 'verbatim'
\let\tcb@verbatim@comment\comment
\let\tcb@verbatim@endcomment\endcomment

\def\tcb@@end@v@@d{%
  \tcb@verbatim@endcomment%
  \tcb@layer@dec%
}

\def\tcb@@capture@v@@d{%
  \let\endtcolorbox\tcb@@end@v@@d%
  \tcb@verbatim@comment%
}
\makeatother
%---------- end patch

\undef\comment
\undef\endcomment
\usepackage{changes}


\begin{document}
content\comment{Sure} content

\begin{tcolorbox}[void]
I am invisible
\end{tcolorbox}

\end{document}
```

The same patch the other way around:

```latex
\documentclass{article}

\usepackage{changes}

\let\changesComment\comment

\usepackage{tcolorbox}

%---------- patch
\makeatletter
% save 'comment' from 'verbatim'
\let\tcb@verbatim@comment\comment
\let\tcb@verbatim@endcomment\endcomment

\def\tcb@@end@v@@d{%
  \tcb@verbatim@endcomment%
  \tcb@layer@dec%
}

\def\tcb@@capture@v@@d{%
  \let\endtcolorbox\tcb@@end@v@@d%
  \tcb@verbatim@comment%
}
\makeatother
%---------- end patch

\let\comment\changesComment


\begin{document}
content\comment{Sure} content

\begin{tcolorbox}[void]
I am invisible
\end{tcolorbox}

\end{document}

```

**Comment by yguilhem** [comment]
Thank you both for your quick replies. Sorry for the wrong problem identification.
I will inform the authors of changes package.

**Comment by muzimuzhi** [comment]
> But, it hurts not much to implement most of 'Workaround 2' for `tcolorbox` and I am going to do it for the next version. What I will not do is
> 
> ```
> \let\comment  \@undefined
> ```
> 
> because it would disable the `comment` environment from the standard package `verbatim` for all users of `tcolorbox`.

This reminds me. I have opened a feature request to `verbatim` package.

**Comment by yguilhem** [comment]
Oops, I already opened a [new issue](https://gitlab.com/ekleinod/changes/-/issues/80) on `changes` package GitLab...

**Comment by muzimuzhi** [comment]
> Oops, I already opened a [new issue](https://gitlab.com/ekleinod/changes/-/issues/80) on `changes` package GitLab...

Don't worry. Both ways (fix from `verbatim` side or `changes` side) may help. It's a great thing that users, developers, and maintainers work together to get to a more thorough solution.

**Comment by T-F-S** [comment]
Patch added to version 4.30 (2020-04-28).
